const V132_BOSS_PROGRESS_KEY='V132_BOSS_PROGRESS';
function readV132BossProgress_(){try{return JSON.parse(PropertiesService.getUserProperties().getProperty(V132_BOSS_PROGRESS_KEY)||'{}')}catch(e){return {}}}
function setV132BossProgress(boss,item,value){
  if(v132BossGuides_().map(x=>x.name).indexOf(String(boss||''))<0)throw new Error('Unknown boss.');
  item=String(item||'');if(!/^(gear|mechanic):[a-z0-9_-]+$/.test(item))throw new Error('Unknown checklist item.');
  const all=readV132BossProgress_();all[boss]=all[boss]||{};
  if(value===false||value===''||value==null)delete all[boss][item];else all[boss][item]=value===true?true:String(value);
  PropertiesService.getUserProperties().setProperty(V132_BOSS_PROGRESS_KEY,JSON.stringify(all));return all[boss];
}
function v132BossGuides_(){
  const S=(label,summary,items)=>({label:label,summary:summary,items:items||[]});
  return [
    {name:'Scurrius',image:'https://oldschool.runescape.wiki/images/Scurrius.png',source:'https://oldschool.runescape.wiki/w/Scurrius/Strategies',facts:[['Combat','200 solo / 250 group'],['Hitpoints','500 solo / 1,500 group'],['Styles','Melee, Ranged, Magic'],['Max hit','13 melee; 8/7 solo mage/range'],['Weakness','Rat-bone weapons']],mechanics:['Protect from Melee when close','React to falling rubble','Deal with summoned rats'],setups:[S('Learner / Budget','Accessible melee equipment and food.',['Rune-or-better melee weapon','Rune-or-better armour','Food']),S('Recommended / Consistent','Rat-bone weapon with prayer and strength gear.',['Bone mace','Prayer equipment','Melee strength equipment']),S('Efficient / Upgraded','Higher melee-strength gear around the encounter weapon.',['Bone mace','Upgraded melee strength gear','Super combat potion']),S('Best in Slot (BIS)','The source does not define one universal BIS inventory; use its highest-ranked choices for your group size.',[])],extras:['No quest gate','Food','Combat potion','Prayer restoration']},
    {name:'Barrows',image:'https://oldschool.runescape.wiki/images/Barrows_minigame.png',source:'https://oldschool.runescape.wiki/w/Barrows/Strategies',facts:[['Encounter','Six brothers'],['Weakness','50% Air weakness'],['Prayer drain','Every 18 seconds'],['Access','Priest in Peril'],['Rewards','Chest potential based']],mechanics:['Plan an efficient brother route','Manage periodic prayer drain','Identify the tunnel brother'],setups:[S('Learner / Budget','Low-cost magic with defensive armour.',['Iban’s staff','Tank armour','Spade','Emergency teleport']),S('Recommended / Consistent','Powered staff and defensive equipment.',['Powered staff','Tank armour','Prayer restoration']),S('Efficient / Upgraded','Higher-ranked magic damage and utility choices.',['Upgraded powered staff','Magic damage equipment','Barrows teleport']),S('Best in Slot (BIS)','Use first-ranked equipment-table choices for the chosen route; no universal inventory is asserted.',['Highest-ranked documented staff','Highest-ranked documented magic slots'])],extras:['Priest in Peril','Spade','Food','Prayer restoration']},
    {name:'Giant Mole',image:'https://oldschool.runescape.wiki/images/Giant_Mole.png',source:'https://oldschool.runescape.wiki/w/Giant_Mole/Strategies',facts:[['Combat','230'],['Hitpoints','200'],['Style','Crush'],['Max hit','21'],['Respawn','9.6 seconds']],mechanics:['Use Protect from Melee','Track burrow locations','Maintain run energy'],setups:[S('Learner / Budget','Accessible melee equipment and stamina support.',['Melee weapon','Melee armour','Light source']),S('Recommended / Consistent','Strong melee setup plus a locator.',['Strong melee weapon','Falador shield 3 or 4','Stamina potion']),S('Efficient / Upgraded','High-damage ranged or melee choices from ranked tables.',['High-damage weapon','Damage-boosting equipment','Falador shield 4']),S('Best in Slot (BIS)','Twisted bow is among the most effective documented options; exact best choices depend on combat style.',['Twisted bow (ranged method)','Highest-ranked documented slots'])],extras:['Light source','Stamina potion','Food']},
    {name:'Moons of Peril',image:'https://oldschool.runescape.wiki/images/Eclipse_Moon.png',source:'https://oldschool.runescape.wiki/w/Moons_of_Peril/Strategies',facts:[['Hitpoints','500 each'],['Defence','60'],['Off-style defence','+100 melee / +500 magic & ranged'],['Standard combo','4, 8, 20'],['Protection prayers','No effect']],mechanics:['Match each Moon’s melee weakness','Perform special-phase movement','Gather and cook dungeon supplies'],setups:[S('Learner / Budget','Three accessible melee weapons.',['Stab weapon','Slash weapon','Crush weapon','Defensive armour']),S('Recommended / Consistent','Higher-accuracy swaps with strong defence.',['Upgraded stab weapon','Upgraded slash weapon','Upgraded crush weapon','Tank armour']),S('Efficient / Upgraded','Top-ranked documented weapon choices by weakness.',['High-ranked stab weapon','High-ranked slash weapon','High-ranked crush weapon']),S('Best in Slot (BIS)','No single loadout exists because each Moon has a different weakness.',['First-ranked stab choice','First-ranked slash choice','First-ranked crush choice'])],extras:['Children of the Sun','Dungeon food','Dungeon potions']},
    {name:'Sarachnis',image:'https://oldschool.runescape.wiki/images/Sarachnis.png',source:'https://oldschool.runescape.wiki/w/Sarachnis/Strategies',facts:[['Combat','318'],['Hitpoints','400'],['Styles','Melee, Ranged'],['Max hit','31'],['Weakness','Crush']],mechanics:['Switch prayer after web attack','Control spawned spiders','Position for web phases'],setups:[S('Learner / Budget','Accessible crush weapon and defence.',['Dragon mace or documented alternative','Defensive armour','Antipoison']),S('Recommended / Consistent','Stronger crush gear and prayer sustain.',['Strong crush weapon','Melee strength gear','Prayer restoration']),S('Efficient / Upgraded','Higher-ranked crush and strength choices.',['Upgraded crush weapon','Upgraded strength gear']),S('Best in Slot (BIS)','Use first-ranked documented slot choices for the crush method.',['First-ranked crush weapon','First-ranked documented slots'])],extras:['Forthos Dungeon access','Antipoison','Food']},
    {name:'Zulrah',image:'https://oldschool.runescape.wiki/images/Zulrah_%28serpentine%29.png',source:'https://oldschool.runescape.wiki/w/Zulrah/Strategies',facts:[['Combat','725'],['Hitpoints','500'],['Attack speed','3 ticks'],['Damage','Ranged, Magic, venom'],['Stats by form','Context dependent']],mechanics:['Recognise forms and rotations','Switch prayers and gear','Move between safe positions','Maintain venom protection and recoil'],setups:[S('Learner / Budget','Compact two-style switches.',['Budget ranged setup','Budget magic setup','Ring of recoil','Antivenom protection']),S('Recommended / Consistent','Reliable powered staff and ranged setup.',['Powered staff','Reliable ranged weapon','Recoil effect']),S('Efficient / Upgraded','Higher-ranked two-style equipment.',['Upgraded magic setup','Upgraded ranged setup','Damage jewellery']),S('Best in Slot (BIS)','Ranked equipment differs by combat style and method; no phase-independent BIS inventory exists.',['First-ranked magic choices','First-ranked ranged choices'])],extras:['Regicide','Antivenom','Recoil effect','Emergency teleport']},
    {name:'Vorkath',image:'https://oldschool.runescape.wiki/images/Vorkath.png',source:'https://oldschool.runescape.wiki/w/Vorkath/Strategies',facts:[['Hitpoints','750'],['Styles','Melee, Ranged, Magic, dragonfire'],['Specials','Acid pool; zombified spawn'],['Weakness','Method dependent'],['Max hit','Context dependent']],mechanics:['Avoid the fireball','Walk the acid phase','Crumble Undead the spawn','Maintain antifire and venom protection'],setups:[S('Learner / Budget','Crossbow method with salve effect.',['Crossbow setup','Salve amulet (ei)','Antifire protection','Crumble Undead runes']),S('Recommended / Consistent','Dragon hunter crossbow method.',['Dragon hunter crossbow','Salve amulet (ei)','Shield option']),S('Efficient / Upgraded','Upgraded ranged or lance method.',['Upgraded dragonbane weapon','High-ranked style equipment']),S('Best in Slot (BIS)','Best equipment differs between ranged and melee methods.',['First-ranked ranged choices','First-ranked melee choices'])],extras:['Dragon Slayer II','Extended super antifire','Antivenom','Prayer restoration']},
    {name:'Phantom Muspah',image:'https://oldschool.runescape.wiki/images/Phantom_Muspah.png',source:'https://oldschool.runescape.wiki/w/Phantom_Muspah/Strategies',facts:[['Forms','Ranged and melee'],['Styles','Ranged, Magic, Melee'],['Prayer shield','Prayer damage relevant'],['Spike phase','Movement required'],['Max hit','Context dependent']],mechanics:['Switch protection prayer','Kite the melee form','Avoid spikes','Break the prayer shield'],setups:[S('Learner / Budget','Ranged-focused method with optional magic.',['Ranged setup','Optional magic switch','Stamina support']),S('Recommended / Consistent','Strong ranged setup and shield solution.',['Strong ranged weapon','Prayer-shield solution','Stamina support']),S('Efficient / Upgraded','Higher-ranked ranged and optional magic.',['Upgraded ranged setup','Upgraded magic switch']),S('Best in Slot (BIS)','Choices depend on ranged-only versus hybrid strategy.',['First-ranked ranged choices','First-ranked hybrid choices'])],extras:['Secrets of the North','Prayer restoration','Stamina potion']},
    {name:'Corrupted Gauntlet',image:'https://oldschool.runescape.wiki/images/Corrupted_Hunllef.png',source:'https://oldschool.runescape.wiki/w/The_Gauntlet/Strategies',facts:[['Combat','894'],['Hitpoints','1,000'],['Styles','Magic, Ranged'],['Max hit','68'],['Equipment','Prepared inside']],mechanics:['Complete a consistent prep route','Count attacks and switch prayer','Switch offensive style','Avoid tornadoes and floor tiles'],setups:[S('Learner / Budget','All equipment is created inside; practise Tier 2 preparation.',[]),S('Recommended / Consistent','Tier 2 armour and two perfected weapons.',['Two perfected weapons','Tier 2 armour','Prepared food and potions']),S('Efficient / Upgraded','Lower armour tiers after mechanics are reliable.',['Two perfected weapons','Chosen armour tier','Optimised food']),S('Best in Slot (BIS)','No bank-gear BIS applies because equipment is made inside.',[])],extras:['Song of the Elves','Resources gathered inside']},
    {name:'Tombs of Amascut (Entry)',image:'https://oldschool.runescape.wiki/images/Tombs_of_Amascut.png',source:'https://oldschool.runescape.wiki/w/Tombs_of_Amascut/Strategies',facts:[['Encounter','Four paths plus Wardens'],['Scaling','Invocation and team dependent'],['Styles','All combat styles'],['HP / max hit','Context dependent'],['Entry mode','0–149 raid level']],mechanics:['Complete each path mechanic','Use all three combat styles','Manage supplies across rooms','Learn Wardens phases'],setups:[S('Learner / Budget','Low-cost three-style switches.',['Budget melee setup','Budget ranged setup','Budget magic setup']),S('Recommended / Consistent','Balanced three-style equipment.',['Recommended melee setup','Recommended ranged setup','Recommended magic setup']),S('Efficient / Upgraded','Higher-ranked room-specific choices.',['Upgraded melee setup','Upgraded ranged setup','Upgraded magic setup']),S('Best in Slot (BIS)','Raid BIS is room-, role-, invocation-, and team-dependent.',['Room-specific first-ranked choices'])],extras:['Beneath Cursed Sands','Combat potions','Prayer restoration','Food']}
  ];
}
