const V289_VERSION='V2.89';
const V289_EFFECT_RULES={
  'dragon hunter lance':{source:'https://oldschool.runescape.wiki/w/Dragon_hunter_lance',targets:['dragon'],accuracy:1.2,damage:1.2,label:'+20% accuracy and damage against dragons'},
  'arclight':{source:'https://oldschool.runescape.wiki/w/Arclight',targets:['demon'],accuracy:1.7,damage:1.7,label:'+70% accuracy and damage against demons'},
  'emberlight':{source:'https://oldschool.runescape.wiki/w/Emberlight',targets:['demon'],accuracy:1.7,damage:1.7,label:'+70% accuracy and damage against demons'},
  'silverlight':{source:'https://oldschool.runescape.wiki/w/Silverlight',targets:['demon'],damage:1.6,label:'+60% maximum hit against demons'},
  'darklight':{source:'https://oldschool.runescape.wiki/w/Darklight',targets:['demon'],damage:1.6,label:'+60% maximum hit against demons'},
  'keris':{source:'https://oldschool.runescape.wiki/w/Keris',targets:['kalphite','scarab'],damage:1.33,expected:1+2/51,label:'+33% base damage and 1/51 triple-damage roll'},
  'keris partisan':{source:'https://oldschool.runescape.wiki/w/Keris_partisan',targets:['kalphite','scarab'],damage:1.33,expected:1+2/51,label:'+33% base damage and 1/51 triple-damage roll'},
  'bone mace':{source:'https://oldschool.runescape.wiki/w/Bone_mace',targets:['rat'],flatMax:10,label:'+10 maximum hit against rats'},
  'colossal blade':{source:'https://oldschool.runescape.wiki/w/Colossal_blade',flatSize:2,label:'+2 maximum hit per target size, capped at size 5'},
  "osmumten's fang":{source:'https://oldschool.runescape.wiki/w/Osmumten%27s_fang',accuracyReroll:true,label:'Rolls accuracy twice and uses the better result'}
};
function v289Attrs_(monster){return (String(monster&&monster.Attributes||'')+' '+String(monster&&monster.Name||monster&&monster.Page||'')).toLowerCase()}
function v289Applies_(rule,monster){if(!rule.targets)return true;const attrs=v289Attrs_(monster);return rule.targets.some(x=>attrs.indexOf(x)>=0)}
function v289ApplyWeaponEffect_(weapon,monster,base){const rule=V289_EFFECT_RULES[v281tKey_(weapon&&weapon.name)];if(!rule||!v289Applies_(rule,monster))return {accuracy:base.accuracy,maxHit:base.maxHit,expectedMultiplier:1,effects:[]};let accuracy=base.accuracy,maxHit=base.maxHit,expected=1;if(rule.accuracy)accuracy=Math.min(1,accuracy*rule.accuracy);if(rule.accuracyReroll)accuracy=1-Math.pow(1-accuracy,2);if(rule.damage)maxHit=Math.floor(maxHit*rule.damage);if(rule.flatMax)maxHit+=rule.flatMax;if(rule.flatSize)maxHit+=rule.flatSize*Math.min(5,Math.max(1,v281tNum_(monster.Size)));if(rule.expected)expected*=rule.expected;return {accuracy:accuracy,maxHit:maxHit,expectedMultiplier:expected,effects:[{item:weapon.name,label:rule.label,source:rule.source}]}}
function runV289EffectRegressions(){const base={accuracy:.5,maxHit:20},dragon={Name:'Dragon',Attributes:'dragon',Size:3},demon={Name:'Demon',Attributes:'demon',Size:2},rat={Name:'Giant rat',Attributes:'rat',Size:1},tests=[{name:'Dragon target',pass:v289ApplyWeaponEffect_({name:'Dragon hunter lance'},dragon,base).maxHit===24},{name:'Dragon gate',pass:v289ApplyWeaponEffect_({name:'Dragon hunter lance'},demon,base).maxHit===20},{name:'Arclight demon',pass:v289ApplyWeaponEffect_({name:'Arclight'},demon,base).maxHit===34},{name:'Bone mace rat',pass:v289ApplyWeaponEffect_({name:'Bone mace'},rat,base).maxHit===30},{name:'Fang reroll',pass:Math.abs(v289ApplyWeaponEffect_({name:"Osmumten's fang"},dragon,base).accuracy-.75)<1e-9},{name:'Size scaling',pass:v289ApplyWeaponEffect_({name:'Colossal blade'},dragon,base).maxHit===26}];return {ok:tests.every(x=>x.pass),version:V289_VERSION,tests:tests,failed:tests.filter(x=>!x.pass)}}
