const V287_VERSION='V2.87';
const V287_SHEET='Game Data - Equipment Knowledge';
const V287_CURSOR='V287_EQUIPMENT_CURSOR';
const V287_BATCH_SIZE=35;
const V287_REQUIREMENT_KEYS={att:'Attack',attack:'Attack',str:'Strength',strength:'Strength',def:'Defence',defence:'Defence',range:'Ranged',ranged:'Ranged',magic:'Magic',prayer:'Prayer',hp:'Hitpoints',hitpoints:'Hitpoints'};

function v287Clean_(v){return String(v==null?'':v).replace(/<!--[^]*?-->/g,'').replace(/\{\{[^{}]*\}\}/g,'').replace(/\[\[[^\]|]*\|?([^\]]*)\]\]/g,'$1').replace(/<[^>]+>/g,'').trim()}
function v287RequirementMap_(wikitext){const out={};let inBonuses=false;String(wikitext||'').split(/\r?\n/).slice(0,220).forEach(line=>{if(/^\s*\{\{\s*Infobox Bonuses\b/i.test(line)){inBonuses=true;return}if(inBonuses&&/^\s*\}\}\s*$/.test(line)){inBonuses=false;return}if(inBonuses)return;const m=line.match(/^\|\s*([a-z_]+)\s*=\s*(.+?)\s*$/i);if(!m)return;const skill=V287_REQUIREMENT_KEYS[m[1].toLowerCase()];if(!skill)return;const n=Number(v287Clean_(m[2]).match(/\d+/)?.[0]);if(Number.isFinite(n)&&n>0)out[skill]=n});return out}
function v287EffectEvidence_(wikitext){const text=String(wikitext||''),markers=[];if(/==+\s*Passive effect\s*==+/i.test(text))markers.push('PASSIVE_SECTION');if(/\bset effect\b/i.test(text))markers.push('SET_EFFECT_TEXT');if(/\bspecial effect\b/i.test(text))markers.push('SPECIAL_EFFECT_TEXT');if(/\bdegrad(?:e|es|able|ation)\b/i.test(text))markers.push('DEGRADABLE_TEXT');if(/\bcharges?\b/i.test(text))markers.push('CHARGE_TEXT');return markers}
function v287RevisionBatch_(titles){const out={},size=10;if(!titles.length)return out;for(let start=0;start<titles.length;start+=size){const batch=titles.slice(start,start+size),url=V285_WIKI_API+'?action=query&format=json&formatversion=2&redirects=1&prop=revisions&rvprop=ids|timestamp|content&rvslots=main&titles='+encodeURIComponent(batch.join('|')),data=v285FetchJson_(url),normalized={};(data.query&&data.query.redirects||[]).forEach(r=>normalized[v281tKey_(r.to)]=v281tKey_(r.from));(data.query&&data.query.pages||[]).forEach(page=>{const rev=page.revisions&&page.revisions[0]||{},slot=rev.slots&&rev.slots.main||{},canonical=v281tKey_(page.title),key=normalized[canonical]||canonical,record={title:page.title||'',revision:rev.revid||'',timestamp:rev.timestamp||'',text:slot.content||''};out[key]=record;out[canonical]=record})}return out}
function v287EquipmentNames_(){const ss=SpreadsheetApp.openById(V1_TRACKER_ID),sh=ss.getSheetByName(V285_SHEETS.equipment);if(!sh||sh.getLastRow()<2)return[];const rows=v281tRows_(sh),seen={},all=[];rows.forEach(r=>{const name=String(r.Name||r.Page||'').trim();if(name&&!seen[name.toLowerCase()]){seen[name.toLowerCase()]=true;all.push(name)}});all.sort((a,b)=>a.localeCompare(b));const priority=[],queued={};Object.keys(V281T_LOADOUTS||{}).forEach(tier=>{(V281T_LOADOUTS[tier].weaponChoices||[]).concat(V281T_LOADOUTS[tier].items||[]).forEach(x=>{const key=String(x.name||'').toLowerCase();if(key&&seen[key]&&!queued[key]){queued[key]=true;priority.push(x.name)}})});return priority.concat(all.filter(name=>!queued[name.toLowerCase()]))}
function v287Upsert_(records){const headers=['Name','Requirements JSON','Effect Status','Effect Evidence','Wiki Revision','Wiki Timestamp','Source','Last Checked','Confidence'],sh=v285Sheet_(V287_SHEET,headers),existing={};if(sh.getLastRow()>1)sh.getRange(2,1,sh.getLastRow()-1,headers.length).getValues().forEach((r,i)=>existing[String(r[0]).toLowerCase()]=i+2);records.forEach(rec=>{const row=[rec.name,JSON.stringify(rec.requirements),rec.effectStatus,rec.evidence.join(' | '),rec.revision,rec.timestamp,rec.source,new Date(),rec.confidence],at=existing[rec.name.toLowerCase()];if(at)sh.getRange(at,1,1,headers.length).setValues([row]);else{sh.appendRow(row);existing[rec.name.toLowerCase()]=sh.getLastRow()}});return records.length}
function refreshV287EquipmentKnowledgeBatch(){const names=v287EquipmentNames_();if(!names.length)throw new Error('Equipment database is empty.');const props=PropertiesService.getScriptProperties(),cursor=Math.max(0,Number(props.getProperty(V287_CURSOR)||0)),batch=names.slice(cursor,cursor+V287_BATCH_SIZE),pages=v287RevisionBatch_(batch),records=batch.map(name=>{const page=pages[name.toLowerCase()]||{},requirements=v287RequirementMap_(page.text),evidence=v287EffectEvidence_(page.text),effectStatus=evidence.length?'REVIEW_REQUIRED':'NO_EFFECT_EVIDENCE';return {name:name,requirements:requirements,effectStatus:effectStatus,evidence:evidence,revision:page.revision||'',timestamp:page.timestamp||'',source:'https://oldschool.runescape.wiki/w/'+encodeURIComponent(String(page.title||name).replace(/ /g,'_')),confidence:page.revision?(evidence.length?'WIKI_REVISION_REVIEW':'WIKI_REVISION_PARSED'):'BLOCKED'}});v287Upsert_(records);const next=cursor+batch.length>=names.length?0:cursor+batch.length;props.setProperty(V287_CURSOR,String(next));props.setProperty('V287_LAST_BATCH',new Date().toISOString());if(next===0)props.setProperty('V287_CYCLE_COMPLETE_AT',new Date().toISOString());return {ok:true,version:V287_VERSION,processed:batch.length,total:names.length,nextCursor:next,cycleComplete:next===0,reviewRequired:records.filter(x=>x.effectStatus==='REVIEW_REQUIRED').length}}
function installV287EquipmentKnowledge(){const existing=ScriptApp.getProjectTriggers();if(!existing.some(t=>t.getHandlerFunction()==='refreshV287EquipmentKnowledgeBatch'))ScriptApp.newTrigger('refreshV287EquipmentKnowledgeBatch').timeBased().everyMinutes(15).create();ScriptApp.newTrigger('refreshV287EquipmentKnowledgeBatch').timeBased().after(60000).create();PropertiesService.getScriptProperties().setProperty('V287_INSTALLED',new Date().toISOString());return {ok:true,version:V287_VERSION}}
function ensureV287EquipmentKnowledge_(){const props=PropertiesService.getScriptProperties();if(props.getProperty('V287_INSTALLED'))return;const lock=LockService.getScriptLock();if(!lock.tryLock(500))return;try{if(!props.getProperty('V287_INSTALLED'))installV287EquipmentKnowledge()}finally{lock.releaseLock()}}
function getV287EquipmentKnowledgeStatus(){const ss=SpreadsheetApp.openById(V1_TRACKER_ID),sh=ss.getSheetByName(V287_SHEET),rows=sh&&sh.getLastRow()>1?v281tRows_(sh):[],counts={verified:0,review:0,blocked:0};rows.forEach(r=>{if(r.Confidence==='BLOCKED')counts.blocked++;else if(r['Effect Status']==='REVIEW_REQUIRED')counts.review++;else counts.verified++});return {version:V287_VERSION,records:rows.length,counts:counts,nextCursor:Number(PropertiesService.getScriptProperties().getProperty(V287_CURSOR)||0),lastBatch:PropertiesService.getScriptProperties().getProperty('V287_LAST_BATCH')||''}}
function v291AdvisorCandidateNames_(){const ss=SpreadsheetApp.openById(V1_TRACKER_ID),rows=v281tRows_(ss.getSheetByName(V285_SHEETS.equipment)),priority=['Dragon dagger','Dragon longsword','Dragon mace','Dragon battleaxe','Sulphur blades','Granite hammer','Brine sabre','Rune scimitar'],seen={},out=[];Object.keys(V281T_LOADOUTS).forEach(tier=>(V281T_LOADOUTS[tier].weaponChoices||[]).concat(V281T_LOADOUTS[tier].items||[]).forEach(x=>priority.push(x.name)));rows.map(r=>({name:String(r.Name||r.Page||''),score:Math.max(v281tNum_(r['Stab Attack']),v281tNum_(r['Slash Attack']),v281tNum_(r['Crush Attack']))+v281tNum_(r['Melee Strength'])-Math.max(0,v281tNum_(r['Attack Speed'])-4)*12})).sort((a,b)=>b.score-a.score).slice(0,35).forEach(x=>priority.push(x.name));priority.forEach(name=>{const key=v281tKey_(name);if(key&&!seen[key]&&out.length<50){seen[key]=true;out.push(name)}});return out}
function refreshV291AdvisorKnowledge(){const names=v291AdvisorCandidateNames_(),pages=v287RevisionBatch_(names),records=names.map(name=>{const page=pages[v281tKey_(name)]||{},requirements=v287RequirementMap_(page.text),evidence=v287EffectEvidence_(page.text);return {name:name,requirements:requirements,effectStatus:evidence.length?'REVIEW_REQUIRED':'NO_EFFECT_EVIDENCE',evidence:evidence,revision:page.revision||'',timestamp:page.timestamp||'',source:'https://oldschool.runescape.wiki/w/'+encodeURIComponent(String(page.title||name).replace(/ /g,'_')),confidence:page.revision?(evidence.length?'WIKI_REVISION_REVIEW':'WIKI_REVISION_PARSED'):'BLOCKED'}});v287Upsert_(records);PropertiesService.getScriptProperties().setProperty('V291_ADVISOR_REFRESHED_AT',new Date().toISOString());return {ok:true,processed:records.length}}
function getV291TrainingRecommendations(skill,objective){refreshV291AdvisorKnowledge();if(typeof refreshV292EquipmentPricing==='function')refreshV292EquipmentPricing();return getV281TrainingRecommendations(skill,objective)}
