const V285_USER_AGENT='SensumOSRSDashboard/2.85 (background game-data platform)';
const V285_WIKI_API='https://oldschool.runescape.wiki/api.php';
const V285_PRICE_API='https://prices.runescape.wiki/api/v1/osrs';
const V285_SHEETS={items:'Game Data - Items',recipes:'Game Data - Recipes',equipment:'Game Data - Equipment',monsters:'Game Data - Monsters',audit:'Game Data - Sync Audit'};

function v285FetchJson_(url){const response=UrlFetchApp.fetch(url,{headers:{'User-Agent':V285_USER_AGENT},muteHttpExceptions:true});const code=response.getResponseCode();if(code<200||code>=300)throw new Error('Data source returned HTTP '+code+' for '+url.split('?')[0]);return JSON.parse(response.getContentText())}
function v285Sheet_(name,headers){const ss=SpreadsheetApp.openById(V1_TRACKER_ID);let sh=ss.getSheetByName(name);if(!sh)sh=ss.insertSheet(name);if(headers&&headers.length){if(sh.getMaxColumns()<headers.length)sh.insertColumnsAfter(sh.getMaxColumns(),headers.length-sh.getMaxColumns());sh.getRange(1,1,1,headers.length).setValues([headers]);sh.setFrozenRows(1)}return sh}
function v285Replace_(name,headers,rows,minRows){if(rows.length<Number(minRows||1))throw new Error(name+' staged only '+rows.length+' records; verified data was preserved.');const sh=v285Sheet_(name,headers),width=headers.length;if(sh.getLastRow()>1)sh.getRange(2,1,sh.getLastRow()-1,Math.max(width,sh.getLastColumn())).clearContent();if(rows.length)sh.getRange(2,1,rows.length,width).setValues(rows);sh.getRange(1,1,1,width).setFontWeight('bold');return rows.length}
function v285Audit_(domain,status,count,message,source){const headers=['Checked At','Domain','Status','Records','Message','Source'];const sh=v285Sheet_(V285_SHEETS.audit,headers);sh.appendRow([new Date(),domain,status,Number(count||0),String(message||''),String(source||'')]);const excess=Math.max(0,sh.getLastRow()-501);if(excess)sh.deleteRows(2,excess)}
function v285Text_(value){if(value==null)return'';if(Array.isArray(value))return value.map(v285Text_).filter(Boolean).join(' | ');if(typeof value==='object')return String(value.fulltext||value.raw||value.value||JSON.stringify(value));return String(value)}
function v285Number_(value){const n=Number(String(v285Text_(value)).replace(/,/g,'').match(/-?\d+(?:\.\d+)?/)?.[0]);return Number.isFinite(n)?n:''}
function v285Print_(result,name){return result&&result.printouts?result.printouts[name]:''}
function v285AskAll_(condition,properties,limit){const out=[],pageSize=500,max=Math.min(10000,Number(limit||10000));for(let offset=0;offset<max;offset+=pageSize){const query=[condition].concat(properties.map(x=>'?'+x)).concat(['limit='+pageSize,'offset='+offset]).join('|'),url=V285_WIKI_API+'?action=ask&format=json&formatversion=2&query='+encodeURIComponent(query),data=v285FetchJson_(url),results=data&&data.query&&data.query.results||{},batch=Object.keys(results).map(k=>results[k]);out.push.apply(out,batch);if(batch.length<pageSize)break}return out}
function v285Revision_(title){return 'https://oldschool.runescape.wiki/w/'+encodeURIComponent(String(title||'').replace(/ /g,'_'))}

function refreshV285ItemDatabase(){const source=V285_PRICE_API+'/mapping';try{const mapping=v285FetchJson_(source),latest=(v285FetchJson_(V285_PRICE_API+'/latest').data||{}),checked=new Date(),headers=['Item ID','Name','Members','Examine','Store Value','Low Alch','High Alch','GE Buy Limit','Icon','Instant Buy','Instant Sell','Buy Time','Sell Time','Source','Last Checked','Confidence'],rows=mapping.map(x=>{const p=latest[String(x.id)]||{};return [Number(x.id),String(x.name||''),!!x.members,String(x.examine||''),Number(x.value||0),Number(x.lowalch||0),Number(x.highalch||0),Number(x.limit||0),String(x.icon||''),Number(p.high||0),Number(p.low||0),p.highTime?new Date(p.highTime*1000):'',p.lowTime?new Date(p.lowTime*1000):'',source,checked,'WIKI_MAPPING+LIVE_GE']});const count=v285Replace_(V285_SHEETS.items,headers,rows,3000);v285Audit_('items','OK',count,'Mapping and latest GE prices refreshed.',source);return {ok:true,domain:'items',count:count}}catch(e){v285Audit_('items','ERROR',0,e.message,source);throw e}}

function v285LegacyRecipeDatabase_(){return null}

function v285LegacyEquipmentDatabase_(){return null}

function v285LegacyMonsterDatabase_(){return null}

function v285BucketAll_(bucketName,fields,limit){const out=[],pageSize=1000,max=Math.min(20000,Number(limit||20000));for(let offset=0;offset<max;offset+=pageSize){const args=fields.map(x=>"'"+x+"'").join(','),query="bucket('"+bucketName+"').select("+args+").orderBy('page_name_sub','asc').limit("+pageSize+").offset("+offset+").run()",url=V285_WIKI_API+'?action=bucket&format=json&formatversion=2&query='+encodeURIComponent(query),data=v285FetchJson_(url);if(data.error)throw new Error('OSRS Wiki Bucket error: '+v285Text_(data.error));const batch=Array.isArray(data.bucket)?data.bucket:[];out.push.apply(out,batch);if(batch.length<pageSize)break}return out}
function v285Json_(raw){try{return JSON.parse(String(raw||''))}catch(e){return {}}}

function refreshV285RecipeDatabase(){const source='OSRS Wiki Bucket API · recipe.production_json';try{const results=v285BucketAll_('recipe',['page_name','page_name_sub','production_json','uses_material','uses_tool','uses_facility','uses_skill','is_members_only'],20000),checked=new Date(),headers=['Recipe Key','Page','Production JSON','Materials','Tools','Facilities','Skills','Members','Ticks','Output','Output Quantity','XP JSON','Requirements JSON','Source','Last Checked','Confidence'],rows=results.map((r,i)=>{const p=v285Json_(r.production_json),output=p.output||{},skills=Array.isArray(p.skills)?p.skills:[],requirements=skills.map(s=>({skill:s.name,level:s.level,boostable:s.boostable}));return [v281QuestScopeKey_(r.page_name_sub||r.page_name)+'-'+i,r.page_name_sub||r.page_name,String(r.production_json||''),JSON.stringify(p.materials||r.uses_material||[]),JSON.stringify(p.tools||r.uses_tool||[]),JSON.stringify(p.facilities||r.uses_facility||[]),JSON.stringify(skills),r.is_members_only===true,v285Number_(p.ticks),v285Text_(output.name||output),v285Number_(output.quantity),JSON.stringify(skills.map(s=>({skill:s.name,xp:s.experience}))),JSON.stringify(requirements),v285Revision_(r.page_name),checked,r.production_json?'WIKI_BUCKET_STRUCTURED':'REVIEW']});const count=v285Replace_(V285_SHEETS.recipes,headers,rows,100);v285Audit_('recipes','OK',count,'Current Bucket recipe records refreshed.',source);return {ok:true,domain:'recipes',count:count}}catch(e){v285Audit_('recipes','ERROR',0,e.message,source);throw e}}

function refreshV285EquipmentDatabase(){const source='OSRS Wiki Bucket API · infobox_bonuses + infobox_item';try{const fields=['page_name','page_name_sub','equipment_slot','combat_style','weapon_attack_speed','weapon_attack_range','stab_attack_bonus','slash_attack_bonus','crush_attack_bonus','magic_attack_bonus','range_attack_bonus','strength_bonus','ranged_strength_bonus','magic_damage_bonus','prayer_bonus','stab_defence_bonus','slash_defence_bonus','crush_defence_bonus','magic_defence_bonus','range_defence_bonus'],results=v285BucketAll_('infobox_bonuses',fields,20000),items=v285BucketAll_('infobox_item',['page_name','page_name_sub','item_id','item_name','is_members_only'],20000),itemMap={};items.forEach(x=>itemMap[String(x.page_name_sub||x.page_name).toLowerCase()]=x);const checked=new Date(),headers=['Record Key','Page','Item ID','Name','Members','Slot','Combat Style','Attack Speed','Attack Range','Attack Bonus','Stab Attack','Slash Attack','Crush Attack','Magic Attack','Ranged Attack','Melee Strength','Ranged Strength','Magic Damage','Prayer','Stab Defence','Slash Defence','Crush Defence','Magic Defence','Ranged Defence','Light Defence','Standard Defence','Heavy Defence','Flat Armour','Skill Requirements','Quest Requirements','Source','Last Checked','Confidence'],rows=results.map((r,i)=>{const key=String(r.page_name_sub||r.page_name),item=itemMap[key.toLowerCase()]||{};return [v281QuestScopeKey_(key)+'-'+i,r.page_name,v285Text_(item.item_id),item.item_name||key,item.is_members_only===true,r.equipment_slot||'',r.combat_style||'',v285Number_(r.weapon_attack_speed),v285Number_(r.weapon_attack_range),'',v285Number_(r.stab_attack_bonus),v285Number_(r.slash_attack_bonus),v285Number_(r.crush_attack_bonus),v285Number_(r.magic_attack_bonus),v285Number_(r.range_attack_bonus),v285Number_(r.strength_bonus),v285Number_(r.ranged_strength_bonus),v285Number_(r.magic_damage_bonus),v285Number_(r.prayer_bonus),v285Number_(r.stab_defence_bonus),v285Number_(r.slash_defence_bonus),v285Number_(r.crush_defence_bonus),v285Number_(r.magic_defence_bonus),v285Number_(r.range_defence_bonus),'','','','','','',v285Revision_(r.page_name),checked,'WIKI_BUCKET_STRUCTURED']});const count=v285Replace_(V285_SHEETS.equipment,headers,rows,100);v285Audit_('equipment','OK',count,'Current equipment and weapon records refreshed.',source);return {ok:true,domain:'equipment',count:count}}catch(e){v285Audit_('equipment','ERROR',0,e.message,source);throw e}}

function refreshV285MonsterDatabase(){const source='OSRS Wiki Bucket API · infobox_monster';try{const fields=['page_name','page_name_sub','id','name','is_members_only','combat_level','hitpoints','attack_level','strength_level','defence_level','ranged_level','magic_level','stab_defence_bonus','slash_defence_bonus','crush_defence_bonus','magic_defence_bonus','range_defence_bonus','light_range_defence_bonus','standard_range_defence_bonus','heavy_range_defence_bonus','flat_armour','elemental_weakness','elemental_weakness_percent','slayer_level','slayer_experience','experience_bonus','attack_style','attack_speed','max_hit','poisonous','poison_resistance','venom_resistance','attribute','size','uses_skill','slayer_category','assigned_by'],results=v285BucketAll_('infobox_monster',fields,20000),checked=new Date(),headers=['Record Key','Page','NPC ID','Name','Members','Combat Level','Hitpoints','Attack','Strength','Defence','Ranged','Magic','Stab Defence','Slash Defence','Crush Defence','Magic Defence','Ranged Defence','Light Defence','Standard Defence','Heavy Defence','Flat Armour','Elemental Weakness','Weakness Percent','Slayer Level','Slayer XP','Combat XP Bonus','Attack Styles','Attack Speed','Max Hit','Poisonous','Poison Immune','Venom Immune','Attributes','Size','Respawn Ticks','Locations','Quest Requirements','Slayer Categories','Assigned By','Source','Last Checked','Confidence'],rows=results.map((r,i)=>[v281QuestScopeKey_(r.page_name_sub||r.page_name)+'-'+i,r.page_name,v285Text_(r.id),r.name||r.page_name_sub||r.page_name,r.is_members_only===true,v285Number_(r.combat_level),v285Number_(r.hitpoints),v285Number_(r.attack_level),v285Number_(r.strength_level),v285Number_(r.defence_level),v285Number_(r.ranged_level),v285Number_(r.magic_level),v285Number_(r.stab_defence_bonus),v285Number_(r.slash_defence_bonus),v285Number_(r.crush_defence_bonus),v285Number_(r.magic_defence_bonus),v285Number_(r.range_defence_bonus),v285Number_(r.light_range_defence_bonus),v285Number_(r.standard_range_defence_bonus),v285Number_(r.heavy_range_defence_bonus),v285Number_(r.flat_armour),r.elemental_weakness||'',v285Number_(r.elemental_weakness_percent),v285Number_(r.slayer_level),v285Number_(r.slayer_experience),v285Number_(r.experience_bonus),v285Text_(r.attack_style),v285Number_(r.attack_speed),v285Text_(r.max_hit),r.poisonous||'',r.poison_resistance||'',r.venom_resistance||'',v285Text_(r.attribute),v285Number_(r.size),'','',v285Text_(r.uses_skill),v285Text_(r.slayer_category),v285Text_(r.assigned_by),v285Revision_(r.page_name),checked,'WIKI_BUCKET_STRUCTURED']);const count=v285Replace_(V285_SHEETS.monsters,headers,rows,100);v285Audit_('monsters','OK',count,'Current monster combat records refreshed.',source);return {ok:true,domain:'monsters',count:count}}catch(e){v285Audit_('monsters','ERROR',0,e.message,source);throw e}}

function installV285GameDataPlatform(){Object.keys(V285_SHEETS).forEach(k=>v285Sheet_(V285_SHEETS[k]));const handlers=['refreshV285ItemDatabase','refreshV285RecipeDatabase','refreshV285EquipmentDatabase','refreshV285MonsterDatabase'],existing=ScriptApp.getProjectTriggers();handlers.forEach((handler,index)=>{if(!existing.some(t=>t.getHandlerFunction()===handler))ScriptApp.newTrigger(handler).timeBased().everyDays(1).atHour((index+1)%24).create();ScriptApp.newTrigger(handler).timeBased().after((index+1)*60000).create()});if(!existing.some(t=>t.getHandlerFunction()==='refreshV285ItemDatabaseHourly'))ScriptApp.newTrigger('refreshV285ItemDatabaseHourly').timeBased().everyHours(1).create();PropertiesService.getScriptProperties().setProperty('V285_PLATFORM_INSTALLED_AT',new Date().toISOString());return {ok:true,handlers:handlers.concat(['refreshV285ItemDatabaseHourly'])}}
function ensureV285GameDataPlatform_(){const props=PropertiesService.getScriptProperties(),installed=props.getProperty('V285_PLATFORM_INSTALLED_AT');if(installed&&props.getProperty('V285_BUCKET_MIGRATION_QUEUED'))return;const lock=LockService.getScriptLock();if(!lock.tryLock(1000))return;try{if(!props.getProperty('V285_PLATFORM_INSTALLED_AT'))installV285GameDataPlatform();if(!props.getProperty('V285_BUCKET_MIGRATION_QUEUED')){['refreshV285RecipeDatabase','refreshV285EquipmentDatabase','refreshV285MonsterDatabase'].forEach((handler,index)=>ScriptApp.newTrigger(handler).timeBased().after((index+1)*60000).create());props.setProperty('V285_BUCKET_MIGRATION_QUEUED',new Date().toISOString())}}finally{lock.releaseLock()}}
function refreshV285ItemDatabaseHourly(){return refreshV285ItemDatabase()}
function getV285GameDataStatus(){const ss=SpreadsheetApp.openById(V1_TRACKER_ID),status={installedAt:PropertiesService.getScriptProperties().getProperty('V285_PLATFORM_INSTALLED_AT')||'',domains:{},audit:[]};Object.keys(V285_SHEETS).filter(k=>k!=='audit').forEach(k=>{const sh=ss.getSheetByName(V285_SHEETS[k]);status.domains[k]={records:sh?Math.max(0,sh.getLastRow()-1):0,lastChecked:sh&&sh.getLastRow()>1?sh.getRange(2,sh.getLastColumn()-1).getDisplayValue():''}});const audit=ss.getSheetByName(V285_SHEETS.audit);if(audit&&audit.getLastRow()>1){const start=Math.max(2,audit.getLastRow()-11);status.audit=audit.getRange(start,1,audit.getLastRow()-start+1,6).getDisplayValues().map(r=>({checkedAt:r[0],domain:r[1],status:r[2],records:Number(r[3]||0),message:r[4],source:r[5]})).reverse()}return status}
