const V290_VERSION='V2.90';
const V290_SET_RULES={
  obsidian:{source:'https://oldschool.runescape.wiki/w/Obsidian_equipment',required:['obsidian helmet','obsidian platebody','obsidian platelegs'],weapon:/^(toktz-|tzhaar-ket-|obsidian)/i,accuracy:1.10,strength:1.10,label:'Obsidian armour · +10% melee accuracy and Strength with an obsidian weapon'},
  void_melee:{source:'https://oldschool.runescape.wiki/w/Void_Knight_equipment',required:['void melee helm','void knight top','void knight robe','void knight gloves'],accuracy:1.10,strength:1.10,label:'Void melee · +10% melee accuracy and Strength'},
  inquisitor:{source:'https://oldschool.runescape.wiki/w/Inquisitor%27s_armour',members:['inquisitor\'s great helm','inquisitor\'s hauberk','inquisitor\'s plateskirt'],style:'crush',pieceAccuracy:1.005,pieceDamage:1.005,fullAccuracy:1.01,fullDamage:1.01,macePieceAccuracy:1.025,macePieceDamage:1.025,label:'Inquisitor crush accuracy and damage'}
};
const V290_CONTEXT_BLOCKED={
  "dharok's":'Requires current Hitpoints and full-set state.',
  'slayer helmet':'Requires an active Slayer assignment.',
  'black mask':'Requires an active Slayer assignment.',
  'blood moon':'Requires dual-hit proc and attack-delay state modeling.',
  'salve amulet':'Requires undead classification and salve/Slayer exclusivity handling.'
};
function v290Names_(weapon,items){return [weapon].concat(items||[]).map(x=>v281tKey_(x&&x.name||x))}
function v290Signature_(item){const n=v281tKey_(item&&item.name);const tags=[];Object.keys(V290_SET_RULES).forEach(key=>{const r=V290_SET_RULES[key],members=(r.required||r.members||[]).map(v281tKey_);if(members.indexOf(n)>=0)tags.push(key+':'+n)});return tags.join(',')}
function v290EffectSafe_(name){const n=v281tKey_(name);if(Object.keys(V290_CONTEXT_BLOCKED).some(key=>n.indexOf(key)>=0))return false;return Object.keys(V290_SET_RULES).some(key=>{const r=V290_SET_RULES[key];return (r.required||r.members||[]).map(v281tKey_).indexOf(n)>=0})}
function v290SetModifiers_(weapon,items,style){const names=v290Names_(weapon,items),mods={attackLevel:1,strengthLevel:1,accuracy:1,damage:1,effects:[]};Object.keys(V290_SET_RULES).forEach(key=>{const r=V290_SET_RULES[key],required=(r.required||[]).map(v281tKey_),members=(r.members||[]).map(v281tKey_),complete=required.length&&required.every(x=>names.indexOf(x)>=0);if(key==='obsidian'&&complete&&r.weapon.test(String(weapon&&weapon.name||''))){mods.attackLevel*=r.accuracy;mods.strengthLevel*=r.strength;mods.effects.push({label:r.label,source:r.source})}else if(key==='void_melee'&&complete){mods.attackLevel*=r.accuracy;mods.strengthLevel*=r.strength;mods.effects.push({label:r.label,source:r.source})}else if(key==='inquisitor'&&style===r.style){const pieces=members.filter(x=>names.indexOf(x)>=0).length;if(pieces){const mace=/inquisitor's mace/i.test(String(weapon&&weapon.name||'')),piece=mace?.025:.005,full=!mace&&pieces===3?.01:0;mods.accuracy*=1+pieces*piece+full;mods.damage*=1+pieces*piece+full;mods.effects.push({label:r.label+' · '+pieces+'/3 pieces',source:r.source})}}});return mods}
function runV290SetRegressions(){const obs=[{name:'Obsidian helmet'},{name:'Obsidian platebody'},{name:'Obsidian platelegs'}],partial=obs.slice(0,2),full=v290SetModifiers_({name:'Toktz-xil-ak'},obs,'slash'),incomplete=v290SetModifiers_({name:'Toktz-xil-ak'},partial,'slash'),wrongWeapon=v290SetModifiers_({name:'Rune scimitar'},obs,'slash'),inq=v290SetModifiers_({name:"Inquisitor's mace"},[{name:"Inquisitor's great helm"},{name:"Inquisitor's hauberk"},{name:"Inquisitor's plateskirt"}],'crush'),tests=[{name:'Obsidian full set activates',pass:full.attackLevel===1.1&&full.strengthLevel===1.1},{name:'Incomplete obsidian does not activate',pass:incomplete.attackLevel===1},{name:'Wrong weapon blocks obsidian bonus',pass:wrongWeapon.attackLevel===1},{name:'Inquisitor mace amplifies each piece',pass:inq.accuracy>1.07},{name:'Dharok remains context blocked',pass:!v290EffectSafe_("Dharok's platebody")}];return {ok:tests.every(x=>x.pass),version:V290_VERSION,tests:tests,failed:tests.filter(x=>!x.pass)}}
