import assert from 'node:assert/strict';
import test from 'node:test';

import {hash} from '../ingestion/lib.mjs';
import {
  ACTIVITY_REFERENCE_MEMBER_COLLECTION_IDENTITY_FACT_KIND,
  buildActivityReferenceMemberCollectionIdentityExistingSourceCountQuery,
  buildActivityReferenceMemberCollectionIdentityMaterializationSql,
  validateActivityReferenceMemberCollectionIdentityMaterializationInput,
  verifyActivityReferenceMemberCollectionIdentityReconciliation
} from '../db/activity-reference-member-collection-activity-identity-evidence-materialization-lib.mjs';

const without=(value,key)=>Object.fromEntries(Object.entries(value).filter(([name])=>name!==key));

function fixture() {
  const collectionSource={candidateKey:'osrs-wiki-pageid:2078',pageId:2078,title:'Minigames',url:'https://oldschool.runescape.wiki/w/Minigames',revision:'999',timestamp:'2026-09-01T00:00:00Z',contentHash:'b'.repeat(64)};
  const record={
    contract:'sensum.activity-reference-collection-member-collection-activity-identity-evidence.v1',memberCandidateKey:'collection-row:2078:999:section:1:2',sourcePageId:42,resolvedTitle:'Example activity',sourceRevision:'123',sourceTimestamp:'2026-09-02T00:00:00Z',sourceUrl:'https://oldschool.runescape.wiki/w/Example_activity',sourceContentHash:'a'.repeat(64),sourceRelationshipDispositionContentHash:'c'.repeat(64),
    collectionActivityEvidence:{collectionSource,evidenceState:'revision_pinned_collection_row_and_source_role_evidence_review_only',allRowCellEvidence:[{logicalHeader:'Activity',plainText:'Example activity'}],nonEmptyRowCellEvidence:[{logicalHeader:'Activity',plainText:'Example activity'}],directRowWikilinkEvidence:[{requestedTitle:'Example activity'}]},
    collectionActivityIdentityCandidateObservations:{collectionActivityIdentityVerdict:null,linkedSubjectRelationshipVerdict:null,interpretationState:'candidate_observations_only_no_identity_or_relationship_inference',memberLinkSourceTitleAlignments:[{sourcePageId:42,sourceRevision:'123',resolvedTitle:'Example activity'}],stableSourceIdentityAlignments:[{sourcePageId:42,sourceRevision:'123',sourceContentHash:'a'.repeat(64)}],sharedMainNamespaceLinkTargets:[{normalizedTarget:'example'}],retainedSourceRelationshipClasses:['activity_component'],collectionRowCellCandidates:[{logicalHeader:'Activity',plainText:'Example activity'}]},
    sourcePageEvidence:{revisionAlignment:{fetchedContentHashMatchesRoutingRecord:true,fetchedPageIdMatchesRoutingRecord:true,fetchedRevisionMatchesRoutingRecord:true,fetchedTimestampMatchesRoutingRecord:true,fetchedTitleMatchesRoutingRecord:true,fetchedUrlMatchesRoutingRecord:true,retainedIdentityContextsPresentAndAligned:true,routingRecordMatchesPolicyRoute:true}},
    sourceRelationshipDisposition:{relationshipClass:'activity_component',state:'source_declaration_supported',evidenceKeys:['fixture']},sourceRelationshipDispositionSignals:[{matchedDeclarations:[{matchedText:'activity component'}]}],
    collectionActivityIdentityReview:{state:'unreviewed',identity:null,evidenceKeys:[]},linkedSubjectRelationshipReview:{state:'unreviewed',relationships:[],evidenceKeys:[]},repeatabilityReview:{state:'unreviewed',classification:null,evidenceKeys:[]},memberExpansionReview:{state:'unreviewed',atomicSubject:null,memberKeys:[],evidenceKeys:[]},mechanicsReview:{state:'unreviewed',evidenceKeys:[]},
    canonicalGameEntityIdentity:null,canonicalActivityIdentity:null,optimizerEligible:false,accountIndependent:true,blockers:['collection_activity_identity_evidence_requires_semantic_disposition','exact_linked_subject_collection_relationship_review_pending','canonical_game_entity_and_activity_identities_not_established','repeatability_and_member_expansion_not_reviewed','requirements_xp_timing_and_mechanics_not_structured','optimizer_eligibility_blocked'],state:'collection_activity_identity_evidence_ready_for_review'
  };
  record.contentHash=hash(record);
  const raw=JSON.stringify(record)+'\n',directory='2026-09-06T22-30-00-000Z';
  const evidenceChannels=['exact_collection_revision_and_row','all_source_located_collection_row_cells','all_direct_collection_row_wikilinks','exact_linked_source_revision','source_relationship_disposition_and_declarations','exact_cross_source_link_target_intersections'];
  const coreAudit={contract:'sensum.activity-reference-collection-member-collection-activity-identity-evidence-audit.v1',accountIndependent:true,inputCoverage:{expectedSourceRelationshipDispositionCount:1,identityEvidencePacketCount:1,duplicateInputMemberCandidateKeys:[],duplicateOutputMemberCandidateKeys:[],missingMemberCandidateKeys:[],unexpectedMemberCandidateKeys:[],contextMismatchMemberCandidateKeys:[],structurallyInvalidInputMemberCandidateKeys:[],exactInputOutputSetAndContextMatch:true},policyCoverage:{policy:'sensum.activity-reference-collection-member-collection-activity-identity-evidence-policy.v1',evidenceChannels,forbiddenPolicyPaths:[]},collectionActivityEvidenceCoverage:{collectionRevisionPinnedCount:1,linkedSourceRevisionPinnedCount:1,allRowCellEvidenceCount:1,nonEmptyRowCellEvidenceCount:1,directRowWikilinkEvidenceCount:1,sourceRelationshipDispositionSignalCount:1,matchedSourceDeclarationCount:1,relationshipClassCounts:{activity_component:1},invalidEvidenceMemberCandidateKeys:[],invalidSourceLocatorMemberCandidateKeys:[]},candidateObservationCoverage:{memberLinkSourceTitleAlignmentCount:1,stableSourceIdentityAlignmentCount:1,sharedMainNamespaceLinkTargetCount:1,collectionActivityIdentityVerdictCount:0,linkedSubjectRelationshipVerdictCount:0,invalidCandidateVerdictMemberCandidateKeys:[]},semanticPromotionCoverage:{collectionActivityIdentityReviewedCount:0,linkedSubjectRelationshipReviewedCount:0,canonicalGameEntityIdentityCount:0,canonicalActivityIdentityCount:0,repeatabilityReviewedCount:0,memberExpansionReviewedCount:0,mechanicsReviewedCount:0,optimizerEligibleCount:0,unsupportedPromotionMemberCandidateKeys:[]},accountStateFindings:[],identityEvidencePacketCoverageComplete:true,collectionActivityIdentityReviewComplete:false,linkedSubjectRelationshipReviewComplete:false,repeatabilityReviewComplete:false,requirementsXpTimingAndMechanicsComplete:false,completeActivityUniverse:false,absoluteBestGate:'blocked_incomplete_activity_universe',blockers:['collection_activity_identity_evidence_requires_semantic_disposition','exact_linked_subject_collection_relationship_review_pending','canonical_game_entity_and_activity_identities_not_established','repeatability_and_member_expansion_not_reviewed','requirements_xp_timing_and_mechanics_not_structured','independent_complete_activity_universe_not_established'],publishable:true};
  const manifest={contract:'sensum.ingestion-manifest.v1',domain:'activity-reference-collection-member-collection-activity-identity-evidence',createdAt:'2026-09-06T22:30:00Z',records:1,contentHash:hash(raw),snapshotDirectory:directory,source:{kind:'revision_pinned_collection_activity_identity_review_evidence_without_identity_or_relationship_inference',inputSnapshot:{directory:'input',contentHash:'d'.repeat(64),rejections:[]},audit:structuredClone(coreAudit)}};
  const audit={...structuredClone(coreAudit),generatedAt:'2026-09-06T22:30:01Z',policy:{id:'fixture',file:'fixture',contentHash:'e'.repeat(64)},inputSnapshot:{directory:'input',contentHash:'d'.repeat(64),rejections:[]},outputSnapshot:{directory,contentHash:manifest.contentHash}}; audit.contentHash=hash(audit);
  return {raw,manifest,audit,record};
}

function rehashInput(input) { input.record.contentHash=hash(without(input.record,'contentHash')); input.raw=JSON.stringify(input.record)+'\n'; input.manifest.contentHash=hash(input.raw); input.audit.outputSnapshot.contentHash=input.manifest.contentHash; input.audit.contentHash=hash(without(input.audit,'contentHash')); }

test('collection-identity evidence preserves linked and collection revisions with closed semantic gates',()=>{
  const input=fixture(),first=validateActivityReferenceMemberCollectionIdentityMaterializationInput(input),second=validateActivityReferenceMemberCollectionIdentityMaterializationInput(input);
  assert.equal(first.materializationHash,second.materializationHash); assert.deepEqual(first.counts,{sources:2,records:1,statements:1}); assert.deepEqual(first.skillKeys,[]); assert.equal(first.statements[0].payload.collectionActivityIdentity,null); assert.equal(first.statements[0].payload.linkedSubjectRelationshipVerdict,null); assert.equal(first.gates.collectionActivityIdentityReviewComplete,false);
});

test('collection-identity tampering, account state, promotion, count drift, and source drift fail closed',()=>{
  const tampered=fixture(); tampered.raw=tampered.raw.replace('Example activity','Changed activity'); assert.throws(()=>validateActivityReferenceMemberCollectionIdentityMaterializationInput(tampered),/snapshot_content_hash_mismatch/);
  const account=fixture(); account.record.currentBaseLevel=34; rehashInput(account); assert.throws(()=>validateActivityReferenceMemberCollectionIdentityMaterializationInput(account),/record_account_state_present/);
  const promoted=fixture(); promoted.record.collectionActivityIdentityReview={state:'reviewed',identity:'activity:example',evidenceKeys:['fixture']}; rehashInput(promoted); assert.throws(()=>validateActivityReferenceMemberCollectionIdentityMaterializationInput(promoted),/record_collection_identity_review_not_closed/);
  const countDrift=fixture(); countDrift.audit.collectionActivityEvidenceCoverage.allRowCellEvidenceCount=2; countDrift.audit.contentHash=hash(without(countDrift.audit,'contentHash')); assert.throws(()=>validateActivityReferenceMemberCollectionIdentityMaterializationInput(countDrift),/manifest_embedded_audit_mismatch|counts_do_not_reconcile/);
  const sourceDrift=fixture(); sourceDrift.record.collectionActivityIdentityCandidateObservations.stableSourceIdentityAlignments[0].sourceRevision='124'; rehashInput(sourceDrift); assert.throws(()=>validateActivityReferenceMemberCollectionIdentityMaterializationInput(sourceDrift),/cross_source_identity_alignment_missing/);
});

test('collection-identity SQL is transactional, insert-only, candidate-only, and lineage-bound',()=>{
  const model=validateActivityReferenceMemberCollectionIdentityMaterializationInput(fixture()),sql=buildActivityReferenceMemberCollectionIdentityMaterializationSql(model);
  assert.match(sql,/^\\set ON_ERROR_STOP on\nBEGIN;/); assert.match(sql,/pg_advisory_xact_lock/); assert.match(sql,new RegExp(ACTIVITY_REFERENCE_MEMBER_COLLECTION_IDENTITY_FACT_KIND)); assert.match(sql,/'candidate'/); assert.match(sql,/'review'/); assert.match(sql,/INSERT INTO activity_evidence_ingestion_lineage/); assert.match(sql,/ON CONFLICT .* DO NOTHING/); assert.match(sql,/COMMIT;\n$/); assert.doesNotMatch(sql,/\bDELETE\b|\bTRUNCATE\b|\bUPDATE\b/i); assert.match(buildActivityReferenceMemberCollectionIdentityExistingSourceCountQuery(model),/published_at=e\.published_at/);
});

test('collection-identity reconciliation rejects count, lineage, completeness, and semantic drift',()=>{
  const model=validateActivityReferenceMemberCollectionIdentityMaterializationInput(fixture()); const actual={runId:model.runId,status:'published',records:1,sources:2,statements:1,lineage:1,snapshotComplete:false,metrics:{recordHashAggregate:model.recordHashAggregate,sourceHashAggregate:model.sourceHashAggregate,statementHashAggregate:model.statementHashAggregate,materializationHash:model.materializationHash,skillCoverage:0,skillKeys:[],...model.gates}}; assert.equal(verifyActivityReferenceMemberCollectionIdentityReconciliation(model,actual),true); assert.throws(()=>verifyActivityReferenceMemberCollectionIdentityReconciliation(model,{...actual,sources:1}),/sources_count_mismatch/); assert.throws(()=>verifyActivityReferenceMemberCollectionIdentityReconciliation(model,{...actual,lineage:0}),/lineage_count_mismatch/); assert.throws(()=>verifyActivityReferenceMemberCollectionIdentityReconciliation(model,{...actual,snapshotComplete:true}),/must_not_claim_complete/); assert.throws(()=>verifyActivityReferenceMemberCollectionIdentityReconciliation(model,{...actual,metrics:{...actual.metrics,linkedSubjectRelationshipReviewComplete:true}}),/semantic_gate_weakened/);
});
