import assert from 'node:assert/strict';
import test from 'node:test';

import {hash} from '../ingestion/lib.mjs';
import {
  ACTIVITY_REFERENCE_MEMBER_UNRESOLVED_RELATIONSHIP_FACT_KIND,
  buildActivityReferenceMemberUnresolvedRelationshipExistingSourceCountQuery,
  buildActivityReferenceMemberUnresolvedRelationshipMaterializationSql,
  validateActivityReferenceMemberUnresolvedRelationshipMaterializationInput,
  verifyActivityReferenceMemberUnresolvedRelationshipReconciliation
} from '../db/activity-reference-member-unresolved-subject-relationship-evidence-materialization-lib.mjs';

const without=(value,key)=>Object.fromEntries(Object.entries(value).filter(([name])=>name!==key));

function fixture() {
  const collectionSource={candidateKey:'collection:1',contentHash:'b'.repeat(64),pageId:7,revision:'999',routingContentHash:'c'.repeat(64),sourceDispositionContentHash:'d'.repeat(64),timestamp:'2026-09-01T00:00:00Z',title:'Activities',url:'https://oldschool.runescape.wiki/w/Activities'};
  const collectionContext={collectionSource,sectionEvidence:{heading:'Activities',level:2,sourceLocator:{lineStart:10,lineEnd:10}},tableEvidence:{sourceTableOrdinal:1,memberHeader:'Activity',logicalHeaders:['Activity'],sourceLocator:{lineStart:11,lineEnd:20}},rowEvidence:{sourceRowOrdinal:1,rawText:'[[Example activity]]',cells:[{plainText:'Example activity'}],sourceLocator:{lineStart:12,lineEnd:12}},memberCellEvidence:{plainText:'Example activity',rawValue:'[[Example activity]]',sourceLocator:{lineStart:12,lineEnd:12}},memberLinks:[{occurrence:1,requestedTitle:'Example activity',requestedFragment:null,displayText:'Example activity',rawLink:'[[Example activity]]',sourceLocator:{lineStart:12,lineEnd:12}}],membershipClassification:'official_activity'};
  const sourceAuthoredLinks=[{ordinal:1,requestedTitle:'Example activity',displayText:null,namespaceClass:'main',sourceLocator:{line:2}},{ordinal:2,requestedTitle:'File:Example.png',displayText:null,namespaceClass:'non_main',sourceLocator:{line:3}}];
  const collectionMembershipEvidence={collectionSource,sectionEvidence:collectionContext.sectionEvidence,tableEvidence:collectionContext.tableEvidence,rowEvidence:collectionContext.rowEvidence,memberCellEvidence:collectionContext.memberCellEvidence,memberLinks:collectionContext.memberLinks,membershipClassification:'official_activity',evidenceState:'source_authored_collection_membership_assertion_review_only'};
  const sourcePageEvidence={sourcePageId:42,resolvedTitle:'Example activity',sourceRevision:'123',sourceTimestamp:'2026-09-02T00:00:00Z',sourceUrl:'https://oldschool.runescape.wiki/w/Example_activity',sourceContentHash:'a'.repeat(64),sourceContentBytes:100,revisionAlignment:{fetchedContentHashMatchesRoutingRecord:true,fetchedPageIdMatchesRoutingRecord:true,fetchedRevisionMatchesRoutingRecord:true,fetchedTimestampMatchesRoutingRecord:true,fetchedTitleMatchesRoutingRecord:true,fetchedUrlMatchesRoutingRecord:true,retainedIdentityContextsPresentAndAligned:true,routingRecordMatchesPolicyRoute:true},rootTemplates:[{line:1,template:'Infobox Activity',templateKey:'infobox activity'}],rootTemplateDelimiterAudit:{balanced:true,closeCount:1,finalDepth:0,openCount:1,underflow:false},directCategories:[],leadParagraphEvidence:[{ordinal:1,rawText:'Example activity can be played.',sourceLocator:{lineStart:2,lineEnd:2}}],headingEvidence:[{ordinal:1,normalizedTitle:'Example activity',rawTitle:'Example activity',line:4}],sourceAuthoredLinks,sourceLinkDelimiterAudit:{balanced:true,closeCount:2,openCount:2},evidenceState:'exact_revision_source_page_evidence_review_only'};
  const relationshipCandidateObservations={memberLabel:'Example activity',normalizedMemberLabel:'example activity',collectionRowLinkCandidates:[{candidateKey:'member:1:collection-row-link:1',requestedTitle:'Example activity',requestedFragment:null,displayText:'Example activity',rawLink:'[[Example activity]]',sourceLocator:{lineStart:12,lineEnd:12},relationshipState:'unreviewed_collection_row_link_candidate'}],sourcePageMainNamespaceLinkCandidates:[{...sourceAuthoredLinks[0],relationshipState:'unreviewed_source_page_link_candidate'}],exactMemberLabelSourceLinkMatches:[{...sourceAuthoredLinks[0],matchedMemberLabel:'Example activity',matchKind:'requested_title_exact_normalized',relationshipState:'unreviewed_exact_label_link_match_candidate'}],exactMemberLabelLeadMentions:[{...sourcePageEvidence.leadParagraphEvidence[0],matchedMemberLabel:'Example activity',matchKind:'lead_contains_exact_normalized_full_member_label',relationshipState:'unreviewed_exact_label_text_match_candidate'}],exactMemberLabelHeadingMentions:[{...sourcePageEvidence.headingEvidence[0],matchedMemberLabel:'Example activity',matchKind:'heading_contains_exact_normalized_full_member_label',relationshipState:'unreviewed_exact_label_text_match_candidate'}],relationshipVerdict:null,interpretationState:'candidate_observations_only_no_relationship_inference'};
  const record={contract:'sensum.activity-reference-collection-member-unresolved-subject-relationship-evidence.v1',memberCandidateKey:'member:1',sourceRelationshipRoutingContentHash:'e'.repeat(64),sourceSignatureDispositionContentHash:'f'.repeat(64),sourceSignatureContentHash:'1'.repeat(64),sourceRoutingContentHash:'2'.repeat(64),sourceMemberDispositionContentHash:'3'.repeat(64),sourceMemberEvidenceContentHash:'4'.repeat(64),collectionContext,memberIdentityContexts:[{pageId:42,resolvedTitle:'Example activity',observedRevision:'123'}],sourcePageId:42,resolvedTitle:'Example activity',membershipClassification:'official_activity',sourceRevision:'123',sourceTimestamp:'2026-09-02T00:00:00Z',sourceUrl:'https://oldschool.runescape.wiki/w/Example_activity',sourceContentHash:'a'.repeat(64),sourcePageSubjectDisposition:{state:'source_signature_supported',disposition:'activity_page',conflictingDispositions:[],evidenceKeys:['source:1']},routingDecision:{routeState:'queued',routeKey:'relationship-review'},sourceBlockers:['source-review'],sourceSignatureBlockers:['signature-review'],sourceDispositionBlockers:['disposition-review'],sourceRelationshipRoutingBlockers:['relationship-work-pending'],sourceSignatureJoin:{matchedRecordCount:1,exactHashIdentityRevisionAndContextMatch:true},collectionMembershipEvidence,sourcePageEvidence,relationshipCandidateObservations,collectionActivityIdentityReview:{state:'unreviewed',identity:null,evidenceKeys:[]},linkedSubjectRelationshipReview:{state:'unreviewed',relationships:[],evidenceKeys:[]},canonicalGameEntityIdentity:null,canonicalActivityIdentity:null,repeatabilityReview:{state:'unreviewed',classification:null,evidenceKeys:[]},memberExpansionReview:{state:'unreviewed',atomicSubject:null,memberKeys:[],evidenceKeys:[]},mechanicsReview:{state:'unreviewed',evidenceKeys:[]},optimizerEligible:false,accountIndependent:true,blockers:['relationship_candidate_observations_require_semantic_review','collection_activity_identity_not_established','linked_subject_relationship_review_pending','canonical_game_entity_and_activity_identities_not_established','repeatability_and_member_expansion_not_reviewed','requirements_xp_timing_and_mechanics_not_structured','optimizer_eligibility_blocked'],state:'relationship_evidence_collected_review_pending'};
  record.contentHash=hash(record);
  const raw=JSON.stringify(record)+'\n',directory='2026-09-06T23-10-00-000Z';
  const coreAudit={contract:'sensum.activity-reference-collection-member-unresolved-subject-relationship-evidence-audit.v1',accountIndependent:true,inputCoverage:{routingRecordCount:1,queuedRelationshipRouteCount:1,sourceSignatureRecordCount:1,relationshipEvidencePacketCount:1,duplicateInputMemberCandidateKeys:[],duplicateOutputMemberCandidateKeys:[],missingMemberCandidateKeys:[],unexpectedMemberCandidateKeys:[],contextMismatchMemberCandidateKeys:[],sourceSignatureJoinFailureMemberCandidateKeys:[],exactInputOutputSetContextAndSourceJoinMatch:true},evidenceCoverage:{collectionMembershipEvidenceCount:1,collectionRevisionPinnedCount:1,linkedSourceRevisionPinnedCount:1,totalLinkedSourceContentBytes:100,rootTemplateCount:1,directCategoryCount:0,leadParagraphCount:1,headingCount:1,sourceAuthoredLinkOccurrenceCount:2,mainNamespaceLinkOccurrenceCount:1,evidenceMismatchMemberCandidateKeys:[]},candidateObservationCoverage:{collectionRowLinkCandidateCount:1,sourcePageMainNamespaceLinkCandidateCount:1,exactMemberLabelSourceLinkMatchCount:1,exactMemberLabelLeadMentionCount:1,exactMemberLabelHeadingMentionCount:1,relationshipVerdictCount:0,candidateObservationMismatchMemberCandidateKeys:[],invalidCandidateStateMemberCandidateKeys:[]},policyCoverage:{policy:'sensum.activity-reference-collection-member-unresolved-subject-relationship-evidence-policy.v1',evidenceChannelCount:7,forbiddenPolicyPaths:[]},semanticPromotionCoverage:{collectionActivityIdentityReviewedCount:0,linkedSubjectRelationshipReviewedCount:0,canonicalGameEntityIdentityCount:0,canonicalActivityIdentityCount:0,repeatabilityReviewedCount:0,memberExpansionReviewedCount:0,mechanicsReviewedCount:0,optimizerEligibleCount:0,unsupportedPromotionMemberCandidateKeys:[]},accountStateFindings:[],relationshipEvidencePacketCoverageComplete:true,collectionActivityIdentityReviewComplete:false,linkedSubjectRelationshipReviewComplete:false,repeatabilityReviewComplete:false,requirementsXpTimingAndMechanicsComplete:false,completeActivityUniverse:false,absoluteBestGate:'blocked_incomplete_activity_universe',blockers:['relationship_candidate_observations_require_semantic_review','collection_activity_identity_not_established','linked_subject_relationship_review_pending','canonical_game_entity_and_activity_identities_not_established','repeatability_and_member_expansion_not_reviewed','requirements_xp_timing_and_mechanics_not_structured','independent_complete_activity_universe_not_established'],publishable:true};
  const manifest={contract:'sensum.ingestion-manifest.v1',domain:'activity-reference-collection-member-unresolved-subject-relationship-evidence',createdAt:'2026-09-06T23:10:00Z',records:1,contentHash:hash(raw),source:{kind:'revision_pinned_collection_row_and_linked_source_page_relationship_review_evidence_without_semantic_inference',policy:{id:'fixture',file:'fixture',contentHash:'5'.repeat(64)},routingSnapshot:{directory:'routing',contentHash:'6'.repeat(64),rejections:[]},sourceSignatureSnapshot:{directory:'signatures',contentHash:'7'.repeat(64),rejections:[]},audit:structuredClone(coreAudit)}};
  const audit={...structuredClone(coreAudit),generatedAt:'2026-09-06T23:10:01Z',policy:{id:'fixture',file:'fixture',contentHash:'5'.repeat(64)},routingSnapshot:{directory:'routing',contentHash:'6'.repeat(64),rejections:[]},sourceSignatureSnapshot:{directory:'signatures',contentHash:'7'.repeat(64),rejections:[]},outputSnapshot:{directory,contentHash:manifest.contentHash}};
  audit.contentHash=hash(audit);
  return {raw,manifest,audit,record};
}

function rehashInput(input) { input.record.contentHash=hash(without(input.record,'contentHash')); input.raw=JSON.stringify(input.record)+'\n'; input.manifest.contentHash=hash(input.raw); input.audit.outputSnapshot.contentHash=input.manifest.contentHash; input.audit.contentHash=hash(without(input.audit,'contentHash')); }

test('unresolved relationship evidence remains candidate-only and preserves both source layers',()=>{
  const input=fixture(),first=validateActivityReferenceMemberUnresolvedRelationshipMaterializationInput(input),second=validateActivityReferenceMemberUnresolvedRelationshipMaterializationInput(input);
  assert.equal(first.materializationHash,second.materializationHash);
  assert.deepEqual(first.counts,{sources:2,records:1,statements:1,sourceAuthoredLinks:2,mainNamespaceRelationshipCandidates:1,collectionRowLinkCandidates:1});
  assert.deepEqual(first.skillKeys,[]);
  assert.equal(first.statements[0].payload.relationshipVerdict,null);
  assert.equal(first.gates.linkedSubjectRelationshipReviewComplete,false);
  const historical=fixture(); delete historical.manifest.snapshotDirectory; assert.equal(validateActivityReferenceMemberUnresolvedRelationshipMaterializationInput(historical).snapshotDirectory,historical.audit.outputSnapshot.directory);
});

test('relationship tampering, account state, promotion, count drift, and source drift fail closed',()=>{
  const tampered=fixture(); tampered.raw=tampered.raw.replace('Example activity','Changed activity'); assert.throws(()=>validateActivityReferenceMemberUnresolvedRelationshipMaterializationInput(tampered),/snapshot_content_hash_mismatch/);
  const account=fixture(); account.record.currentBaseLevel=34; rehashInput(account); assert.throws(()=>validateActivityReferenceMemberUnresolvedRelationshipMaterializationInput(account),/record_account_state_present/);
  const promoted=fixture(); promoted.record.relationshipCandidateObservations.relationshipVerdict='same_activity'; promoted.record.linkedSubjectRelationshipReview={state:'reviewed',relationships:['same_activity'],evidenceKeys:['source:1']}; rehashInput(promoted); assert.throws(()=>validateActivityReferenceMemberUnresolvedRelationshipMaterializationInput(promoted),/relationship_review_not_closed|candidate_observations_invalid/);
  const countDrift=fixture(); countDrift.audit.evidenceCoverage.sourceAuthoredLinkOccurrenceCount=3; countDrift.audit.contentHash=hash(without(countDrift.audit,'contentHash')); assert.throws(()=>validateActivityReferenceMemberUnresolvedRelationshipMaterializationInput(countDrift),/manifest_embedded_audit_mismatch|counts_do_not_reconcile/);
  const sourceDrift=fixture(); sourceDrift.record.sourcePageEvidence.sourceRevision='124'; rehashInput(sourceDrift); assert.throws(()=>validateActivityReferenceMemberUnresolvedRelationshipMaterializationInput(sourceDrift),/source_page_evidence_invalid/);
  const evidenceLoss=fixture(); evidenceLoss.record.collectionMembershipEvidence.memberLinks=[]; rehashInput(evidenceLoss); assert.throws(()=>validateActivityReferenceMemberUnresolvedRelationshipMaterializationInput(evidenceLoss),/collection_evidence_context_mismatch|candidate_observations_invalid/);
  const directoryDrift=fixture(); directoryDrift.manifest.snapshotDirectory='different'; assert.throws(()=>validateActivityReferenceMemberUnresolvedRelationshipMaterializationInput(directoryDrift),/audit_output_snapshot_mismatch/);
});

test('relationship SQL is transactional, insert-only, candidate-only, and lineage-bound',()=>{
  const model=validateActivityReferenceMemberUnresolvedRelationshipMaterializationInput(fixture()),sql=buildActivityReferenceMemberUnresolvedRelationshipMaterializationSql(model);
  assert.match(sql,/^\\set ON_ERROR_STOP on\nBEGIN;/); assert.match(sql,/pg_advisory_xact_lock/); assert.match(sql,new RegExp(ACTIVITY_REFERENCE_MEMBER_UNRESOLVED_RELATIONSHIP_FACT_KIND)); assert.match(sql,/'candidate'/); assert.match(sql,/'review'/); assert.match(sql,/INSERT INTO activity_evidence_ingestion_lineage/); assert.match(sql,/ON CONFLICT .* DO NOTHING/); assert.match(sql,/COMMIT;\n$/); assert.doesNotMatch(sql,/\bDELETE\b|\bTRUNCATE\b|\bUPDATE\b/i); assert.match(buildActivityReferenceMemberUnresolvedRelationshipExistingSourceCountQuery(model),/published_at=e\.published_at/);
});

test('relationship reconciliation rejects count, lineage, completeness, and semantic drift',()=>{
  const model=validateActivityReferenceMemberUnresolvedRelationshipMaterializationInput(fixture());
  const actual={runId:model.runId,status:'published',records:1,sources:2,statements:1,lineage:1,snapshotComplete:false,metrics:{recordHashAggregate:model.recordHashAggregate,sourceHashAggregate:model.sourceHashAggregate,statementHashAggregate:model.statementHashAggregate,materializationHash:model.materializationHash,...model.gates}};
  assert.equal(verifyActivityReferenceMemberUnresolvedRelationshipReconciliation(model,actual),true);
  assert.throws(()=>verifyActivityReferenceMemberUnresolvedRelationshipReconciliation(model,{...actual,sources:1}),/sources_count_mismatch/); assert.throws(()=>verifyActivityReferenceMemberUnresolvedRelationshipReconciliation(model,{...actual,lineage:0}),/lineage_count_mismatch/); assert.throws(()=>verifyActivityReferenceMemberUnresolvedRelationshipReconciliation(model,{...actual,snapshotComplete:true}),/must_not_claim_complete/); assert.throws(()=>verifyActivityReferenceMemberUnresolvedRelationshipReconciliation(model,{...actual,metrics:{...actual.metrics,linkedSubjectRelationshipReviewComplete:true}}),/semantic_gate_weakened/);
});
