import {finiteConditionLevel,isTrainableVariantRecord,resolveEntryAndModeledLevels,resolveVariantConditionModel} from '../transforms/activity-variant-condition-lib.mjs';
const failures=[],check=(ok,message)=>{if(!ok)failures.push(message)};
const boosted=resolveVariantConditionModel({entry_boostable:false,base_agility_level_minimum:70,effective_agility_level_minimum:75,failure_free_effective_agility_level:75,boost_policy:'maintain_effective_level',equipment_requirement:{mode:'one_of'}});
check(boosted.baseLevelMinimum===70&&boosted.effectiveLevelMinimum===75,'Base and effective Agility levels must remain separate.');
check(boosted.failure?.value?.minimum_level===75&&boosted.failure?.value?.level_kind==='effective','An effective-level failure threshold must not become a base requirement.');
check(boosted.conditionDetails.entryBoostable===false&&boosted.conditionDetails.boostPolicy==='maintain_effective_level','Entry and training boost policies must remain independent.');
const compound=resolveVariantConditionModel({failure_free_condition:{all_of:[{skill:'Agility',minimum:80},{skill:'Strength',minimum:80},{carried_weight_kg:{maximum:2}}]}});
check(compound.failure?.value?.probability===0&&compound.failure?.value?.minimum_level===80&&compound.failure?.value?.level_kind==='compound'&&compound.failure?.value?.all_of?.length===3,'Compound failure-free conditions must retain the Agility threshold and remain conjunctive.');
const partial=resolveVariantConditionModel({failure_free_level:50,unmodeled_level_ranges:[{minimum:20,maximum:49,blocker:'failure_probability_by_level_missing'}]});
check(partial.conditionDetails.unmodeledLevelRanges?.[0]?.maximum===49,'Explicit level ranges without a trustworthy condition model must survive vector generation.');
check(isTrainableVariantRecord({variant_key:'method'})&&!isTrainableVariantRecord({record_kind:'composable_modifier'})&&!isTrainableVariantRecord({record_kind:'encounter_requirement'}),'Composable effects and encounter requirements must not become standalone methods.');
const noAccessRequirement=resolveEntryAndModeledLevels({explicitEntryLevel:0,baseLevelMinimum:40});
check(noAccessRequirement.entryLevel===0&&noAccessRequirement.modeledMinimumLevel===40,'A zero access requirement must remain known while a level-specific rate keeps its modeled minimum.');
const timeOutcome=resolveVariantConditionModel({skill_requirements:{Agility:25},outcome_model:'completion_time_reward',random_failure_roll_applicable:false,completion_scope:'all_10_goals_completed'});
check(timeOutcome.conditionDetails.outcomeModel==='completion_time_reward'&&timeOutcome.conditionDetails.randomFailureRollApplicable===false&&timeOutcome.conditionDetails.completionScope==='all_10_goals_completed','Time-based completion outcomes must survive condition resolution without becoming random success rolls.');
const qualitative=resolveVariantConditionModel({failure_possible:true,failure_qualifier:'very_unlikely',failure_probability_published:false,supporting_evidence:{source_revision:'9'}});
check(qualitative.failure===null&&qualitative.conditionDetails.failurePossible===true&&qualitative.conditionDetails.failureQualifier==='very_unlikely'&&qualitative.conditionDetails.failureProbabilityPublished===false,'Qualitative failure evidence must survive without becoming a synthetic probability.');
check(qualitative.conditionDetails.failureEvidence?.source_revision==='9','The supporting condition revision must survive vector condition resolution.');
const unknown=resolveEntryAndModeledLevels({explicitEntryLevel:null,inferredEntryLevels:[null,undefined]});
check(unknown.entryLevel===null&&unknown.modeledMinimumLevel===null&&finiteConditionLevel(null)===null,'Missing levels must not be coerced to zero.');
if(failures.length){console.error(failures.join('\n'));process.exit(1)}console.log('Activity variant condition checks passed.');
