import {auditAgilityHallowedGuideMemberCoverage,HALLOWED_SECTION_KEY,HALLOWED_GUIDE_CANDIDATE_KEY,HALLOWED_FLOOR_POLICY_KEYS,HALLOWED_EQUIPMENT_KEYS} from '../transforms/agility-hallowed-guide-member-coverage-lib.mjs';
import {auditAgilityTrainingGuideSectionCoverage} from '../transforms/agility-training-guide-section-coverage-lib.mjs';

const guideRevision='15324367',hallowedRevision='15322138',guideCandidates=[{candidate_key:HALLOWED_GUIDE_CANDIDATE_KEY,source_section_key:HALLOWED_SECTION_KEY,source_revision:guideRevision,composite_variant_axes:['maximum_floor','looting_policy','equipment_state']}],entryLevels=[52,62,72,77,87],floorPolicyVariants=HALLOWED_FLOOR_POLICY_KEYS.map(recordKey=>{const floor=Number(recordKey.match(/floor-(\d+)/)[1]),lootingPolicy=recordKey.endsWith(':no_looting')?'no_looting':'looting';return {record_key:recordKey,parent_name:'Hallowed Sepulchre',floor,looting_policy:lootingPolicy,entry_level:entryLevels[floor-1],observed_xp_per_hour:30000+floor*1000,source_revision:hallowedRevision}}),equipmentMembers=HALLOWED_EQUIPMENT_KEYS.map((recordKey,index)=>({record_key:recordKey,parent_name:'Hallowed Sepulchre',record_kind:index%3?'composable_modifier':'encounter_requirement',encounter:`encounter-${index}`,source_revision:hallowedRevision})),vectors=HALLOWED_FLOOR_POLICY_KEYS.map((recordKey,index)=>({recordKey,scenarioKey:`hallowed:${index}`,sourceRevision:hallowedRevision})),failures=[],check=(ok,message)=>{if(!ok)failures.push(message)};

const complete=auditAgilityHallowedGuideMemberCoverage({guideCandidates,floorPolicyVariants,equipmentMembers,vectors});
check(complete.internalMemberAuditSatisfied===true&&complete.memberCount===10&&complete.coveredMemberCount===10&&complete.floorCount===5&&complete.lootingPolicyCount===2,'Five floors crossed with two policies must produce ten covered decision members.');
check(complete.vectorMatchCount===10&&complete.equipmentMemberCount===13&&complete.coveredEquipmentMemberCount===13,'Every decision member must link to one vector and every equipment member must remain independent.');
check(complete.guideSourceRevision===guideRevision&&complete.hallowedSourceRevision===hallowedRevision,'Guide and detail-page revisions must remain separately visible.');
check(complete.floorPolicyIdentityCoverageOnly===true&&complete.equipmentModifierCatalogLinked===true&&complete.variantCompletenessProven===false&&complete.mechanicalCompletenessProven===false,'Identity coverage must not overclaim combination or mechanical completeness.');

const missingFloor=auditAgilityHallowedGuideMemberCoverage({guideCandidates,floorPolicyVariants:floorPolicyVariants.slice(1),equipmentMembers,vectors});
check(missingFloor.blockers.includes('one_or_more_hallowed_floor_policy_members_incomplete')&&missingFloor.memberDetails[0].blockers.includes('hallowed_floor_policy_member_missing'),'A missing floor/policy member must block the collection.');
const missingVector=auditAgilityHallowedGuideMemberCoverage({guideCandidates,floorPolicyVariants,equipmentMembers,vectors:vectors.slice(0,-1)});
check(missingVector.memberDetails.at(-1).blockers.includes('hallowed_floor_policy_vector_missing'),'A missing exact vector must block its member.');
const staleVector=auditAgilityHallowedGuideMemberCoverage({guideCandidates,floorPolicyVariants,equipmentMembers,vectors:vectors.map((vector,index)=>index?vector:{...vector,sourceRevision:'older'})});
check(staleVector.memberDetails[0].blockers.includes('hallowed_floor_policy_vector_revision_mismatch'),'A vector from another Hallowed revision must not satisfy the member.');
const missingEquipment=auditAgilityHallowedGuideMemberCoverage({guideCandidates,floorPolicyVariants,equipmentMembers:equipmentMembers.slice(0,-1),vectors});
check(missingEquipment.blockers.includes('one_or_more_hallowed_equipment_members_incomplete'),'A missing equipment member must block the collection.');
const changedAxes=auditAgilityHallowedGuideMemberCoverage({guideCandidates:[{...guideCandidates[0],composite_variant_axes:['maximum_floor','looting_policy']}],floorPolicyVariants,equipmentMembers,vectors});
check(changedAxes.blockers.includes('hallowed_guide_composite_axes_incomplete_or_changed'),'The guide candidate must retain all declared composite axes.');
const unexpected=auditAgilityHallowedGuideMemberCoverage({guideCandidates,floorPolicyVariants:[...floorPolicyVariants,{...floorPolicyVariants[0],record_key:'hallowed-sepulchre:floor-6:looting',floor:6}],equipmentMembers:[...equipmentMembers,{...equipmentMembers[0],record_key:'hallowed-equipment:new'}],vectors:[...vectors,{recordKey:'hallowed-sepulchre:floor-6:looting',scenarioKey:'new',sourceRevision:hallowedRevision}]});
check(unexpected.blockers.includes('unexpected_hallowed_floor_policy_member')&&unexpected.blockers.includes('unexpected_hallowed_equipment_member')&&unexpected.blockers.includes('unexpected_hallowed_floor_policy_vector'),'Unreviewed floor, equipment, or vector identities must fail closed.');

const section={sectionKey:HALLOWED_SECTION_KEY,title:'Levels 62–99: Hallowed Sepulchre',sourceOrder:4,sectionRole:'composite_method_section',repeatableTraining:true,requiresInternalMemberAudit:true,materialToCandidateUniverse:true,sourceRevision:guideRevision,sourceUrl:'https://oldschool.runescape.wiki/w/Agility_training',sourceLocator:{headingLine:1}},sectionCoverage=auditAgilityTrainingGuideSectionCoverage({sections:[section],candidates:guideCandidates,memberAudits:[{sectionKey:HALLOWED_SECTION_KEY,complete:true,sourceRevision:guideRevision,contentHash:'test',memberCount:10,coveredMemberCount:10,uncoveredMemberCount:0}]});
check(sectionCoverage.internalMemberAuditPendingCount===0&&sectionCoverage.sectionDetails[0].internalMemberAuditSatisfied===true,'A complete same-guide-revision Hallowed audit must clear only its section identity gate.');

if(failures.length){console.error(failures.join('\n'));process.exit(1)}
console.log('Agility Hallowed guide-member coverage checks passed.');
