import {parseAgilityConditionVariants} from '../ingestion/agility-condition-variant-lib.mjs';
const content=`The course has no requirements to access other than a 200 [[coins]] fee paid before each entry.
Every minute, one of these Ticket Dispensers will be activated, and the player should try to find their way to this activated dispenser by traversing the Agility obstacles as quickly as possible. For every Ticket Dispenser tagged, one ticket will be awarded.
The best experience per hour rates will be achieved by non-stop completing Agility obstacles during the waiting time.
Wear [[Karamja gloves 2]], [[Karamja gloves 3|3]], or [[Karamja gloves 4|4]] for 10% extra Agility experience from obstacles.
Players who have completed the elite tasks in the [[Karamja Diary]] will have a 10% chance to receive two tickets and vouchers.
Tagging a dispenser awards 30 [[Agility]] experience for every 10 Agility levels (including boosts), maxing out at 300 if boosting to level 100 Agility. Unlike obstacles, this is not affected by the 10% Karamja gloves 2-4 bonus. Tickets can be exchanged for 345 [[Agility]] experience per ticket. Players wearing [[Karamja gloves 2]], [[Karamja gloves 3|3]], or [[Karamja gloves 4|4]] will receive an additional 10% experience, giving 379.5 Agility experience per ticket.
At level 99 with the elite diary complete, expect to be able to achieve up to 68,000 Agility experience per hour when constantly jumping over floor spikes during down time. Having level 100+ Agility makes pillars give 300 experience each instead of 270, so using the [[Agility cape]] or other [[Temporary skill boosts#Agility|temporary boosts]] can increase the maximum experience per hour up to about 70,000.
Base experience rates for a more passive approach (only traversing obstacles to reach each marked pillar) can be estimated from the experience earned by tagging pillars and redeeming tickets alone. At level 40 Agility, players can earn roughly 28,000 experience per hour (or 30,000 experience per hour with Karamja gloves 2). At level 80 Agility, players can earn roughly 35,000 experience per hour (or roughly 37,000 experience per hour with Karamja gloves 2). If the elite tier of the Karamja Diary is complete, players can expect roughly 2,277 experience per hour added onto these rates (regardless of Agility level). These rates assume no pillars are missed (60 pillars tagged per hour).`;
const rows=parseAgilityConditionVariants({title:'Brimhaven Agility Arena',content,sourceRevision:'15293118',sourceTimestamp:'2026-08-11',sourceUrl:'https://example.test'}),failures=[],check=(ok,message)=>{if(!ok)failures.push(message)};
check(rows.length===14,'Brimhaven must emit eight passive observations, four passive formula policies, and two active conditions.');
check(new Set(rows.map(x=>x.candidate_group_key)).size===6,'Observations and formulas for each passive policy must collapse to one stable candidate identity.');
check(rows.every(x=>x.candidate_group_key&&x.candidate_display_name),'Every condition variant must declare stable candidate identity and display text.');
const passive=rows.find(x=>x.variant_key==='passive_level_40_no_gloves_no_elite'),combined=rows.find(x=>x.variant_key==='passive_level_80_gloves_elite'),active=rows.find(x=>x.variant_key==='active_level_99_elite'),boosted=rows.find(x=>x.variant_key==='active_boosted_100_elite');
check(passive?.observed_xp_per_hour===28000&&passive.entry_level===0&&Object.keys(passive.skill_requirements||{}).length===0,'The level-40 benchmark must not become a level-40 access requirement.');
check(passive?.base_agility_level_minimum===40&&passive?.benchmark_base_agility_level===40&&passive?.observed_xp_per_hour_level_scope?.minimum===40&&passive?.observed_xp_per_hour_level_scope?.maximum===40,'Level-40 passive evidence must retain an exact machine-readable benchmark scope.');
check(passive?.observational_benchmark_only===true&&passive?.outcome_integrated_in_observed_rate===true&&passive?.observed_rate_kind==='approximate_passive_pillar_benchmark','Passive estimates must remain source observations rather than synthetic mechanical rates.');
check(passive?.candidate_group_key==='agility-condition:Brimhaven Agility Arena:passive_no_gloves_no_elite'&&rows.filter(x=>x.candidate_group_key===passive.candidate_group_key).length===3,'Level-40/80 observations and the parameterized formula must share one globally scoped candidate group.');
check(combined?.observed_xp_per_hour===39277&&combined.observed_rate_components?.elite_diary_added_xp_per_hour===2277,'Glove and elite effects must remain independent, additive evidence components.');
check(combined?.requirement_alternatives?.length===3&&combined.axis_coverage.includes('equipment_modifier')&&combined.axis_coverage.includes('achievement_modifier'),'All sourced glove alternatives and diary coverage must remain explicit.');
check(active?.observed_xp_per_hour===68000&&active.equipment_policy==='karamja_gloves_state_not_specified_by_rate_statement','The active rate must not silently assume Karamja gloves.');
check(boosted?.skill_requirements?.Agility===99&&boosted.effective_agility_level_minimum===100&&boosted.axis_coverage.includes('temporary_boost'),'Base level and boosted effective level must remain separate.');
check(boosted?.pillar_tag_xp===300&&active?.pillar_tag_xp===270&&boosted.observed_xp_per_hour===70000&&boosted.observed_rate_about===true,'Boosted pillar XP and approximate maximum rate must retain their source conditions.');
const formulaRows=rows.filter(x=>x.expected_xp_per_hour_model),benchmarkRows=rows.filter(x=>x.observed_xp_per_hour);
check(formulaRows.length===4&&formulaRows.every(x=>x.base_agility_level_minimum===1&&x.failure_model_required===false&&x.source_locator?.evidence?.length),'Every passive policy must have one revision-located, account-independent formula row.');
check(formulaRows.every(x=>x.expected_xp_per_hour_model?.tag_and_ticket_xp_only===true&&x.expected_xp_per_hour_model?.obstacle_xp_included===false&&x.expected_xp_per_hour_model?.assumes_no_missed_pillars===true),'Formula scope must stay limited to the source-stated tag-and-ticket-only, no-missed-pillar conditions.');
check(benchmarkRows.length===10&&benchmarkRows.every(x=>x.observed_rate_approximate===true&&x.source_locator?.evidence?.length),'Every source-observed Brimhaven rate must remain approximate and revision-located.');
if(failures.length){console.error(failures.join('\n'));process.exit(1)}console.log('Agility condition variant checks passed.');
