import {parseAgilityColossalWyrmGuideMembers,COLOSSAL_WYRM_SECTION_KEY} from '../ingestion/agility-colossal-wyrm-guide-member-lib.mjs';
import {auditAgilityColossalWyrmGuideMemberCoverage} from '../transforms/agility-colossal-wyrm-guide-member-coverage-lib.mjs';
import {auditAgilityTrainingGuideSectionCoverage} from '../transforms/agility-training-guide-section-coverage-lib.mjs';

const page=(title,content,revision)=>({title,content,sourceRevision:revision,sourceTimestamp:'2026-09-01T00:00:00Z',sourceUrl:`https://oldschool.runescape.wiki/w/${title.replaceAll(' ','_')}`}),guide=page('Agility training',`===Levels 50/62: Colossal Wyrm Agility Course===
The [[Colossal Wyrm Agility Course]] is a less click-intensive course that offers an alternative way to get rewards.

There are two routes, the basic course requires 50 Agility and gives up to 31,000 xp/hr, and the advanced course requires 62 Agility and gives up to 42,000 xp/hr. The advanced route requires only 6 clicks per 60-second lap, with two sections of the course allowing a full 20 seconds of AFK time each.
===Levels 60–80/90: Werewolf Agility Course===`,'15324367'),course=page('Colossal Wyrm Agility Course',`{{Obsolete|Changes to course durations, experience, termites, and bone shards.|update=Update:Summer Sweep Up - Agility & Chambers of Xeric Changes}}
There are two courses available to players beginning at 50 Agility for the basic course, and 62 Agility for the advanced course. Both are lower intensity courses than most other agility courses, with fewer obstacles each with longer animations, averaging about 90 seconds per lap.
==Gameplay==
Both courses share a common entrance ladder and first tightrope obstacle. After the first obstacle, players with 62 Agility can climb a ladder to complete the Advanced course for higher experience rates and 3 obstacles unique from the basic course. The courses merge for a final zipline, granting a total of 633 experience for basic lap completion, and 1053.6 experience for advanced lap completion.
Players never fail obstacles on either course.
Under ideal conditions, the basic course can be completed in 1:07.80, yielding approximately 49 completions per hour (including 3.6 seconds of downtime between laps) and ~31,000 xp/hr.
The advanced course can be completed in 1:22.80, allowing roughly 41 completions per hour and ~43,000 xp/hr.`,'15313984'),agility=page('Agility',`=== Colossal Wyrm Agility Course ===
The Colossal Wyrm Agility Course requires level 50 Agility and completion of {{SCP|Quest}} [[Children of the Sun]] to access. The Agility course consists of a regular and an advanced course. After the second obstacle the player can choose to do one of the two courses. Selecting the tight rope will put the player on the basic course. The regular course consists of six obstacles and gives 504.1 experience per lap. At level 62 Agility the player can do the Advanced Course. If the player selects the ladder the player will be on the advanced course. The Advanced course consists of six obstacles and gives 749.6 experience per lap.
Players can expect to get up to 31,000 Agility experience per hour on the basic course, and up to 44,000 experience per hour on the advanced course.`,'15326985'),update=page('Update:Summer Sweep Up - Agility & Chambers of Xeric Changes',`====Colossal Wyrm Agility course====
* Increased the duration of the Colossal Wyrm Agility course:
** The basic course by ~25%.
** The advanced course by ~40%.
* Increased XP, Bone shards and Termites to match so that it's roughly the same XP/hr and termites/hr but fewer inputs/hr, meaning the course is lower intensity than before.`,'15303824'),input={guide,course,agility,update},parsed=parseAgilityColossalWyrmGuideMembers(input),failures=[],check=(ok,message)=>{if(!ok)failures.push(message)},basic=parsed.records[0],advanced=parsed.records[1];

check(parsed.audit.publishable===true&&parsed.audit.memberCount===2&&parsed.audit.guideParagraphCount===2,'The exact source set must publish two route identities across the two guide paragraphs.');
check(basic.memberKey==='colossal-wyrm:basic-route'&&advanced.memberKey==='colossal-wyrm:advanced-route'&&basic.minimumAgility===50&&advanced.minimumAgility===62,'Basic and advanced routes must retain stable identities, order, and requirements.');
check(basic.corroboratingMinimumAgility.every(level=>level===50)&&advanced.corroboratingMinimumAgility.every(level=>level===62),'All three route sources must agree on entry levels.');
check(basic.coursePageMarkedObsolete===true&&basic.mechanicalBlockers.includes('course_detail_page_marked_obsolete_for_duration_experience_termites_and_bone_shards'),'The detail-page obsolete notice must remain visible.');
check(basic.rateClaims.map(claim=>claim.xpPerHour).join('|')==='31000|31000|31000'&&basic.lapXpClaims.map(claim=>claim.xpPerLap).join('|')==='633|504.1','Basic rate agreement must not hide its conflicting lap-XP claims.');
check(advanced.rateClaims.map(claim=>claim.xpPerHour).join('|')==='42000|43000|44000'&&advanced.mechanicalBlockers.includes('advanced_rate_conflict_42000_vs_43000_vs_44000'),'All three conflicting advanced rates must survive without selection.');
check(advanced.timingClaims[0].seconds===60&&advanced.timingClaims[0].clicks===6&&advanced.timingClaims[0].afkSections===2&&advanced.timingClaims[1].seconds===82.8,'Guide interaction/timing and detail-page ideal timing must remain separate claims.');
check(advanced.timingClaims[2].approximateIncreasePercent===40&&advanced.timingClaims[2].exactPostUpdateDurationPublished===false,'A relative update percentage must not manufacture an exact post-update duration.');
check(parsed.records.every(record=>record.guideSourceRevision==='15324367'&&record.courseSourceRevision==='15313984'&&record.agilitySourceRevision==='15326985'&&record.updateSourceRevision==='15303824'),'Every source revision must remain attached independently.');

const guideCandidates=parsed.records.map(record=>({candidate_key:record.candidateKey,source_section_key:record.sectionKey,source_revision:record.guideSourceRevision,minimum_agility:record.minimumAgility})),coverage=auditAgilityColossalWyrmGuideMemberCoverage({members:parsed.records,guideCandidates});
check(coverage.internalMemberAuditSatisfied===true&&coverage.memberCount===2&&coverage.coveredMemberCount===2&&coverage.uncoveredMemberCount===0,'Both route identities must match exactly one same-guide-revision candidate.');
check(coverage.mechanicalCompletenessProven===false&&coverage.mechanicalBlockers.length===6&&coverage.absoluteBestGate==='blocked_conflicting_or_obsolete_colossal_wyrm_mechanics','Identity coverage must not clear obsolete and contradictory mechanics.');
const missing=auditAgilityColossalWyrmGuideMemberCoverage({members:parsed.records,guideCandidates:guideCandidates.slice(0,1)});check(missing.internalMemberAuditSatisfied===false&&missing.memberDetails[1].identityBlockers.includes('same_revision_guide_candidate_missing'),'A missing advanced candidate must fail identity coverage.');
const stale=auditAgilityColossalWyrmGuideMemberCoverage({members:parsed.records,guideCandidates:guideCandidates.map((candidate,index)=>index?{...candidate,source_revision:'older'}:candidate)});check(stale.internalMemberAuditSatisfied===false&&stale.memberDetails[1].identityBlockers.includes('guide_candidate_revision_mismatch'),'A stale guide candidate must not satisfy the member.');
const wrongLevel=auditAgilityColossalWyrmGuideMemberCoverage({members:parsed.records,guideCandidates:guideCandidates.map((candidate,index)=>index?{...candidate,minimum_agility:61}:candidate)});check(wrongLevel.memberDetails[1].identityBlockers.includes('guide_candidate_minimum_agility_mismatch'),'A mismatched route requirement must fail closed.');
const unexpected=auditAgilityColossalWyrmGuideMemberCoverage({members:parsed.records,guideCandidates:[...guideCandidates,{candidate_key:'guide:colossal-wyrm:invented',source_section_key:COLOSSAL_WYRM_SECTION_KEY,source_revision:'15324367',minimum_agility:1}]});check(unexpected.identityBlockers.includes('guide_section_candidate_not_present_in_route_inventory'),'An unexpected route candidate must block the audit.');

const sectionCoverage=auditAgilityTrainingGuideSectionCoverage({sections:[{sectionKey:COLOSSAL_WYRM_SECTION_KEY,title:'Levels 50/62: Colossal Wyrm Agility Course',sourceOrder:12,sectionRole:'composite_method_section',repeatableTraining:true,requiresInternalMemberAudit:true,materialToCandidateUniverse:true,sourceRevision:'15324367',sourceUrl:guide.sourceUrl,sourceLocator:{headingLine:1}}],candidates:guideCandidates,memberAudits:[{sectionKey:COLOSSAL_WYRM_SECTION_KEY,complete:true,sourceRevision:'15324367',contentHash:'test',memberCount:2,coveredMemberCount:2,uncoveredMemberCount:0}]});
check(sectionCoverage.internalMemberAuditPendingCount===0&&sectionCoverage.sectionDetails[0].internalMemberAuditSatisfied===true,'Complete route identity must clear only the Colossal composite-member gate.');

for(const [changed,key,blocker] of [[{...guide,content:guide.content.replace('There are two routes','There are routes')},'guide','colossal_wyrm_guide_route_claims_missing_or_changed'],[{...course,content:course.content.replace('{{Obsolete|Changes to course durations, experience, termites, and bone shards.|update=Update:Summer Sweep Up - Agility & Chambers of Xeric Changes}}','')},'course','colossal_wyrm_course_obsolete_notice_missing_or_changed'],[{...agility,content:agility.content.replace('504.1','504')},'agility','agility_overview_colossal_route_claims_missing_or_changed'],[{...update,content:update.content.replace('~40%','~41%')},'update','colossal_wyrm_update_claims_missing_or_changed']]){const result=parseAgilityColossalWyrmGuideMembers({...input,[key]:changed});check(result.audit.publishable===false&&result.audit.blockers.includes(blocker),`${blocker} must block source publication.`)}

if(failures.length){console.error(failures.join('\n'));process.exit(1)}
console.log('Agility Colossal Wyrm route identity and mechanical-conflict checks passed.');
