import fs from 'node:fs';
const sql=fs.readFileSync('platform/db/migrations/0001_canonical_osrs.sql','utf8');
const optimizer=JSON.parse(fs.readFileSync('platform/contracts/optimizer-v1.json','utf8'));
const result=JSON.parse(fs.readFileSync('platform/contracts/calculation-result-v1.json','utf8'));
const control=fs.readFileSync('platform/db/migrations/0002_ingestion_control.sql','utf8');
const formulas=JSON.parse(fs.readFileSync('platform/contracts/formula-registry-v1.json','utf8'));
const formulaSql=fs.readFileSync('platform/db/migrations/0003_formula_registry.sql','utf8');
const activitySql=fs.readFileSync('platform/db/migrations/0004_activity_methods.sql','utf8');
const activity=JSON.parse(fs.readFileSync('platform/contracts/activity-method-v1.json','utf8'));
const evidenceSql=fs.readFileSync('platform/db/migrations/0005_activity_evidence.sql','utf8');
const evidence=JSON.parse(fs.readFileSync('platform/contracts/activity-evidence-v1.json','utf8'));
const familySql=fs.readFileSync('platform/db/migrations/0006_activity_families.sql','utf8');
const family=JSON.parse(fs.readFileSync('platform/contracts/activity-family-v1.json','utf8'));
const goldenSql=fs.readFileSync('platform/db/migrations/0007_golden_activity_vectors.sql','utf8');
const golden=JSON.parse(fs.readFileSync('platform/contracts/golden-activity-vector-v1.json','utf8'));
const review=JSON.parse(fs.readFileSync('platform/contracts/golden-review-packet-v1.json','utf8'));
const decision=JSON.parse(fs.readFileSync('platform/contracts/golden-review-decision-v1.json','utf8'));
const certificateSql=fs.readFileSync('platform/db/migrations/0008_recommendation_certificates.sql','utf8');
const certificate=JSON.parse(fs.readFileSync('platform/contracts/recommendation-certificate-v1.json','utf8'));
const agilityTable=JSON.parse(fs.readFileSync('platform/contracts/agility-course-table-v1.json','utf8'));
const failures=[];const check=(ok,msg)=>{if(!ok)failures.push(msg)};
for(const table of ['data_sources','data_snapshots','items','equipment','effects','npcs','npc_combat_stats','locations','recipes','price_observations','profiles','account_snapshots','training_methods','optimization_runs','optimization_evidence','validation_findings'])check(new RegExp(`CREATE TABLE ${table} \\(`).test(sql),`Missing canonical table: ${table}`);
check(/content_hash text NOT NULL/.test(sql),'Sources must be content-addressed.');
check(/formula_version text NOT NULL/.test(sql),'Calculations must retain formula versions.');
check(/unknown_count bigint/.test(sql),'Runs must expose unknown candidate coverage.');
check(optimizer.claimPolicy.absoluteBestRequiresCompleteCandidateCoverage===true,'Absolute-best requires complete coverage.');
check(optimizer.claimPolicy.aiGeneratedFactsAllowed===false,'AI facts must not be authoritative.');
check(result.explanation.authoritative===false,'AI explanations must be non-authoritative.');
for(const table of ['ingestion_runs','ingestion_records','publication_gates'])check(new RegExp(`CREATE TABLE ${table} \\(`).test(control),`Missing ingestion-control table: ${table}`);
check(/maximum_unknown_ratio/.test(control)&&/require_source_revision/.test(control),'Publication gates must enforce completeness and provenance.');
for(const file of ['platform/ingestion/lib.mjs','platform/ingestion/ingest-ge.mjs','platform/ingestion/ingest-wiki-domain.mjs','platform/ingestion/audit-local-catalogs.mjs'])check(fs.existsSync(file),`Missing ingestion component: ${file}`);
for(const table of ['formula_registry','formula_test_vectors','canonicalization_runs','entity_quarantine'])check(new RegExp(`CREATE TABLE ${table} \\(`).test(formulaSql),`Missing formula/canonicalization table: ${table}`);
check(formulas.formulas.every(x=>x.source&&x.state==='draft'),'New formulas must start source-linked and unverified.');
check(fs.existsSync('platform/transforms/canonicalize.mjs'),'Canonical transform is missing.');
for(const file of ['platform/formulas/osrs-v1.mjs','platform/formulas/verify.mjs'])check(fs.existsSync(file),`Missing formula component: ${file}`);
for(const table of ['activity_methods','activity_locations','activity_requirements','activity_model_vectors'])check(new RegExp(`CREATE TABLE ${table} \\(`).test(activitySql),`Missing activity table: ${table}`);
check(activity.claimPolicy.absoluteBestRequiresVerifiedMethodVector===true,'Activity claims require verified method vectors.');
check(activity.claimPolicy.aiGeneratedFactsAllowed===false,'AI activity facts must not be authoritative.');
for(const file of ['platform/formulas/activity-v1.mjs','platform/formulas/verify-activity.mjs','platform/transforms/activity-readiness.mjs'])check(fs.existsSync(file),`Missing activity engine component: ${file}`);
for(const table of ['activity_evidence','activity_enrichment_runs'])check(new RegExp(`CREATE TABLE ${table} \\(`).test(evidenceSql),`Missing activity evidence table: ${table}`);
check(evidence.promotionRules.verifiedRequiresPassingModelVector===true,'Verified activity evidence requires a passing model vector.');
check(evidence.promotionRules.aiGeneratedFactsAllowed===false,'AI evidence must not be authoritative.');
for(const file of ['platform/ingestion/ingest-activity-evidence.mjs','platform/transforms/validate-activity-evidence.mjs'])check(fs.existsSync(file),`Missing activity evidence component: ${file}`);
for(const table of ['activity_families','activity_family_members','activity_family_facts'])check(new RegExp(`CREATE TABLE ${table} \\(`).test(familySql),`Missing activity family table: ${table}`);
check(family.rules.observationalFactsCannotReplaceMechanicalFacts===true,'Observed rates must not replace activity mechanics.');
check(family.rules.unclassifiedRecordsCannotBeRanked===true,'Unclassified activities must not be rankable.');
check(fs.existsSync('platform/transforms/build-activity-families.mjs'),'Missing activity family builder.');
for(const table of ['golden_activity_scenarios','golden_activity_contradictions','golden_activity_reviews'])check(new RegExp(`CREATE TABLE ${table} \\(`).test(goldenSql),`Missing golden activity table: ${table}`);
check(golden.approvalPolicy.automaticApprovalAllowed===false,'Golden vectors must not auto-approve.');
check(golden.approvalPolicy.approvedVectorMayOpenOnlyItsOwnScenario===true,'Golden approval scope must remain scenario-specific.');
check(fs.existsSync('platform/transforms/generate-golden-activity-vectors.mjs'),'Missing golden activity vector generator.');
check(fs.existsSync('platform/tests/golden-agility.test.mjs'),'Missing golden Agility regression test.');
check(fs.existsSync('platform/tests/golden-rooftop-agility.test.mjs'),'Missing golden rooftop Agility regression test.');
check(review.rules.generationDoesNotApprove===true,'Review packet generation must not approve vectors.');
for(const file of ['platform/ingestion/activity-evidence-lib.mjs','platform/ingestion/ingest-activity-family-evidence.mjs','platform/transforms/generate-golden-review-packets.mjs'])check(fs.existsSync(file),`Missing golden review component: ${file}`);
check(decision.rules.matchingVectorHashRequired===true&&decision.rules.appendOnly===true,'Review decisions must be hash-bound and append-only.');
for(const table of ['golden_review_decisions','recommendation_certificates','recommendation_certificate_inputs','recommendation_challenges'])check(new RegExp(`CREATE TABLE ${table} \\(`).test(certificateSql),`Missing recommendation certificate table: ${table}`);
check(certificate.rules.unknownEligibilityBlocksAbsoluteBest===true&&certificate.rules.unapprovedCandidateCannotWin===true,'Recommendation claims must fail closed.');
for(const file of ['platform/transforms/record-golden-review.mjs','platform/transforms/generate-recommendation-certificate.mjs','platform/tests/recommendation-certificate.test.mjs'])check(fs.existsSync(file),`Missing recommendation certificate component: ${file}`);
check(agilityTable.rules.tableRateIsPeakNotExpected===true&&agilityTable.rules.failureProneLevelRequiresSeparateModel===true,'Agility table assumptions must remain explicit.');
check(['minimum_level','xp_per_lap','cycle_ticks','observed_peak_xp_per_hour','source_revision'].every(x=>agilityTable.required.includes(x)),'Agility table contract must match emitted record fields.');
check(fs.existsSync('platform/ingestion/ingest-wiki-agility-course-table.mjs'),'Missing structured Agility course ingestion.');
check(fs.existsSync('platform/tests/agility-course-table.test.mjs'),'Missing structured Agility table regression test.');
if(failures.length){console.error(failures.map(x=>'FAIL: '+x).join('\n'));process.exit(1)}
console.log('V4 foundation checks passed: canonical schema, provenance, coverage, and calculation contracts.');
