import assert from 'node:assert/strict';
import fs from 'node:fs';
import { auditMemberIdentityAndAuthoritativeSourceChannelEvidenceWorkRoutes,buildMemberIdentityAndAuthoritativeSourceChannelEvidenceWorkRoutes,compileMemberIdentityAndAuthoritativeSourceChannelEvidenceWorkRoutingPolicy } from '../transforms/member-identity-and-authoritative-source-channel-evidence-work-routing-lib.mjs';

const policy=JSON.parse(fs.readFileSync('platform/policies/member-identity-and-authoritative-source-channel-evidence-work-routing-v1.json','utf8'));
const recordContract=JSON.parse(fs.readFileSync('platform/contracts/member-identity-and-authoritative-source-channel-evidence-work-routing-v1.json','utf8'));
const auditContract=JSON.parse(fs.readFileSync('platform/contracts/member-identity-and-authoritative-source-channel-evidence-work-routing-audit-v1.json','utf8'));
const domains=policy.requiredEvidenceDomains;

function input(key='alpha'){return {contract:policy.inputContract,memberCandidateKey:`member:${key}`,canonicalActivityIdentity:{canonicalActivityKey:`activity:${key}`,canonicalLabel:`Activity ${key}`},exactScopedIndependentRepeatabilityDisposition:{state:'blocked_no_resolved_exact_scoped_independent_repeatability_claim',repeatabilityVerdict:null,evidenceDomainAssessments:domains.map((domainKey,index)=>({domainKey,exactCandidateCount:0,reviewedMemberSubjectCount:0,dispositionClass:index===1?'reviewed_member_subject_prerequisite_missing':'no_exact_candidate_in_completed_defined_channels_not_negative_evidence',negativeGameFactEstablished:false,resolved:false,domainVerdict:null}))},exactScopedIndependentRepeatabilityNextEvidenceWork:{state:'required',routeKey:policy.inputRouteKey,routeState:policy.inputRouteState,requiredEvidenceDomains:domains,domainWorkItems:domains.map((domainKey,index)=>({domainKey,workKind:index===1?'reviewed_member_identity_expansion':'additional_authoritative_exact_scoped_source_channel_discovery',evidenceWorkComplete:false})),sameLineExactSubjectPredicateRequired:true,crossLineCrossSectionCrossPageAndCrossSourceJoinsAllowed:false,evidenceWorkComplete:false},memberExpansionReview:{state:'unreviewed'},mechanicsReview:{state:'unreviewed'},optimizerEligible:false,accountIndependent:true,blockers:['reviewed_member_identity_and_authoritative_source_channel_work_not_completed'],state:policy.inputState,contentHash:`disposition-${key}`}}

assert.equal(compileMemberIdentityAndAuthoritativeSourceChannelEvidenceWorkRoutingPolicy(policy).valid,true);
const first=input();const built=buildMemberIdentityAndAuthoritativeSourceChannelEvidenceWorkRoutes({dispositionRecords:[first],policy});
assert.equal(built.audit.publishable,true);assert.equal(built.audit.routingCoverageComplete,true);assert.equal(built.audit.routingCoverage.domainWorkItemCount,6);assert.equal(built.audit.routingCoverage.memberIdentityWorkItemCount,1);assert.equal(built.audit.routingCoverage.authoritativeSourceChannelWorkItemCount,5);assert.equal(built.audit.routingCoverage.blockedWorkItemCount,6);assert.equal(built.audit.routingCoverage.completedWorkItemCount,0);
const output=built.records[0],route=output.memberIdentityAndAuthoritativeSourceChannelEvidenceWorkRouting;assert.equal(route.memberIdentityWorkItemCount,1);assert.equal(route.authoritativeSourceChannelWorkItemCount,5);assert.equal(route.evidenceWorkComplete,false);assert.ok(route.domainEvidenceWorkItems.every(item=>item.evidenceKeys.length===0&&item.requireExactSameLineSubjectPredicateScope&&!item.crossLineCrossSectionCrossPageAndCrossSourceJoinAllowed&&!item.evidenceWorkComplete));assert.equal(output.optimizerEligible,false);for(const field of recordContract.required)assert.ok(Object.hasOwn(output,field),`Missing record field ${field}`);for(const field of auditContract.required)assert.ok(Object.hasOwn(built.audit,field),`Missing audit field ${field}`);

const multi=buildMemberIdentityAndAuthoritativeSourceChannelEvidenceWorkRoutes({dispositionRecords:[input('beta'),first],policy});assert.equal(multi.audit.publishable,true);assert.deepEqual(multi.records.map(record=>record.memberCandidateKey),['member:beta','member:alpha']);assert.equal(multi.audit.routingCoverage.domainWorkItemCount,12);assert.equal(multi.audit.routingCoverage.memberIdentityWorkItemCount,2);assert.equal(multi.audit.routingCoverage.authoritativeSourceChannelWorkItemCount,10);

const wrongKind=input();wrongKind.exactScopedIndependentRepeatabilityNextEvidenceWork.domainWorkItems[0].workKind='reviewed_member_identity_expansion';assert.equal(buildMemberIdentityAndAuthoritativeSourceChannelEvidenceWorkRoutes({dispositionRecords:[wrongKind],policy}).audit.publishable,false);
const candidatePresent=input();candidatePresent.exactScopedIndependentRepeatabilityDisposition.evidenceDomainAssessments[0].exactCandidateCount=1;assert.equal(buildMemberIdentityAndAuthoritativeSourceChannelEvidenceWorkRoutes({dispositionRecords:[candidatePresent],policy}).audit.publishable,false);

const missingDefinition=structuredClone(policy);missingDefinition.domainWorkDefinitions.pop();assert.equal(compileMemberIdentityAndAuthoritativeSourceChannelEvidenceWorkRoutingPolicy(missingDefinition).valid,false);
const swappedBranch=structuredClone(policy);swappedBranch.domainWorkDefinitions[0].branchKey='reviewed_member_identity_expansion';assert.equal(compileMemberIdentityAndAuthoritativeSourceChannelEvidenceWorkRoutingPolicy(swappedBranch).valid,false);
const specific=structuredClone(policy);specific.overrides={'member:alpha':true};assert.equal(compileMemberIdentityAndAuthoritativeSourceChannelEvidenceWorkRoutingPolicy(specific).valid,false);
const automatic=structuredClone(policy);automatic.rules.automaticVerificationAllowed=true;assert.equal(compileMemberIdentityAndAuthoritativeSourceChannelEvidenceWorkRoutingPolicy(automatic).valid,false);

const changed=structuredClone(built.records);changed[0].memberIdentityAndAuthoritativeSourceChannelEvidenceWorkRouting.domainEvidenceWorkItems[0].branchKey='reviewed_member_identity_expansion';assert.equal(auditMemberIdentityAndAuthoritativeSourceChannelEvidenceWorkRoutes(changed,{dispositionRecords:[first],policy}).publishable,false);
const promoted=structuredClone(built.records);promoted[0].memberIdentityAndAuthoritativeSourceChannelEvidenceWorkRouting.evidenceWorkComplete=true;promoted[0].optimizerEligible=true;const promotedAudit=auditMemberIdentityAndAuthoritativeSourceChannelEvidenceWorkRoutes(promoted,{dispositionRecords:[first],policy});assert.equal(promotedAudit.publishable,false);assert.ok(promotedAudit.blockers.includes('unsupported_repeatability_member_mechanics_or_optimizer_promotion'));
const account=structuredClone(built.records);account[0].currentBaseLevel=34;assert.equal(auditMemberIdentityAndAuthoritativeSourceChannelEvidenceWorkRoutes(account,{dispositionRecords:[first],policy}).publishable,false);
const deterministic=buildMemberIdentityAndAuthoritativeSourceChannelEvidenceWorkRoutes({dispositionRecords:[structuredClone(first)],policy:structuredClone(policy)});assert.deepEqual(deterministic,built);

console.log('Generic member-identity and authoritative source-channel evidence-work routing checks passed.');
