import assert from 'node:assert/strict';
import fs from 'node:fs';
import { hash } from '../ingestion/lib.mjs';
import { buildParentMemberInventoryEvidence } from '../ingestion/parent-member-inventory-evidence-lib.mjs';
import { auditParentMemberInventoryEvidenceDispositions,buildParentMemberInventoryEvidenceDispositions,compileParentMemberInventoryEvidenceDispositionPolicy } from '../transforms/parent-member-inventory-evidence-disposition-lib.mjs';

const evidencePolicy=JSON.parse(fs.readFileSync('platform/policies/parent-member-inventory-evidence-v1.json','utf8')),policy=JSON.parse(fs.readFileSync('platform/policies/parent-member-inventory-evidence-disposition-v1.json','utf8')),recordContract=JSON.parse(fs.readFileSync('platform/contracts/parent-member-inventory-evidence-disposition-v1.json','utf8')),auditContract=JSON.parse(fs.readFileSync('platform/contracts/parent-member-inventory-evidence-disposition-audit-v1.json','utf8'));
const sourceText=`{{Infobox Activity\n|name = Test tasks\n}}\nThe most common tasks are to fetch one of the following items (this list may not be exhaustive).\nThere are 4 tasks in total. {{CiteNews|quote=It is a list of about 4 entries.}}\n==Item delivery==\nThese make up approximately 50% of all tasks.\n{| class="wikitable"\n! Items\n|-\n|{{plink|First item}}||{{plink|Second item}}\n|}\n==Letter delivery==\nThese make up approximately 25% of all tasks.\n*[[First NPC]] in a place\n==A separate thing==\nThe NPC will occasionally ask the player to investigate [[A separate thing|it]]. This makes up approximately 25% of all tasks.`;
const wikiUrl=title=>`https://oldschool.runescape.wiki/w/${encodeURIComponent(title.replaceAll(' ','_'))}`;
function routingRecord({key='1',label='Test tasks',content=sourceText}={}){const sourceRevision=`40${key}`,sourcePageId=300+Number(key),sourcePageIdentity={sourcePageId,resolvedTitle:label,sourceRevision,sourceTimestamp:'2026-01-01T00:00:00Z',sourceUrl:wikiUrl(label),sourceContentHash:hash(content)};return {contract:evidencePolicy.inputContract,memberCandidateKey:`member:${key}`,canonicalActivityIdentity:{canonicalActivityKey:`activity:${key}`,canonicalLabel:label},canonicalActivitySubjectBinding:{canonicalActivityKey:`activity:${key}`,sourcePageIdentity,accountIndependent:true},canonicalActivityScopeEvidenceSources:[{sourcePageIdentity,exactRevisionSourceText:content}],canonicalActivityRepeatabilityEvidenceSources:[{sourcePageIdentity,exactRevisionSourceText:content}],memberIdentityAndAuthoritativeSourceChannelEvidenceWorkRouting:{routeState:'routed_blocked_member_identity_and_authoritative_source_channel_work_not_completed',memberIdentityWorkItemCount:1,authoritativeSourceChannelWorkItemCount:5,domainEvidenceWorkItems:[{domainKey:'member_task_reselection_and_repeatability',branchKey:evidencePolicy.inputBranchKey,inputWorkKind:evidencePolicy.inputWorkKind,evidenceWorkComplete:false,evidenceKeys:[],requireExactSameLineSubjectPredicateScope:true,crossLineCrossSectionCrossPageAndCrossSourceJoinAllowed:false}]},memberExpansionReview:{state:'unreviewed',memberKeys:[],evidenceKeys:[]},mechanicsReview:{state:'unreviewed',evidenceKeys:[]},optimizerEligible:false,accountIndependent:true,blockers:['member_identity_and_authoritative_source_channel_evidence_work_routed_not_completed'],state:evidencePolicy.inputState,contentHash:`route-${key}`}}
function fetchedPage(record,{content=sourceText}={}){const identity=record.canonicalActivitySubjectBinding.sourcePageIdentity;return {pageid:identity.sourcePageId,title:identity.resolvedTitle,revisions:[{revid:Number(identity.sourceRevision),timestamp:identity.sourceTimestamp,slots:{main:{content}}}]}}
function evidenceRecord(options={}){const route=routingRecord(options);return buildParentMemberInventoryEvidence({routingRecords:[route],fetchedPages:[fetchedPage(route,{content:options.content||sourceText})],policy:evidencePolicy,contentHash:hash}).records[0]}

const input=evidenceRecord(),built=buildParentMemberInventoryEvidenceDispositions({evidenceRecords:[input],policy,contentHash:hash});assert.equal(built.audit.publishable,true);assert.equal(built.audit.dispositionAttemptCoverageComplete,true);assert.equal(built.audit.memberCandidateClassificationComplete,true);assert.equal(built.audit.memberIdentityReviewComplete,false);assert.equal(built.audit.candidateCoverage.structuralCandidateCount,4);assert.equal(built.audit.candidateCoverage.itemDeliveryTargetCandidateCount,2);assert.equal(built.audit.candidateCoverage.messageDeliveryRecipientCandidateCount,1);assert.equal(built.audit.candidateCoverage.narrativeAssignedTaskClassCandidateCount,1);assert.equal(built.audit.boundaryCoverage.declaredTotalAssessmentCount,2);assert.equal(built.audit.boundaryCoverage.distributionAssessmentCount,3);assert.equal(built.audit.boundaryCoverage.nonExhaustiveQualificationAssessmentCount,1);assert.equal(built.audit.boundaryCoverage.arithmeticCountAlignmentObservedCount,1);assert.equal(built.audit.boundaryCoverage.arithmeticCompletenessProofCount,0);
const output=built.records[0],disposition=output.parentMemberInventoryDisposition;assert.equal(disposition.structuralCandidateCount,4);assert.equal(disposition.arithmeticAssessment.countAlignmentObserved,true);assert.equal(disposition.arithmeticAssessment.countAlignmentCanProveOneToOneMembership,false);assert.equal(disposition.arithmeticAssessment.countAlignmentCanProveInventoryCompleteness,false);assert.equal(disposition.memberUniverseComplete,false);assert.equal(disposition.memberIdentityVerdict,null);assert.equal(disposition.inventoryCompletenessVerdict,null);assert.equal(disposition.reviewedMemberIdentityCount,0);assert.equal(output.parentMemberInventoryDispositionReview.reviewedMemberIdentities.length,0);assert.equal(output.memberExpansionReview.state,'unreviewed');assert.equal(output.optimizerEligible,false);assert.ok(output.blockers.includes('source_inventory_non_exhaustive_qualification_prevents_completeness'));for(const field of recordContract.required)assert.ok(Object.hasOwn(output,field),`Missing required record field: ${field}`);for(const field of auditContract.required)assert.ok(Object.hasOwn(built.audit,field),`Missing required audit field: ${field}`);

const multi=evidenceRecord({key:'2',label:'Other tasks'}),multiBuilt=buildParentMemberInventoryEvidenceDispositions({evidenceRecords:[input,multi],policy,contentHash:hash});assert.equal(multiBuilt.audit.publishable,true);assert.equal(multiBuilt.records.length,2);
const noMatchText=sourceText.replace('==Item delivery==','==Unclassified section=='),unclassified=evidenceRecord({key:'3',label:'Unclassified tasks',content:noMatchText}),unclassifiedBuilt=buildParentMemberInventoryEvidenceDispositions({evidenceRecords:[unclassified],policy,contentHash:hash});assert.equal(unclassifiedBuilt.audit.publishable,true);assert.equal(unclassifiedBuilt.audit.memberCandidateClassificationComplete,false);assert.equal(unclassifiedBuilt.records[0].parentMemberInventoryDisposition.unclassifiedStructuralObservationCount,2);
const specific=structuredClone(policy);specific.overrides={'member:1':'complete'};assert.equal(buildParentMemberInventoryEvidenceDispositions({evidenceRecords:[input],policy:specific,contentHash:hash}).audit.publishable,false);
const automatic=structuredClone(policy);automatic.rules.automaticVerificationAllowed=true;assert.equal(buildParentMemberInventoryEvidenceDispositions({evidenceRecords:[input],policy:automatic,contentHash:hash}).audit.publishable,false);
const tamperedInput=structuredClone(input);tamperedInput.parentMemberInventoryEvidenceSources[0].structuralInventory.sourceLines[0].rawText='tampered';tamperedInput.contentHash=hash(tamperedInput);const tamperedBuilt=buildParentMemberInventoryEvidenceDispositions({evidenceRecords:[tamperedInput],policy,contentHash:hash});assert.equal(tamperedBuilt.audit.publishable,false);assert.ok(tamperedBuilt.audit.blockers.includes('one_or_more_input_inventory_evidence_packets_failed_exact_source_revalidation'));
const promoted=structuredClone(built.records);promoted[0].parentMemberInventoryDisposition.memberUniverseComplete=true;promoted[0].parentMemberInventoryDisposition.memberIdentityVerdict='complete';promoted[0].parentMemberInventoryDisposition.arithmeticAssessment.countAlignmentCanProveInventoryCompleteness=true;promoted[0].memberExpansionReview.state='reviewed';promoted[0].optimizerEligible=true;const promotedAudit=auditParentMemberInventoryEvidenceDispositions(promoted,{evidenceRecords:[input],policy,contentHash:hash});assert.equal(promotedAudit.publishable,false);assert.ok(promotedAudit.blockers.includes('inventory_disposition_created_unsupported_identity_completeness_repeatability_mechanics_or_optimizer_promotion'));
const accountScoped=structuredClone(built.records);accountScoped[0].currentBaseLevel=34;assert.equal(auditParentMemberInventoryEvidenceDispositions(accountScoped,{evidenceRecords:[input],policy,contentHash:hash}).publishable,false);
const deterministicA=buildParentMemberInventoryEvidenceDispositions({evidenceRecords:[input],policy,contentHash:hash}),deterministicB=buildParentMemberInventoryEvidenceDispositions({evidenceRecords:[structuredClone(input)],policy:structuredClone(policy),contentHash:hash});assert.deepEqual(deterministicA,deterministicB);
const compiled=compileParentMemberInventoryEvidenceDispositionPolicy(policy);assert.equal(compiled.valid,true);assert.deepEqual(compiled.invalidRules,[]);assert.deepEqual(compiled.forbiddenPolicyPaths,[]);assert.deepEqual(compiled.invalidDefinitions,[]);assert.deepEqual(compiled.duplicateDefinitionKeys,[]);
console.log('Generic parent/member inventory evidence disposition checks passed.');
