import assert from 'node:assert/strict';
import fs from 'node:fs';
import { hash } from '../ingestion/lib.mjs';
import { auditParentMemberInventoryEvidence,buildParentMemberInventoryEvidence,compileParentMemberInventoryEvidencePolicy,discoverParentMemberInventoryExactRevisionRequests } from '../ingestion/parent-member-inventory-evidence-lib.mjs';

const policy=JSON.parse(fs.readFileSync('platform/policies/parent-member-inventory-evidence-v1.json','utf8'));
const recordContract=JSON.parse(fs.readFileSync('platform/contracts/parent-member-inventory-evidence-v1.json','utf8'));
const auditContract=JSON.parse(fs.readFileSync('platform/contracts/parent-member-inventory-evidence-audit-v1.json','utf8'));
const wikiUrl=title=>`https://oldschool.runescape.wiki/w/${encodeURIComponent(title.replaceAll(' ','_'))}`;
const sourceText=`{{Infobox Activity\n|name = Test tasks\n}}\nAn NPC assigns tasks.\nThe following list may not be exhaustive.\nThere are 4 tasks in total. {{CiteNews|quote=about 4 entries}}\n==Items==\n{| class="wikitable"\n! Items\n|-\n|{{plink|First item}}||{{plink|Second item}}\n|}\n==Recipients==\n*[[First NPC]]\n==Narrative task==\nDo a separate thing.`;

function lineInventory(content){return content.split(/\r?\n/).map((rawText,index)=>({ordinal:index+1,sourceLocator:{lineStart:index+1,lineEnd:index+1},rawText,rawTextContentHash:hash(rawText)}))}
function routingRecord({key='1',label='Test tasks',content=sourceText}={}){const sourceRevision=`30${key}`,sourcePageId=200+Number(key),sourcePageIdentity={sourcePageId,resolvedTitle:label,sourceRevision,sourceTimestamp:'2026-01-01T00:00:00Z',sourceUrl:wikiUrl(label),sourceContentHash:hash(content)};return {contract:policy.inputContract,memberCandidateKey:`member:${key}`,canonicalActivityIdentity:{canonicalActivityKey:`activity:${key}`,canonicalLabel:label},canonicalActivitySubjectBinding:{canonicalActivityKey:`activity:${key}`,sourcePageIdentity,accountIndependent:true},canonicalActivityScopeEvidenceSources:[{sourcePageIdentity,exactRevisionSourceText:content,structuralInventory:{sourceLines:lineInventory(content)}}],canonicalActivityRepeatabilityEvidenceSources:[{sourcePageIdentity,exactRevisionSourceText:content,structuralInventory:{sourceLines:lineInventory(content)}}],memberIdentityAndAuthoritativeSourceChannelEvidenceWorkRouting:{routeState:'routed_blocked_member_identity_and_authoritative_source_channel_work_not_completed',memberIdentityWorkItemCount:1,authoritativeSourceChannelWorkItemCount:5,domainEvidenceWorkItems:[{domainKey:'parent_activity_post_completion_reassignment_or_restart',branchKey:'authoritative_exact_scoped_source_channel_expansion',inputWorkKind:'additional_authoritative_exact_scoped_source_channel_discovery',evidenceWorkComplete:false,evidenceKeys:[],requireExactSameLineSubjectPredicateScope:true,crossLineCrossSectionCrossPageAndCrossSourceJoinAllowed:false},{domainKey:'member_task_reselection_and_repeatability',branchKey:policy.inputBranchKey,inputWorkKind:policy.inputWorkKind,evidenceWorkComplete:false,evidenceKeys:[],requireExactSameLineSubjectPredicateScope:true,crossLineCrossSectionCrossPageAndCrossSourceJoinAllowed:false}]},memberExpansionReview:{state:'unreviewed',memberKeys:[],evidenceKeys:[]},mechanicsReview:{state:'unreviewed',evidenceKeys:[]},optimizerEligible:false,accountIndependent:true,blockers:['member_identity_and_authoritative_source_channel_evidence_work_routed_not_completed'],state:policy.inputState,contentHash:`route-${key}`}}
function fetchedPage(record,{content=sourceText,pageId,title,revision,timestamp}={}){const identity=record.canonicalActivitySubjectBinding.sourcePageIdentity;return {pageid:pageId??identity.sourcePageId,title:title??identity.resolvedTitle,revisions:[{revid:revision??Number(identity.sourceRevision),timestamp:timestamp??identity.sourceTimestamp,slots:{main:{content}}}]}}

const input=routingRecord(),fetched=[fetchedPage(input)];const requests=discoverParentMemberInventoryExactRevisionRequests([input],policy);assert.equal(requests.length,1);assert.equal(requests[0].sourceRevision,'301');
const built=buildParentMemberInventoryEvidence({routingRecords:[input],fetchedPages:fetched,policy,contentHash:hash});assert.equal(built.audit.publishable,true);assert.equal(built.audit.evidencePacketAttemptCoverageComplete,true);assert.equal(built.audit.inventoryEvidencePacketCoverageComplete,true);assert.equal(built.audit.memberIdentityReviewComplete,false);assert.equal(built.audit.observationCoverage.rootPlinkTemplateCount,2);assert.equal(built.audit.observationCoverage.bulletEntryCount,1);assert.equal(built.audit.observationCoverage.declaredTotalSignalCount,2);assert.equal(built.audit.observationCoverage.nonExhaustiveQualificationSignalCount,1);
const output=built.records[0];assert.equal(output.parentMemberInventoryEvidence.inventoryBoundaryState,'declared_total_and_non_exhaustive_qualification_observed_semantic_disposition_required');assert.equal(output.parentMemberInventoryEvidence.memberUniverseComplete,false);assert.equal(output.parentMemberInventoryEvidence.inventoryCompletenessVerdict,null);assert.equal(output.parentMemberInventoryEvidence.memberIdentityVerdict,null);assert.equal(output.parentMemberInventoryEvidence.reviewedMemberIdentityCount,0);assert.equal(output.parentMemberInventoryEvidenceSources[0].exactRevisionSourceText,sourceText);assert.equal(output.parentMemberInventoryEvidenceSources[0].structuralInventory.topLevelWikiTables[0].cellCount,3);assert.equal(output.memberExpansionReview.state,'unreviewed');assert.equal(output.optimizerEligible,false);for(const field of recordContract.required)assert.ok(Object.hasOwn(output,field),`Missing required record field: ${field}`);for(const field of auditContract.required)assert.ok(Object.hasOwn(built.audit,field),`Missing required audit field: ${field}`);

const multi=routingRecord({key:'2',label:'Other tasks'});const multiBuilt=buildParentMemberInventoryEvidence({routingRecords:[input,multi],fetchedPages:[fetchedPage(input),fetchedPage(multi)],policy,contentHash:hash});assert.equal(multiBuilt.audit.publishable,true);assert.equal(multiBuilt.records.length,2);
const wrong=buildParentMemberInventoryEvidence({routingRecords:[input],fetchedPages:[fetchedPage(input,{pageId:999})],policy,contentHash:hash});assert.equal(wrong.audit.publishable,true);assert.equal(wrong.audit.inventoryEvidencePacketCoverageComplete,false);
const missing=buildParentMemberInventoryEvidence({routingRecords:[input],fetchedPages:[],policy,contentHash:hash});assert.equal(missing.audit.publishable,false);assert.ok(missing.audit.blockers.includes('exact_parent_member_inventory_revision_fetch_set_mismatch'));
const stale=routingRecord({key:'3'});stale.canonicalActivityScopeEvidenceSources[0].exactRevisionSourceText='stale';stale.canonicalActivityRepeatabilityEvidenceSources[0].exactRevisionSourceText='stale';const staleBuilt=buildParentMemberInventoryEvidence({routingRecords:[stale],fetchedPages:[fetchedPage(stale,{revision:303})],policy,contentHash:hash});assert.equal(staleBuilt.audit.publishable,true);assert.equal(staleBuilt.audit.inventoryEvidencePacketCoverageComplete,false);
const specific=structuredClone(policy);specific.overrides={'member:1':'complete'};assert.equal(buildParentMemberInventoryEvidence({routingRecords:[input],fetchedPages:fetched,policy:specific,contentHash:hash}).audit.publishable,false);
const automatic=structuredClone(policy);automatic.rules.automaticVerificationAllowed=true;assert.equal(buildParentMemberInventoryEvidence({routingRecords:[input],fetchedPages:fetched,policy:automatic,contentHash:hash}).audit.publishable,false);
const promoted=structuredClone(built.records);promoted[0].parentMemberInventoryEvidence.memberUniverseComplete=true;promoted[0].parentMemberInventoryEvidence.memberIdentityVerdict='complete';promoted[0].memberExpansionReview.state='reviewed';promoted[0].optimizerEligible=true;const promotedAudit=auditParentMemberInventoryEvidence(promoted,{routingRecords:[input],fetchedPages:fetched,policy,contentHash:hash});assert.equal(promotedAudit.publishable,false);assert.ok(promotedAudit.blockers.includes('parent_member_inventory_evidence_created_unsupported_member_repeatability_mechanics_or_optimizer_promotion'));
const accountScoped=structuredClone(built.records);accountScoped[0].currentBaseLevel=34;assert.equal(auditParentMemberInventoryEvidence(accountScoped,{routingRecords:[input],fetchedPages:fetched,policy,contentHash:hash}).publishable,false);
const deterministicA=buildParentMemberInventoryEvidence({routingRecords:[input],fetchedPages:fetched,policy,contentHash:hash});const deterministicB=buildParentMemberInventoryEvidence({routingRecords:[structuredClone(input)],fetchedPages:structuredClone(fetched),policy:structuredClone(policy),contentHash:hash});assert.deepEqual(deterministicA,deterministicB);
const compiled=compileParentMemberInventoryEvidencePolicy(policy);assert.equal(compiled.valid,true);assert.deepEqual(compiled.invalidRules,[]);assert.deepEqual(compiled.invalidChannels,[]);assert.deepEqual(compiled.forbiddenPolicyPaths,[]);assert.deepEqual(compiled.invalidDefinitions,[]);assert.deepEqual(compiled.duplicateDefinitionKeys,[]);
console.log('Revision-pinned parent/member inventory evidence checks passed.');
