import {auditSkillProgressionCoverage} from '../transforms/skill-progression-coverage-lib.mjs';

const domain={skillKey:'agility',skill:'Agility',minimumBaseLevel:1,maximumBaseLevel:99,baseAndEffectiveLevelsSeparate:true,temporaryBoostsAffectEffectiveLevel:true,sourceRevision:'15321845',sourceTimestamp:'2026-08-27T06:12:04Z',sourceUrl:'https://oldschool.runescape.wiki/w/Skills',sourceLocator:{evidence:[{line:14,excerpt:'Players can advance a skill to level 99.'}]}};
const evaluation=level=>({phaseExitSatisfied:true,candidateUniverse:{total:level<10?1:2},byStatus:{condition_model_present:level<10?1:2},mechanicalReadiness:{readyForGoldenReview:level<10?1:2},blockingCandidates:0,details:[{candidateKey:'method:a',status:'condition_model_present',mechanicalReadiness:'ready_for_golden_review',blockers:[]},...(level<10?[]:[{candidateKey:'method:b',status:'condition_model_present',mechanicalReadiness:'ready_for_golden_review',blockers:[]}]) ]});
const failures=[],check=(condition,message)=>{if(!condition)failures.push(message)};
const incomplete=auditSkillProgressionCoverage({skillDomain:domain,methodUniverse:{complete:false,blockers:['complete_agility_method_universe_not_audited']},evaluateBaseLevel:evaluation});
check(incomplete.levelCoverage.evaluated===99&&incomplete.accountIndependent===true,'The audit must evaluate all 99 Agility base levels independently of an account snapshot.');
check(incomplete.fullSkillCoverageSatisfied===false&&incomplete.blockers.includes('complete_agility_method_universe_not_audited'),'Complete target models cannot overcome an incomplete candidate universe.');
check(incomplete.structuralBreakpoints.map(item=>item.baseLevel).join(',')==='1,10','Structural breakpoints must come from candidate changes rather than arbitrary level buckets.');
const complete=auditSkillProgressionCoverage({skillDomain:domain,methodUniverse:{complete:true,blockers:[]},performanceBreakpointCoverage:{complete:true,blockers:[]},evaluateBaseLevel:evaluation});
check(complete.fullSkillCoverageSatisfied===true&&complete.authoritativeClaimGate==='eligible_for_skill_wide_golden_review','A complete universe, every level model, and complete breakpoint coverage must satisfy the skill-wide gate.');
const dynamicBlocker=auditSkillProgressionCoverage({skillDomain:{...domain,maximumBaseLevel:3},methodUniverse:{complete:true,blockers:[]},performanceBreakpointCoverage:{complete:true,blockers:[]},evaluateBaseLevel:level=>({phaseExitSatisfied:false,blockingCandidates:1,details:[{candidateKey:'method:a',status:'target_condition_gap',blockers:[`failure_probability_at_base_level_${level}_not_published`]}]})});
check(dynamicBlocker.structuralBreakpoints.length===1&&dynamicBlocker.levelCoverage.modelBlocked===3,'A blocker that merely names the requested level must not create a fake breakpoint at every level.');
check(dynamicBlocker.embeddedQueryLevelDefects.length===0,'Correctly derived target-level blockers must not be treated as baked evidence.');
const baked=auditSkillProgressionCoverage({skillDomain:{...domain,maximumBaseLevel:3},methodUniverse:{complete:true,blockers:[]},performanceBreakpointCoverage:{complete:true,blockers:[]},evaluateBaseLevel:level=>({phaseExitSatisfied:false,blockingCandidates:1,details:[{candidateKey:'method:a',status:'target_condition_gap',blockers:['failure_probability_at_base_level_34_not_published']} ]})});
check(baked.embeddedQueryLevelDefects.length===3&&baked.blockers.includes('account_query_level_baked_into_reusable_evidence'),'A reusable record containing a foreign account-query level must be detected as an architectural defect.');
const invalid=auditSkillProgressionCoverage({skillDomain:{...domain,sourceRevision:null},methodUniverse:{complete:true,blockers:[]},performanceBreakpointCoverage:{complete:true,blockers:[]},evaluateBaseLevel:evaluation});
check(invalid.fullSkillCoverageSatisfied===false&&invalid.blockers.includes('revision_pinned_level_domain_evidence_missing'),'Unpinned level-domain evidence must fail closed before level evaluation.');
if(failures.length){console.error(failures.join('\n'));process.exit(1)}
console.log('Whole-skill progression coverage checks passed.');
