import assert from 'node:assert/strict';
import fs from 'node:fs';
import { hash } from '../ingestion/lib.mjs';
import {
  auditStructuralMemberCandidateReviewReadyIdentityAndRemainingGapWorkRoutes,
  buildStructuralMemberCandidateReviewReadyIdentityAndRemainingGapWorkRoutes,
  compileStructuralMemberCandidateReviewReadyIdentityAndRemainingGapWorkRoutingPolicy
} from '../transforms/structural-member-candidate-review-ready-identity-and-remaining-gap-work-routing-lib.mjs';

const policy=JSON.parse(fs.readFileSync('platform/policies/structural-member-candidate-review-ready-identity-and-remaining-gap-work-routing-v1.json','utf8'));
const recordContract=JSON.parse(fs.readFileSync('platform/contracts/structural-member-candidate-review-ready-identity-and-remaining-gap-work-routing-v1.json','utf8'));
const auditContract=JSON.parse(fs.readFileSync('platform/contracts/structural-member-candidate-review-ready-identity-and-remaining-gap-work-routing-audit-v1.json','utf8'));
const branches={identity:'reviewed_structural_candidate_member_identity_and_variant_scope_evidence',type:'unresolved_source_page_entity_type_evidence',relationship:'structural_parent_relationship_reconciliation_evidence',membership:'weighted_parent_task_entry_membership_evidence',mapping:'declared_total_one_to_one_member_mapping_evidence',universe:'complete_member_universe_reconciliation_evidence'};

function source(prefix){
  const text=`{{Infobox Item\n|name = Subject ${prefix}\n|id = 1\n}}`;
  return {sourceKey:`wiki-pageid:${prefix}|revision:100${prefix}`,roles:['candidate_subject_source'],contexts:[],sourcePageIdentity:{sourcePageId:Number(prefix),resolvedTitle:`Subject ${prefix}`,sourceRevision:`100${prefix}`,sourceTimestamp:'2026-01-01T00:00:00Z',sourceUrl:`https://oldschool.runescape.wiki/w/Subject_${prefix}`,sourceContentHash:hash(text),sourceContentBytes:Buffer.byteLength(text,'utf8')},exactRevisionSourceText:text,integrityChecks:{responseRevisionPresent:true,mainNamespace:true,pageIdMatches:true,revisionMatches:true,titleMatches:true,timestampMatches:true,exactTextPresent:true,contentHashMatches:true,contentBytesMatch:true,inputExactTextMatches:true,noSourceConflict:true},captureComplete:true,deficiencies:[],semanticVerdict:null,state:'complete_exact_revision_source_capture_non_verdict'};
}
function baseDisposition(key,branch,candidate=null){
  return {dispositionKey:`disposition:${key}:${branch}`,workItemKey:`work:${key}:${branch}`,branchKey:branch,workKind:`test_${branch}`,structuralCandidateKey:candidate,candidateRole:candidate?'item_delivery_target_candidate':null,sourceEvidenceKeys:['wiki-pageid:1|revision:1001'],packetIntegrity:{checks:{complete:true},complete:true},candidateMemberIdentityVerdict:null,sourcePageEntityTypeVerdict:null,structuralParentRelationshipVerdict:null,weightedTaskEntryMembershipVerdict:null,mappingVerdict:null,inventoryCompletenessVerdict:null,canonicalGameEntityIdentity:null,memberUniverseComplete:false,evidenceWorkComplete:false,automaticVerificationApplied:false,blockers:[],state:`blocked_${branch}_disposition`};
}
function identity(key,mode){
  const item=baseDisposition(key,branches.identity,`candidate:${key}`);
  const readiness={sourceEvidenceKey:'wiki-pageid:1|revision:1001',sourceIntegrity:{checks:{complete:true},complete:true},sourcePageIdentity:{sourcePageId:1,resolvedTitle:'Subject 1',sourceRevision:'1001'},sourcePageEntityTypes:mode==='nested'?[]:['item_page'],identityBearingSourcePageTypes:mode==='nested'?[]:['item_page'],supplementarySourcePageTypes:[],identityBearingRootTemplates:mode==='nested'?[]:[{template:'Infobox Item',line:1,parameterNames:['name','id'],numberedVariantIndices:mode==='multi'?[1,2]:[]}],infoboxNameFields:mode==='nested'?[]:[{name:'name',value:`Subject ${key}`}],numberedVariantIndices:mode==='multi'?[1,2]:[],multiVariantSeries:mode==='multi',structuralParentRelationshipState:'supported_source_structural_relationship_not_parent_membership_verdict',reviewReady:mode==='ready',blockers:mode==='ready'?[]:mode==='multi'?['multiple_numbered_entity_variants_require_exact_parent_variant_binding']:mode==='nested'?['candidate_source_page_type_unresolved','identity_bearing_root_infobox_not_exactly_one','identity_bearing_infobox_name_field_missing']:['structural_parent_relationship_unresolved']};
  return {...item,identityAndVariantScopeReviewReadiness:readiness,semanticDispositionState:mode==='ready'?'ready_for_source_bound_candidate_identity_review_no_verdict':'blocked_candidate_identity_review_readiness_evidence_gap',state:mode==='ready'?'review_ready_candidate_identity_and_variant_scope_no_verdict':'blocked_candidate_identity_and_variant_scope_disposition',blockers:readiness.blockers};
}
function inputRecord(prefix='1'){
  const identities=[identity(`${prefix}:ready`,'ready'),identity(`${prefix}:multi`,'multi'),identity(`${prefix}:nested`,'nested'),identity(`${prefix}:other`,'other')];
  const type=baseDisposition(`${prefix}:nested`,branches.type,`candidate:${prefix}:nested`);
  const relationship=baseDisposition(`${prefix}:other`,branches.relationship,`candidate:${prefix}:other`);
  const memberships=identities.map((item,index)=>baseDisposition(`${prefix}:membership:${index}`,branches.membership,item.structuralCandidateKey));
  const mapping=baseDisposition(`${prefix}:mapping`,branches.mapping);
  const universe=baseDisposition(`${prefix}:universe`,branches.universe);
  const dispositions=[...identities,type,relationship,...memberships,mapping,universe];
  const ready=identities.filter(item=>item.identityAndVariantScopeReviewReadiness.reviewReady);
  return {contract:policy.inputContract,memberCandidateKey:`member:${prefix}`,structuralMemberCandidateSemanticGapEvidenceSources:[source(prefix)],structuralMemberCandidateSemanticGapEvidenceDispositions:dispositions,structuralMemberCandidateSemanticGapEvidenceDisposition:{state:'generic_fail_closed_semantic_sufficiency_disposition_recorded_all_verdicts_closed',dispositionCount:dispositions.length,branchDispositionCounts:{[branches.identity]:4,[branches.type]:1,[branches.relationship]:1,[branches.membership]:4,[branches.mapping]:1,[branches.universe]:1},candidateIdentityDispositionCount:4,candidateIdentityReviewReadyCount:1,candidateIdentityReviewBlockedCount:3,multiVariantScopeBlockedCount:1,untypedOrNestedSubjectBindingBlockedCount:1,completedSemanticGapWorkItemCount:0,blockedSemanticGapWorkItemCount:dispositions.length,candidateMemberIdentityVerdictCount:0,sourcePageEntityTypeVerdictCount:0,structuralParentRelationshipVerdictCount:0,weightedTaskEntryMembershipVerdictCount:0,mappingVerdictCount:0,inventoryCompletenessVerdictCount:0,canonicalGameEntityIdentityCount:0,memberUniverseComplete:false,evidenceWorkComplete:false,automaticVerificationApplied:false},structuralMemberCandidateSemanticGapEvidenceDispositionReview:{state:'review_readiness_classified_final_semantic_decisions_pending',candidateIdentityReviewReadyDispositionKeys:ready.map(item=>item.dispositionKey),candidateIdentityReviewBlockedDispositionKeys:identities.filter(item=>!item.identityAndVariantScopeReviewReadiness.reviewReady).map(item=>item.dispositionKey),candidateMemberIdentityVerdict:null,sourcePageEntityTypeVerdict:null,structuralParentRelationshipVerdict:null,weightedTaskEntryMembershipVerdict:null,mappingVerdict:null,inventoryCompletenessVerdict:null,memberUniverseComplete:false,evidenceWorkComplete:false,automaticVerificationApplied:false},memberExpansionReview:{state:'unreviewed',memberKeys:[],evidenceKeys:[]},mechanicsReview:{state:'unreviewed',evidenceKeys:[]},optimizerEligible:false,accountIndependent:true,blockers:['structural_member_candidate_semantic_gap_evidence_disposition_recorded_final_reviews_not_completed'],state:policy.inputState,contentHash:`input-${prefix}`};
}

const input=inputRecord(),compiled=compileStructuralMemberCandidateReviewReadyIdentityAndRemainingGapWorkRoutingPolicy(policy);
assert.equal(compiled.valid,true);assert.deepEqual(compiled.invalidRules,[]);assert.deepEqual(compiled.invalidRoutes,[]);assert.deepEqual(compiled.duplicateRouteKeys,[]);assert.deepEqual(compiled.forbiddenPolicyPaths,[]);
const built=buildStructuralMemberCandidateReviewReadyIdentityAndRemainingGapWorkRoutes({dispositionRecords:[input],policy});
assert.equal(built.audit.publishable,true);assert.equal(built.audit.routingCoverageComplete,true);assert.equal(built.audit.sourceIntegrityCoverage.completeSourceCount,1);assert.equal(built.audit.routingCoverage.inputDispositionCount,12);assert.equal(built.audit.routingCoverage.totalWorkItemCount,11);assert.equal(built.audit.routingCoverage.reviewReadyIdentityWorkItemCount,1);assert.equal(built.audit.routingCoverage.multiVariantIdentityWorkItemCount,1);assert.equal(built.audit.routingCoverage.nestedSubjectBindingWorkItemCount,1);assert.equal(built.audit.routingCoverage.mergedNestedSubjectWorkItemCount,1);assert.equal(built.audit.routingCoverage.otherIdentityGapWorkItemCount,1);assert.equal(built.audit.routingCoverage.structuralRelationshipGapWorkItemCount,1);assert.equal(built.audit.routingCoverage.weightedMembershipWorkItemCount,4);assert.equal(built.audit.routingCoverage.declaredTotalMappingWorkItemCount,1);assert.equal(built.audit.routingCoverage.completeUniverseWorkItemCount,1);assert.equal(built.audit.dispositionReferenceCoverage.sourceDispositionReferenceCount,12);assert.equal(built.audit.dispositionReferenceCoverage.uniqueSourceDispositionReferenceCount,12);assert.deepEqual(built.audit.dispositionReferenceCoverage.duplicateReferenceKeys,[]);assert.deepEqual(built.audit.dispositionReferenceCoverage.missingDispositionReferences,[]);
const output=built.records[0],route=output.structuralMemberCandidateReviewReadyIdentityAndRemainingGapWorkRouting;
assert.equal(route.reviewReadyIdentityWorkItems[0].reviewReady,true);assert.equal(route.reviewReadyIdentityWorkItems[0].reviewDecision,null);assert.equal(route.reviewReadyIdentityWorkItems[0].candidateMemberIdentityVerdict,null);assert.equal(route.multiVariantIdentityWorkItems[0].routeKey,policy.routes.multiVariantIdentity.routeKey);assert.equal(route.nestedSubjectBindingWorkItems[0].sourceDispositionKeys.length,2);assert.equal(route.nestedSubjectBindingWorkItems[0].mergedNestedIdentityAndPageTypeDispositions,true);assert.equal(route.totalWorkItemCount,11);assert.equal(route.sourceDispositionReferenceCount,12);assert.equal(route.uniqueSourceDispositionReferenceCount,12);assert.equal(route.completedWorkItemCount,0);assert.equal(route.reviewDecisionCount,0);assert.equal(route.semanticVerdictCount,0);assert.equal(route.evidenceWorkComplete,false);assert.equal(output.memberExpansionReview.state,'unreviewed');assert.equal(output.mechanicsReview.state,'unreviewed');assert.equal(output.optimizerEligible,false);
for(const field of recordContract.required)assert.ok(Object.hasOwn(output,field),`Missing required record field: ${field}`);for(const field of auditContract.required)assert.ok(Object.hasOwn(built.audit,field),`Missing required audit field: ${field}`);

const multi=buildStructuralMemberCandidateReviewReadyIdentityAndRemainingGapWorkRoutes({dispositionRecords:[input,inputRecord('2')],policy});assert.equal(multi.audit.publishable,true);assert.equal(multi.records.length,2);assert.equal(multi.audit.routingCoverage.inputDispositionCount,24);assert.equal(multi.audit.routingCoverage.totalWorkItemCount,22);
const specific=structuredClone(policy);specific.overrides={'candidate:1':'reviewed'};assert.equal(compileStructuralMemberCandidateReviewReadyIdentityAndRemainingGapWorkRoutingPolicy(specific).valid,false);
const automatic=structuredClone(policy);automatic.rules.automaticVerificationAllowed=true;assert.equal(compileStructuralMemberCandidateReviewReadyIdentityAndRemainingGapWorkRoutingPolicy(automatic).valid,false);
const duplicated=structuredClone(built.records);duplicated[0].structuralMemberCandidateReviewReadyIdentityAndRemainingGapWorkRouting.weightedMembershipWorkItems[0].sourceDispositionKeys=[route.reviewReadyIdentityWorkItems[0].sourceDispositionKeys[0]];let audit=auditStructuralMemberCandidateReviewReadyIdentityAndRemainingGapWorkRoutes(duplicated,{dispositionRecords:[input],policy});assert.equal(audit.publishable,false);assert.ok(audit.blockers.includes('input_disposition_reference_coverage_not_exactly_once'));
const badMerge=structuredClone(built.records);badMerge[0].structuralMemberCandidateReviewReadyIdentityAndRemainingGapWorkRouting.nestedSubjectBindingWorkItems[0].sourceDispositionKeys=[route.reviewReadyIdentityWorkItems[0].sourceDispositionKeys[0],route.nestedSubjectBindingWorkItems[0].sourceDispositionKeys[1]];audit=auditStructuralMemberCandidateReviewReadyIdentityAndRemainingGapWorkRoutes(badMerge,{dispositionRecords:[input],policy});assert.equal(audit.publishable,false);assert.ok(audit.blockers.includes('merged_nested_subject_work_does_not_bind_exactly_one_identity_and_page_type_disposition_for_same_candidate'));
const branchSwapped=structuredClone(built.records);branchSwapped[0].structuralMemberCandidateReviewReadyIdentityAndRemainingGapWorkRouting.multiVariantIdentityWorkItems[0].routeKey=policy.routes.reviewReadyIdentity.routeKey;branchSwapped[0].structuralMemberCandidateReviewReadyIdentityAndRemainingGapWorkRouting.multiVariantIdentityWorkItems[0].workKind=policy.routes.reviewReadyIdentity.workKind;audit=auditStructuralMemberCandidateReviewReadyIdentityAndRemainingGapWorkRoutes(branchSwapped,{dispositionRecords:[input],policy});assert.equal(audit.publishable,false);assert.ok(audit.blockers.includes('one_or_more_work_items_do_not_match_semantic_route_conditions'));
const promoted=structuredClone(built.records);promoted[0].structuralMemberCandidateReviewReadyIdentityAndRemainingGapWorkRouting.reviewReadyIdentityWorkItems[0].reviewDecision='approved';promoted[0].structuralMemberCandidateReviewReadyIdentityAndRemainingGapWorkRouting.reviewReadyIdentityWorkItems[0].candidateMemberIdentityVerdict='verified';promoted[0].structuralMemberCandidateReviewReadyIdentityAndRemainingGapWorkRouting.reviewDecisionCount=1;promoted[0].optimizerEligible=true;audit=auditStructuralMemberCandidateReviewReadyIdentityAndRemainingGapWorkRoutes(promoted,{dispositionRecords:[input],policy});assert.equal(audit.publishable,false);assert.ok(audit.blockers.includes('routing_created_unsupported_review_identity_membership_completeness_mechanics_or_optimizer_promotion'));
const accountScoped=structuredClone(built.records);accountScoped[0].currentBaseLevel=34;assert.equal(auditStructuralMemberCandidateReviewReadyIdentityAndRemainingGapWorkRoutes(accountScoped,{dispositionRecords:[input],policy}).publishable,false);
const deterministic=buildStructuralMemberCandidateReviewReadyIdentityAndRemainingGapWorkRoutes({dispositionRecords:[structuredClone(input)],policy:structuredClone(policy)});assert.deepEqual(deterministic,built);
console.log('Generic structural member candidate review-ready identity and remaining-gap work routing checks passed.');
