import assert from 'node:assert/strict';
import fs from 'node:fs';
import { hash } from '../ingestion/lib.mjs';
import { auditStructuralMemberCandidateIdentityReviewPacketMaterialization,buildStructuralMemberCandidateIdentityReviewPackets,compileStructuralMemberCandidateIdentityReviewPacketMaterializationPolicy } from '../transforms/structural-member-candidate-identity-review-packet-materialization-lib.mjs';

const policy=JSON.parse(fs.readFileSync('platform/policies/structural-member-candidate-identity-review-packet-materialization-v1.json','utf8'));
const recordContract=JSON.parse(fs.readFileSync('platform/contracts/structural-member-candidate-identity-review-packets-v1.json','utf8'));
const auditContract=JSON.parse(fs.readFileSync('platform/contracts/structural-member-candidate-identity-review-packet-materialization-audit-v1.json','utf8'));

function exactSource(sourceKey,pageId,revision,title,text,roles){return {sourceKey,roles,contexts:[],sourcePageIdentity:{sourcePageId:pageId,resolvedTitle:title,sourceRevision:revision,sourceTimestamp:'2026-01-01T00:00:00Z',sourceUrl:`https://oldschool.runescape.wiki/w/${title.replaceAll(' ','_')}`,sourceContentHash:hash(text),sourceContentBytes:Buffer.byteLength(text,'utf8')},exactRevisionSourceText:text,rootTemplateSignatures:[],templateNameObservations:[],integrityChecks:{responseRevisionPresent:true,mainNamespace:true,pageIdMatches:true,revisionMatches:true,titleMatches:true,timestampMatches:true,exactTextPresent:true,contentHashMatches:true,contentBytesMatch:true,inputExactTextMatches:true,noSourceConflict:true},captureComplete:true,deficiencies:[],semanticVerdict:null,state:'complete_exact_revision_source_capture_non_verdict'};}
function inputRecord(prefix='1'){
  const candidateKey=`candidate:${prefix}`,subjectKey=`wiki-pageid:${100+Number(prefix)}|revision:${200+Number(prefix)}`,parentKey=`wiki-pageid:${300+Number(prefix)}|revision:${400+Number(prefix)}`,subjectText=`{{Infobox Item\n|name = Subject ${prefix}\n|id = ${prefix}\n}}\nLead.`,parentOccurrence=`{{plink|Subject ${prefix}}}`,parentText=`Lead.\n${parentOccurrence}\nEnd.`,subject=exactSource(subjectKey,100+Number(prefix),String(200+Number(prefix)),`Subject ${prefix}`,subjectText,['candidate_subject_source']),parent=exactSource(parentKey,300+Number(prefix),String(400+Number(prefix)),`Parent ${prefix}`,parentText,['parent_inventory_source']);
  const identity={resolvedTitle:`Subject ${prefix}`,sourceContentBytes:Buffer.byteLength(subjectText,'utf8'),sourceContentHash:hash(subjectText),sourcePageId:100+Number(prefix),sourceRevision:String(200+Number(prefix)),sourceTimestamp:'2026-01-01T00:00:00Z',sourceUrl:`https://oldschool.runescape.wiki/w/Subject_${prefix}`};
  const candidate={dispositionKey:`candidate-disposition:${prefix}`,workItemKey:`candidate-work:${prefix}`,structuralCandidateKey:candidateKey,candidateRole:'item_delivery_target_candidate',sourceEvidenceKey:`candidate-source:${prefix}`,sourcePageIdentity:identity,evidenceIntegrity:{checks:{complete:true},complete:true},stableSourcePageSubjectIdentity:{state:'supported_revision_pinned_source_page_subject_identity',supported:true,evidenceKey:`candidate-source:${prefix}`},sourcePageEntityType:{state:'typed',entityTypes:['item_page'],evidence:[],classified:true,canonicalGameEntityIdentity:null},structuralParentRelationship:{state:'supported_source_structural_relationship_not_parent_membership_verdict',relationshipClass:'source_lists_subject_as_item_delivery_target',requiredSourcePageTypes:['item_page'],missingRequiredSourcePageTypes:[],roleTypeCoherenceState:'supported_required_source_page_type_present',supported:true,parentMembershipVerdict:null,weightedTaskEntryMembershipVerdict:null,evidence:{candidateRole:'item_delivery_target_candidate',sourceCandidateEvidence:{exactSourceText:parentOccurrence,exactSourceTextContentHash:hash(parentOccurrence),sourceContentHash:hash(parentText),sourceLocator:{lineStart:2,lineEnd:2,columnStart:1,columnEnd:parentOccurrence.length},sourcePageId:parent.sourcePageIdentity.sourcePageId,sourceRevision:parent.sourcePageIdentity.sourceRevision}}},candidateMemberIdentityVerdict:null,parentMembershipVerdict:null,oneToOneTaskEntryMappingVerdict:null,inventoryCompletenessVerdict:null,memberUniverseComplete:false,repeatabilityVerdict:null,canonicalGameEntityIdentity:null,automaticVerificationApplied:false,state:'reviewed_generic_source_identity_page_type_and_structural_parent_relation_disposition_gates_closed'};
  const semanticDispositionKey=`semantic-disposition:${prefix}`,readiness={sourceEvidenceKey:subjectKey,sourceIntegrity:{checks:{complete:true},complete:true},sourcePageIdentity:identity,sourcePageEntityTypes:['item_page'],identityBearingSourcePageTypes:['item_page'],supplementarySourcePageTypes:[],identityBearingRootTemplates:[{template:'Infobox Item',line:1,parameterNames:['name','id'],numberedVariantIndices:[]}],infoboxNameFields:[{name:'name',value:`Subject ${prefix}`}],numberedVariantIndices:[],multiVariantSeries:false,structuralParentRelationshipState:'supported_source_structural_relationship_not_parent_membership_verdict',reviewReady:true,blockers:[]};
  const semanticDisposition={dispositionKey:semanticDispositionKey,workItemKey:`semantic-work:${prefix}`,branchKey:'reviewed_structural_candidate_member_identity_and_variant_scope_evidence',workKind:'revision_pinned_candidate_member_identity_and_variant_scope_evidence',structuralCandidateKey:candidateKey,candidateRole:'item_delivery_target_candidate',sourceEvidenceKeys:[subjectKey,parentKey],packetIntegrity:{checks:{complete:true},complete:true},identityAndVariantScopeReviewReadiness:readiness,semanticDispositionState:'ready_for_source_bound_candidate_identity_review_no_verdict',blockers:[],candidateMemberIdentityVerdict:null,sourcePageEntityTypeVerdict:null,structuralParentRelationshipVerdict:null,weightedTaskEntryMembershipVerdict:null,mappingVerdict:null,inventoryCompletenessVerdict:null,canonicalGameEntityIdentity:null,memberUniverseComplete:false,evidenceWorkComplete:false,automaticVerificationApplied:false,state:'review_ready_candidate_identity_and_variant_scope_no_verdict'};
  const reviewWorkItem={workItemKey:`${semanticDispositionKey}|work-route|source_bound_candidate_identity_review`,routeKey:policy.reviewRouteKey,workKind:'source_bound_candidate_identity_and_exact_variant_scope_review',structuralCandidateKey:candidateKey,candidateRole:'item_delivery_target_candidate',sourceDispositionKeys:[semanticDispositionKey],sourceDispositionStates:[{dispositionKey:semanticDispositionKey,state:semanticDisposition.state}],sourceEvidenceKeys:[subjectKey,parentKey],requiredChannels:['exact_revision_subject_infobox','source_authored_identity_name','candidate_role_type_and_parent_relation','explicit_source_bound_identity_review_decision'],identityAndVariantScopeReviewReadiness:readiness,reviewReady:true,mergedNestedIdentityAndPageTypeDispositions:false,newEvidenceKeys:[],reviewDecision:null,candidateMemberIdentityVerdict:null,sourcePageEntityTypeVerdict:null,structuralParentRelationshipVerdict:null,weightedTaskEntryMembershipVerdict:null,mappingVerdict:null,inventoryCompletenessVerdict:null,canonicalGameEntityIdentity:null,memberUniverseComplete:false,evidenceWorkComplete:false,automaticVerificationApplied:false,workState:'pending_explicit_source_bound_identity_review_no_verdict'};
  return {contract:policy.inputContract,memberCandidateKey:`member:${prefix}`,structuralMemberCandidateSemanticGapEvidenceSources:[subject,parent],structuralMemberCandidateIdentityDispositions:[candidate],structuralMemberCandidateSemanticGapEvidenceDispositions:[semanticDisposition],structuralMemberCandidateReviewReadyIdentityAndRemainingGapWorkRouting:{routeState:'review_ready_identities_and_remaining_semantic_gaps_routed_all_verdicts_closed',reviewReadyIdentityWorkItems:[reviewWorkItem],multiVariantIdentityWorkItems:[],nestedSubjectBindingWorkItems:[],otherIdentityGapWorkItems:[],structuralRelationshipGapWorkItems:[],weightedMembershipWorkItems:[],declaredTotalMappingWorkItems:[],completeUniverseWorkItems:[],inputDispositionCount:1,reviewReadyIdentityWorkItemCount:1,multiVariantIdentityWorkItemCount:0,nestedSubjectBindingWorkItemCount:0,mergedNestedSubjectWorkItemCount:0,otherIdentityGapWorkItemCount:0,structuralRelationshipGapWorkItemCount:0,weightedMembershipWorkItemCount:0,declaredTotalMappingWorkItemCount:0,completeUniverseWorkItemCount:0,totalWorkItemCount:1,sourceDispositionReferenceCount:1,uniqueSourceDispositionReferenceCount:1,existingEvidenceReferenceCount:2,newEvidenceKeyCount:0,completedWorkItemCount:0,reviewDecisionCount:0,semanticVerdictCount:0,candidateIdentityRelationshipMembershipMappingAndUniverseBranchesSeparated:true,identityReviewComplete:false,memberUniverseComplete:false,evidenceWorkComplete:false,automaticVerificationApplied:false},memberExpansionReview:{state:'unreviewed',memberKeys:[],evidenceKeys:[]},mechanicsReview:{state:'unreviewed',evidenceKeys:[]},optimizerEligible:false,accountIndependent:true,blockers:['source_bound_candidate_identity_reviews_pending'],state:policy.inputState,contentHash:`route-${prefix}`};
}

const input=inputRecord(),compiled=compileStructuralMemberCandidateIdentityReviewPacketMaterializationPolicy(policy);assert.equal(compiled.valid,true);assert.equal(compiled.contractValid,true);assert.equal(compiled.decisionsValid,true);assert.deepEqual(compiled.invalidRules,[]);assert.deepEqual(compiled.forbiddenPolicyPaths,[]);
const built=buildStructuralMemberCandidateIdentityReviewPackets({routingRecords:[input],policy});assert.equal(built.audit.publishable,true);assert.equal(built.audit.reviewPacketMaterializationComplete,true);assert.equal(built.audit.identityReviewComplete,false);assert.equal(built.audit.reviewPacketCoverage.reviewReadyWorkItemCount,1);assert.equal(built.audit.reviewPacketCoverage.reviewPacketCount,1);assert.equal(built.audit.reviewPacketCoverage.completePacketCount,1);assert.equal(built.audit.reviewEvidenceCoverage.subjectRootInfoboxEvidenceCount,1);assert.equal(built.audit.reviewEvidenceCoverage.parentOccurrenceEvidenceCount,1);assert.equal(built.audit.reviewEvidenceCoverage.exactCandidateDispositionMatchCount,1);
const output=built.records[0],packet=output.structuralMemberCandidateIdentityReviewPackets[0],summary=output.structuralMemberCandidateIdentityReviewPacketMaterialization;assert.equal(packet.subjectEvidence.rootInfobox.exactSourceText,'{{Infobox Item\n|name = Subject 1\n|id = 1\n}}');assert.equal(packet.parentOccurrenceEvidence.exactSourceText,'{{plink|Subject 1}}');assert.equal(packet.parentOccurrenceEvidence.sourceLocator.lineStart,2);assert.equal(packet.packetMaterializationComplete,true);assert.equal(packet.eligibleForSourceBoundReview,true);assert.equal(packet.decision,null);assert.equal(packet.reviewer,null);assert.equal(packet.candidateMemberIdentityVerdict,null);assert.ok(packet.reviewScope.confirmationDoesNotProve.includes('weighted_parent_membership'));assert.ok(packet.reviewScope.confirmationDoesNotProve.includes('optimizer_eligibility'));assert.equal(summary.reviewPacketCount,1);assert.equal(summary.reviewPacketMaterializationComplete,true);assert.equal(summary.identityReviewComplete,false);assert.equal(output.memberExpansionReview.state,'unreviewed');assert.equal(output.optimizerEligible,false);for(const field of recordContract.required)assert.ok(Object.hasOwn(output,field),`Missing record field ${field}`);for(const field of auditContract.required)assert.ok(Object.hasOwn(built.audit,field),`Missing audit field ${field}`);

const multi=buildStructuralMemberCandidateIdentityReviewPackets({routingRecords:[input,inputRecord('2')],policy});assert.equal(multi.audit.publishable,true);assert.equal(multi.records.length,2);assert.equal(multi.audit.reviewPacketCoverage.reviewPacketCount,2);
const specific=structuredClone(policy);specific.overrides={'candidate:1':'confirmed'};assert.equal(compileStructuralMemberCandidateIdentityReviewPacketMaterializationPolicy(specific).valid,false);
const automatic=structuredClone(policy);automatic.rules.automaticVerificationAllowed=true;assert.equal(compileStructuralMemberCandidateIdentityReviewPacketMaterializationPolicy(automatic).valid,false);
const sourceChanged=structuredClone(input);sourceChanged.structuralMemberCandidateSemanticGapEvidenceSources[0].exactRevisionSourceText+=' changed';let failed=buildStructuralMemberCandidateIdentityReviewPackets({routingRecords:[sourceChanged],policy});assert.equal(failed.audit.publishable,false);assert.ok(failed.audit.blockers.includes('one_or_more_exact_revision_sources_failed_revalidation'));
const parentChanged=structuredClone(input);parentChanged.structuralMemberCandidateIdentityDispositions[0].structuralParentRelationship.evidence.sourceCandidateEvidence.exactSourceText='{{plink|Different}}';failed=buildStructuralMemberCandidateIdentityReviewPackets({routingRecords:[parentChanged],policy});assert.equal(failed.audit.publishable,false);assert.ok(failed.audit.blockers.includes('one_or_more_source_bound_identity_review_packets_invalid_or_incomplete'));
const duplicate=structuredClone(built.records);duplicate[0].structuralMemberCandidateIdentityReviewPackets.push(structuredClone(packet));let audit=auditStructuralMemberCandidateIdentityReviewPacketMaterialization(duplicate,{routingRecords:[input],policy});assert.equal(audit.publishable,false);assert.ok(audit.blockers.includes('review_work_item_and_packet_sets_do_not_match_exactly'));
const promoted=structuredClone(built.records);promoted[0].structuralMemberCandidateIdentityReviewPackets[0].decision=policy.allowedDecisions[0];promoted[0].structuralMemberCandidateIdentityReviewPackets[0].reviewer='automatic';promoted[0].structuralMemberCandidateIdentityReviewPackets[0].candidateMemberIdentityVerdict='verified';promoted[0].structuralMemberCandidateIdentityReviewPacketMaterialization.decisionCount=1;promoted[0].optimizerEligible=true;audit=auditStructuralMemberCandidateIdentityReviewPacketMaterialization(promoted,{routingRecords:[input],policy});assert.equal(audit.publishable,false);assert.ok(audit.blockers.includes('packet_generation_created_unsupported_review_identity_membership_completeness_mechanics_or_optimizer_promotion'));
const accountScoped=structuredClone(built.records);accountScoped[0].currentBaseLevel=34;assert.equal(auditStructuralMemberCandidateIdentityReviewPacketMaterialization(accountScoped,{routingRecords:[input],policy}).publishable,false);
const deterministic=buildStructuralMemberCandidateIdentityReviewPackets({routingRecords:[structuredClone(input)],policy:structuredClone(policy)});assert.deepEqual(deterministic,built);
console.log('Structural member candidate source-bound identity review packet materialization checks passed.');
