import assert from 'node:assert/strict';
import fs from 'node:fs';
import { hash } from '../ingestion/lib.mjs';
import {
  auditStructuralMemberCandidateSemanticGapEvidenceDispositions,
  buildStructuralMemberCandidateSemanticGapEvidenceDispositions,
  compileStructuralMemberCandidateSemanticGapEvidenceDispositionPolicy
} from '../transforms/structural-member-candidate-semantic-gap-evidence-disposition-lib.mjs';

const policy=JSON.parse(fs.readFileSync('platform/policies/structural-member-candidate-semantic-gap-evidence-disposition-v1.json','utf8'));
const entityTypePolicy=JSON.parse(fs.readFileSync('platform/policies/unlock-linked-page-entity-type-v2.json','utf8'));
const recordContract=JSON.parse(fs.readFileSync('platform/contracts/structural-member-candidate-semantic-gap-evidence-disposition-v1.json','utf8'));
const auditContract=JSON.parse(fs.readFileSync('platform/contracts/structural-member-candidate-semantic-gap-evidence-disposition-audit-v1.json','utf8'));
const texts={parent:'A parent source.',simple:'{{Infobox Item\n|name = Simple item\n|id = 1\n}}',multi:'{{Infobox Item\n|version1 = Normal\n|version2 = Poisoned\n|name1 = Multi item\n|name2 = Multi item(p)\n|id1 = 2\n|id2 = 3\n}}',nested:'{{Switch infobox\n|text1 = {{Infobox Monster\n|name = Nested subject\n}}\n|text2 = {{Infobox NPC\n|name = Nested subject\n}}\n}}'};
const identity=(id,title,revision,text)=>({sourcePageId:id,resolvedTitle:title,sourceRevision:String(revision),sourceTimestamp:`2026-01-${String(id).padStart(2,'0')}T00:00:00Z`,sourceUrl:`https://oldschool.runescape.wiki/w/${title.replaceAll(' ','_')}`,sourceContentHash:hash(text),sourceContentBytes:Buffer.byteLength(text,'utf8')});
const identities={parent:identity(1,'Parent',1001,texts.parent),simple:identity(2,'Simple item',1002,texts.simple),multi:identity(3,'Multi item',1003,texts.multi),nested:identity(4,'Nested subject',1004,texts.nested)};
const candidates=[{key:'simple',identity:identities.simple,type:{state:'typed',entityTypes:['item_page'],classified:true}},{key:'multi',identity:identities.multi,type:{state:'typed',entityTypes:['item_page'],classified:true}},{key:'nested',identity:identities.nested,type:{state:'untyped',entityTypes:[],classified:false}}];
const channels={identity:['exact_subject_declaration','variant_and_multi_type_scope','source_role_to_subject_binding','reviewed_member_identity_decision'],type:['variant_container_structure','nested_subject_variant_binding','exact_top_level_subject_scope','reviewed_source_page_type_decision'],membership:['explicit_weighted_entry_membership','parent_selection_scope','duplicate_alias_and_variant_treatment','reviewed_weighted_membership_decision'],mapping:['explicit_parent_member_mapping','declared_total_scope_and_revision','duplicate_alias_and_variant_treatment','one_to_one_mapping_review'],universe:['complete_parent_member_enumeration','source_limitation_reconciliation','independent_authoritative_coverage_check','complete_universe_review']};
function source(key,role){const sourceIdentity=identities[key],text=texts[key];return {sourceKey:`wiki-pageid:${sourceIdentity.sourcePageId}|revision:${sourceIdentity.sourceRevision}`,roles:[role],contexts:[],sourcePageIdentity:sourceIdentity,exactRevisionSourceText:text,rootTemplateSignatures:[],templateNameObservations:[],integrityChecks:{responseRevisionPresent:true,mainNamespace:true,pageIdMatches:true,revisionMatches:true,titleMatches:true,timestampMatches:true,exactTextPresent:true,contentHashMatches:true,contentBytesMatch:true,inputExactTextMatches:true,noSourceConflict:true},captureComplete:true,deficiencies:[],semanticVerdict:null,state:'complete_exact_revision_source_capture_non_verdict'};}
function channelObservations(required){return required.map(channel=>({channel,captureState:channel.endsWith('_decision')||channel.endsWith('_review')?'review_decision_pending':'revision_pinned_observation_available_semantic_review_required',sourceEvidenceKeys:['wiki-pageid:1|revision:1001'],observationCaptured:true,sufficientForSemanticVerdict:false,semanticVerdict:null,evidence:{}}));}
function packet(key,branch,required,candidate=null){const sourceEvidenceKeys=candidate?[`wiki-pageid:${candidate.identity.sourcePageId}|revision:${candidate.identity.sourceRevision}`,'wiki-pageid:1|revision:1001']:['wiki-pageid:1|revision:1001'];return {packetKey:`packet:${key}`,workItemKey:`work:${key}`,branchKey:branch,workKind:`test_${branch}`,structuralCandidateKey:candidate?.key??null,candidateRole:candidate?'item_delivery_target_candidate':null,requiredChannels:required,sourceBoundaryContext:candidate?{sourcePageIdentity:candidate.identity,sourcePageEntityTypes:candidate.type.entityTypes}:{},sourceEvidenceKeys,channelObservations:channelObservations(required).map(item=>({...item,sourceEvidenceKeys})),capturePacketComplete:true,semanticEvidenceComplete:false,candidateMemberIdentityVerdict:null,sourcePageEntityTypeVerdict:null,structuralParentRelationshipVerdict:null,weightedTaskEntryMembershipVerdict:null,mappingVerdict:null,inventoryCompletenessVerdict:null,memberUniverseComplete:false,evidenceWorkComplete:false,automaticVerificationApplied:false,state:'revision_pinned_evidence_observations_captured_semantic_review_pending'};}
function evidenceRecord(){const sources=[source('parent','parent_inventory_source'),source('simple','candidate_subject_source'),source('multi','candidate_subject_source'),source('nested','candidate_subject_source')],dispositions=candidates.map(candidate=>({structuralCandidateKey:candidate.key,candidateRole:'item_delivery_target_candidate',sourcePageIdentity:candidate.identity,evidenceIntegrity:{complete:true},stableSourcePageSubjectIdentity:{supported:true},sourcePageEntityType:candidate.type,structuralParentRelationship:{supported:true,state:'supported_source_structural_relationship_not_parent_membership_verdict'},candidateMemberIdentityVerdict:null,parentMembershipVerdict:null,canonicalGameEntityIdentity:null,memberUniverseComplete:false,automaticVerificationApplied:false})),packets=[...candidates.map(candidate=>packet(`identity:${candidate.key}`,'reviewed_structural_candidate_member_identity_and_variant_scope_evidence',channels.identity,candidate)),packet('type:nested','unresolved_source_page_entity_type_evidence',channels.type,candidates[2]),...candidates.map(candidate=>packet(`membership:${candidate.key}`,'weighted_parent_task_entry_membership_evidence',channels.membership,candidate)),packet('mapping','declared_total_one_to_one_member_mapping_evidence',channels.mapping),packet('universe','complete_member_universe_reconciliation_evidence',channels.universe)];return {contract:policy.inputContract,memberCandidateKey:'member:test',structuralMemberCandidateIdentityDispositions:dispositions,structuralMemberCandidateSemanticGapEvidenceSources:sources,structuralMemberCandidateSemanticGapEvidencePackets:packets,structuralMemberCandidateSemanticGapEvidence:{captureCoverageComplete:true,semanticEvidenceWorkComplete:false,distinctRevisionPinnedSourceCount:sources.length,completeRevisionPinnedSourceCount:sources.length,workItemEvidencePacketCount:packets.length,completeCapturePacketCount:packets.length,memberUniverseComplete:false,automaticVerificationApplied:false},structuralMemberCandidateSemanticGapEvidenceReview:{state:'unreviewed_revision_pinned_semantic_gap_evidence_packets_ready_for_separate_branch_reviews',captureCoverageComplete:true,semanticEvidenceWorkComplete:false,memberUniverseComplete:false,automaticVerificationApplied:false},structuralMemberCandidateSemanticGapEvidenceWorkRouting:{evidenceKeyCount:0,completedWorkItemCount:0,evidenceWorkComplete:false,memberUniverseComplete:false},memberExpansionReview:{state:'unreviewed',memberKeys:[],evidenceKeys:[]},mechanicsReview:{state:'unreviewed',evidenceKeys:[]},optimizerEligible:false,accountIndependent:true,blockers:['revision_pinned_structural_member_candidate_semantic_gap_evidence_captured_reviews_pending'],state:policy.inputState,contentHash:'evidence-content-hash'};}

const input=evidenceRecord(),compiled=compileStructuralMemberCandidateSemanticGapEvidenceDispositionPolicy(policy,entityTypePolicy);assert.equal(compiled.valid,true);assert.deepEqual(compiled.invalidRules,[]);assert.deepEqual(compiled.invalidSupplementaryTypes,[]);assert.deepEqual(compiled.forbiddenPolicyPaths,[]);
const built=buildStructuralMemberCandidateSemanticGapEvidenceDispositions({evidenceRecords:[input],policy,entityTypePolicy,contentHash:hash});assert.equal(built.audit.publishable,true);assert.equal(built.audit.semanticDispositionCoverageComplete,true);assert.equal(built.audit.semanticEvidenceWorkComplete,false);assert.equal(built.audit.packetDispositionCoverage.evidencePacketCount,9);assert.equal(built.audit.packetDispositionCoverage.dispositionCount,9);assert.equal(built.audit.identityReviewReadinessCoverage.candidateIdentityDispositionCount,3);assert.equal(built.audit.identityReviewReadinessCoverage.reviewReadyCandidateIdentityCount,1);assert.equal(built.audit.identityReviewReadinessCoverage.reviewBlockedCandidateIdentityCount,2);assert.equal(built.audit.identityReviewReadinessCoverage.multiVariantScopeBlockedCount,1);assert.equal(built.audit.identityReviewReadinessCoverage.untypedOrNestedSubjectBindingBlockedCount,1);assert.deepEqual(built.audit.branchDispositionCoverage,{reviewed_structural_candidate_member_identity_and_variant_scope_evidence:3,unresolved_source_page_entity_type_evidence:1,structural_parent_relationship_reconciliation_evidence:0,weighted_parent_task_entry_membership_evidence:3,declared_total_one_to_one_member_mapping_evidence:1,complete_member_universe_reconciliation_evidence:1});
const output=built.records[0];assert.equal(output.structuralMemberCandidateSemanticGapEvidenceDisposition.candidateIdentityReviewReadyCount,1);assert.equal(output.structuralMemberCandidateSemanticGapEvidenceDisposition.completedSemanticGapWorkItemCount,0);assert.equal(output.structuralMemberCandidateSemanticGapEvidenceDisposition.canonicalGameEntityIdentityCount,0);assert.equal(output.structuralMemberCandidateSemanticGapEvidenceDispositionReview.candidateMemberIdentityVerdict,null);assert.equal(output.memberExpansionReview.state,'unreviewed');assert.equal(output.optimizerEligible,false);for(const disposition of output.structuralMemberCandidateSemanticGapEvidenceDispositions){assert.equal(disposition.candidateMemberIdentityVerdict,null);assert.equal(disposition.canonicalGameEntityIdentity,null);assert.equal(disposition.evidenceWorkComplete,false);}for(const field of recordContract.required)assert.ok(Object.hasOwn(output,field),`Missing required record field: ${field}`);for(const field of auditContract.required)assert.ok(Object.hasOwn(built.audit,field),`Missing required audit field: ${field}`);
const tamperedSource=structuredClone(input);tamperedSource.structuralMemberCandidateSemanticGapEvidenceSources[1].exactRevisionSourceText+=' changed';assert.equal(buildStructuralMemberCandidateSemanticGapEvidenceDispositions({evidenceRecords:[tamperedSource],policy,entityTypePolicy,contentHash:hash}).audit.publishable,false);
const tamperedPacket=structuredClone(input);tamperedPacket.structuralMemberCandidateSemanticGapEvidencePackets[0].channelObservations.pop();assert.equal(buildStructuralMemberCandidateSemanticGapEvidenceDispositions({evidenceRecords:[tamperedPacket],policy,entityTypePolicy,contentHash:hash}).audit.publishable,false);
const promoted=structuredClone(built.records);promoted[0].structuralMemberCandidateSemanticGapEvidenceDispositions[0].candidateMemberIdentityVerdict='verified';promoted[0].optimizerEligible=true;const promotedAudit=auditStructuralMemberCandidateSemanticGapEvidenceDispositions(promoted,{evidenceRecords:[input],policy,entityTypePolicy,contentHash:hash});assert.equal(promotedAudit.publishable,false);assert.ok(promotedAudit.blockers.includes('review_readiness_disposition_created_unsupported_verdict_or_promotion'));
const accountScoped=structuredClone(built.records);accountScoped[0].currentBaseLevel=34;assert.equal(auditStructuralMemberCandidateSemanticGapEvidenceDispositions(accountScoped,{evidenceRecords:[input],policy,entityTypePolicy,contentHash:hash}).publishable,false);
const specific=structuredClone(policy);specific.overrides={'candidate:simple':'ready'};assert.equal(compileStructuralMemberCandidateSemanticGapEvidenceDispositionPolicy(specific,entityTypePolicy).valid,false);
const automatic=structuredClone(policy);automatic.rules.automaticVerificationAllowed=true;assert.equal(compileStructuralMemberCandidateSemanticGapEvidenceDispositionPolicy(automatic,entityTypePolicy).valid,false);
const deterministic=buildStructuralMemberCandidateSemanticGapEvidenceDispositions({evidenceRecords:[structuredClone(input)],policy:structuredClone(policy),entityTypePolicy:structuredClone(entityTypePolicy),contentHash:hash});assert.deepEqual(deterministic,built);
console.log('Generic structural member candidate semantic-gap evidence disposition checks passed.');
