import assert from 'node:assert/strict';
import fs from 'node:fs';
import {
  auditStructuralMemberCandidateSemanticGapEvidenceWorkRoutes,
  buildStructuralMemberCandidateSemanticGapEvidenceWorkRoutes,
  compileStructuralMemberCandidateSemanticGapEvidenceWorkRoutingPolicy
} from '../transforms/structural-member-candidate-semantic-gap-evidence-work-routing-lib.mjs';

const policy=JSON.parse(fs.readFileSync('platform/policies/structural-member-candidate-semantic-gap-evidence-work-routing-v1.json','utf8'));
const recordContract=JSON.parse(fs.readFileSync('platform/contracts/structural-member-candidate-semantic-gap-evidence-work-routing-v1.json','utf8'));
const auditContract=JSON.parse(fs.readFileSync('platform/contracts/structural-member-candidate-semantic-gap-evidence-work-routing-audit-v1.json','utf8'));
const parentBranches=['declared_total_one_to_one_member_mapping_evidence','complete_member_universe_reconciliation_evidence'];

function disposition(index,{typed=true,types=['item_page'],relationship=true,role='item_delivery_target_candidate',prefix='1'}={}){return {dispositionKey:`candidate:${prefix}:${index}|semantic-disposition`,workItemKey:`candidate:${prefix}:${index}|identity`,structuralCandidateKey:`candidate:${prefix}:${index}`,candidateRole:role,sourceEvidenceKey:`source:${prefix}:${index}`,sourcePageIdentity:{sourcePageId:500+index,resolvedTitle:`Subject ${prefix} ${index}`,sourceRevision:String(6000+index),sourceTimestamp:'2026-01-01T00:00:00Z',sourceUrl:`https://oldschool.runescape.wiki/w/Subject_${prefix}_${index}`,sourceContentHash:`hash-${prefix}-${index}`},evidenceIntegrity:{checks:{complete:true},complete:true},stableSourcePageSubjectIdentity:{state:'supported_revision_pinned_source_page_subject_identity',supported:true,evidenceKey:`source:${prefix}:${index}`},sourcePageEntityType:{state:typed?(types.length>1?'multi_typed':'typed'):'untyped',entityTypes:typed?types:[],evidence:[],classified:typed,canonicalGameEntityIdentity:null},structuralParentRelationship:{state:relationship?'supported_source_structural_relationship_not_parent_membership_verdict':'blocked_structural_relationship_evidence_or_role_coherence_failure',relationshipClass:relationship?'source_lists_subject_as_item_delivery_target':null,requiredSourcePageTypes:[],missingRequiredSourcePageTypes:[],roleTypeCoherenceState:relationship?'supported_required_source_page_type_present':'blocked_required_source_page_type_missing',supported:relationship,parentMembershipVerdict:null,weightedTaskEntryMembershipVerdict:null,evidence:{}},candidateMemberIdentityVerdict:null,parentMembershipVerdict:null,oneToOneTaskEntryMappingVerdict:null,inventoryCompletenessVerdict:null,memberUniverseComplete:false,repeatabilityVerdict:null,canonicalGameEntityIdentity:null,automaticVerificationApplied:false,state:'reviewed_generic_source_identity_page_type_and_structural_parent_relation_disposition_gates_closed'};}
function priorCompletenessItem(branch,index){return {workItemOrdinal:index+1,workItemKey:`member:1|${branch}`,branchKey:branch,workKind:'prior_work',sourceBoundaryContext:{prior:true},evidenceKeys:[],mappingVerdict:null,inventoryCompletenessVerdict:null,memberUniverseComplete:false,evidenceWorkComplete:false,automaticVerificationApplied:false,workState:`blocked_pending_${branch}`};}
function inputRecord(key='1'){
  const dispositions=[disposition(1,{prefix:key}),disposition(2,{prefix:key,types:['equipment_page','item_page']}),disposition(3,{prefix:key,role:'message_delivery_recipient_candidate',types:['npc_page']}),disposition(4,{prefix:key,typed:false,types:[],role:'narrative_assigned_task_class_candidate'}),disposition(5,{prefix:key,relationship:false})];
  return {contract:policy.inputContract,memberCandidateKey:`member:${key}`,canonicalActivityIdentity:{canonicalActivityKey:`activity:${key}`,canonicalLabel:'Test activity'},canonicalGameEntityIdentity:null,parentMemberInventoryDisposition:{declaredTotalAssessments:[{observedQuantity:5}],nonExhaustiveQualificationAssessments:[{qualificationClass:'source_authored_non_exhaustive_inventory_warning'}],arithmeticAssessment:{structuralCandidateCount:5,countAlignmentObserved:true,countAlignmentCanProveOneToOneMembership:false,countAlignmentCanProveInventoryCompleteness:false},memberIdentityVerdict:null,inventoryCompletenessVerdict:null,memberUniverseComplete:false},parentMemberCandidateIdentityAndCompletenessEvidenceWorkRouting:{completenessWorkItemCount:2,completenessWorkItems:parentBranches.map(priorCompletenessItem),evidenceWorkComplete:false,memberUniverseComplete:false},structuralMemberCandidateIdentityDispositions:dispositions,structuralMemberCandidateIdentityDisposition:{state:'partial_generic_candidate_semantic_disposition_explicit_gaps_retained',candidateDispositionCount:dispositions.length,sourceEvidenceIntegrityComplete:true,stableSubjectIdentityDispositionCount:dispositions.length,sourcePageTypedCount:4,sourcePageUntypedCount:1,sourcePageMultiTypedCount:1,structuralParentRelationshipDispositionCount:4,candidateMemberIdentityVerdict:null,parentMembershipVerdict:null,oneToOneTaskEntryMappingVerdict:null,inventoryCompletenessVerdict:null,memberUniverseComplete:false,canonicalGameEntityIdentityCount:0,automaticVerificationApplied:false,evidenceWorkComplete:false},structuralMemberCandidateIdentityDispositionReview:{state:'reviewed_generic_fail_closed_source_identity_page_type_and_structural_parent_relation_disposition',stableSubjectIdentityDispositionComplete:true,sourcePageEntityTypeDispositionComplete:false,structuralParentRelationshipDispositionComplete:false,candidateMemberIdentityVerdict:null,parentMembershipVerdict:null,oneToOneTaskEntryMappingVerdict:null,inventoryCompletenessVerdict:null,memberUniverseComplete:false,evidenceWorkComplete:false,automaticVerificationApplied:false,evidenceKeys:dispositions.map(item=>item.sourceEvidenceKey)},memberExpansionReview:{state:'unreviewed',memberKeys:[],evidenceKeys:[]},mechanicsReview:{state:'unreviewed',evidenceKeys:[]},optimizerEligible:false,accountIndependent:true,blockers:['one_or_more_candidate_source_pages_remain_untyped','one_or_more_structural_parent_relationships_remain_unresolved','member_universe_completeness_not_proven'],state:policy.inputState,contentHash:`disposition-${key}`};
}

const input=inputRecord(),compiled=compileStructuralMemberCandidateSemanticGapEvidenceWorkRoutingPolicy(policy);assert.equal(compiled.valid,true);assert.deepEqual(compiled.invalidRules,[]);assert.deepEqual(compiled.invalidCandidateBranches,[]);assert.deepEqual(compiled.invalidParentBranches,[]);assert.deepEqual(compiled.duplicateBranchKeys,[]);assert.deepEqual(compiled.forbiddenPolicyPaths,[]);
const built=buildStructuralMemberCandidateSemanticGapEvidenceWorkRoutes({dispositionRecords:[input],policy});assert.equal(built.audit.publishable,true);assert.equal(built.audit.routingCoverageComplete,true);assert.equal(built.audit.evidenceWorkComplete,false);assert.equal(built.audit.routingCoverage.candidateDispositionCount,5);assert.equal(built.audit.routingCoverage.candidateIdentityAndVariantScopeWorkItemCount,5);assert.equal(built.audit.routingCoverage.sourcePageEntityTypeWorkItemCount,1);assert.equal(built.audit.routingCoverage.structuralParentRelationshipReconciliationWorkItemCount,1);assert.equal(built.audit.routingCoverage.weightedParentTaskEntryMembershipWorkItemCount,4);assert.equal(built.audit.routingCoverage.parentCompletenessWorkItemCount,2);assert.equal(built.audit.routingCoverage.totalWorkItemCount,13);assert.equal(built.audit.routingCoverage.blockedWorkItemCount,13);assert.equal(built.audit.routingCoverage.completedWorkItemCount,0);assert.equal(built.audit.routingCoverage.evidenceKeyCount,0);assert.equal(built.audit.branchSeparationCoverage.declaredTotalMappingBranchCount,1);assert.equal(built.audit.branchSeparationCoverage.completeUniverseBranchCount,1);
const output=built.records[0],route=output.structuralMemberCandidateSemanticGapEvidenceWorkRouting;assert.equal(route.candidateIdentityAndVariantScopeWorkItemCount,5);assert.deepEqual(route.sourcePageEntityTypeWorkItems.map(item=>item.structuralCandidateKey),['candidate:1:4']);assert.deepEqual(route.structuralParentRelationshipReconciliationWorkItems.map(item=>item.structuralCandidateKey),['candidate:1:5']);assert.ok(!route.weightedParentTaskEntryMembershipWorkItems.some(item=>item.structuralCandidateKey==='candidate:1:5'));assert.deepEqual(route.parentCompletenessWorkItems.map(item=>item.branchKey),parentBranches);assert.ok([...route.candidateIdentityAndVariantScopeWorkItems,...route.sourcePageEntityTypeWorkItems,...route.structuralParentRelationshipReconciliationWorkItems,...route.weightedParentTaskEntryMembershipWorkItems].every(item=>!item.evidenceKeys.length&&item.candidateMemberIdentityVerdict===null&&item.sourcePageEntityTypeVerdict===null&&item.structuralParentRelationshipVerdict===null&&item.weightedTaskEntryMembershipVerdict===null&&item.evidenceWorkComplete===false&&item.automaticVerificationApplied===false));assert.ok(route.parentCompletenessWorkItems.every(item=>!item.evidenceKeys.length&&item.mappingVerdict===null&&item.inventoryCompletenessVerdict===null&&item.memberUniverseComplete===false&&item.evidenceWorkComplete===false));assert.equal(output.structuralMemberCandidateIdentityDisposition.memberUniverseComplete,false);assert.equal(output.parentMemberCandidateIdentityAndCompletenessEvidenceWorkRouting.completenessWorkItems[0].evidenceWorkComplete,false);assert.equal(output.memberExpansionReview.state,'unreviewed');assert.equal(output.optimizerEligible,false);for(const field of recordContract.required)assert.ok(Object.hasOwn(output,field),`Missing required record field: ${field}`);for(const field of auditContract.required)assert.ok(Object.hasOwn(built.audit,field),`Missing required audit field: ${field}`);

const multi=buildStructuralMemberCandidateSemanticGapEvidenceWorkRoutes({dispositionRecords:[input,inputRecord('2')],policy});assert.equal(multi.audit.publishable,true);assert.equal(multi.records.length,2);assert.equal(multi.audit.routingCoverage.totalWorkItemCount,26);
const specific=structuredClone(policy);specific.overrides={'candidate:1':'complete'};assert.equal(compileStructuralMemberCandidateSemanticGapEvidenceWorkRoutingPolicy(specific).valid,false);
const automatic=structuredClone(policy);automatic.rules.automaticVerificationAllowed=true;assert.equal(compileStructuralMemberCandidateSemanticGapEvidenceWorkRoutingPolicy(automatic).valid,false);
const altered=structuredClone(built.records);altered[0].structuralMemberCandidateSemanticGapEvidenceWorkRouting.sourcePageEntityTypeWorkItems.push(structuredClone(altered[0].structuralMemberCandidateSemanticGapEvidenceWorkRouting.sourcePageEntityTypeWorkItems[0]));const alteredAudit=auditStructuralMemberCandidateSemanticGapEvidenceWorkRoutes(altered,{dispositionRecords:[input],policy});assert.equal(alteredAudit.publishable,false);assert.ok(alteredAudit.blockers.includes('one_or_more_semantic_gap_routes_do_not_match_generic_policy'));
const promoted=structuredClone(built.records);promoted[0].structuralMemberCandidateSemanticGapEvidenceWorkRouting.candidateIdentityAndVariantScopeWorkItems[0].candidateMemberIdentityVerdict='verified';promoted[0].structuralMemberCandidateSemanticGapEvidenceWorkRouting.completedWorkItemCount=1;promoted[0].structuralMemberCandidateSemanticGapEvidenceWorkRouting.evidenceWorkComplete=true;promoted[0].memberExpansionReview.state='reviewed';promoted[0].optimizerEligible=true;const promotedAudit=auditStructuralMemberCandidateSemanticGapEvidenceWorkRoutes(promoted,{dispositionRecords:[input],policy});assert.equal(promotedAudit.publishable,false);assert.ok(promotedAudit.blockers.includes('routing_created_unsupported_identity_page_type_relationship_membership_completeness_repeatability_mechanics_or_optimizer_promotion'));
const accountScoped=structuredClone(built.records);accountScoped[0].currentBaseLevel=34;assert.equal(auditStructuralMemberCandidateSemanticGapEvidenceWorkRoutes(accountScoped,{dispositionRecords:[input],policy}).publishable,false);
const deterministic=buildStructuralMemberCandidateSemanticGapEvidenceWorkRoutes({dispositionRecords:[structuredClone(input)],policy:structuredClone(policy)});assert.deepEqual(deterministic,built);
console.log('Generic structural member candidate semantic-gap evidence-work routing checks passed.');
