import fs from 'node:fs';
import {buildUnlockStatementSemanticCrosswalk,auditUnlockStatementSemanticCrosswalk,compileUnlockStatementRolePolicy} from '../transforms/unlock-statement-semantic-crosswalk-lib.mjs';

const policy=JSON.parse(fs.readFileSync('platform/policies/unlock-statement-source-role-v1.json','utf8')),failures=[],check=(condition,message)=>{if(!condition)failures.push(message)},statements=[{entryKey:'crafting:members1:1',sourceLeadingVerb:'Craft',sourceText:'* Craft [[Example item]]',linkedTargets:['Example item'],sourceLocator:{lineStart:3,lineEnd:3}},{entryKey:'crafting:members2:1',sourceLeadingVerb:null,sourceText:'* {{plink|Unclear unlock}}',linkedTargets:['Unclear unlock'],sourceLocator:{lineStart:4,lineEnd:4}}],unlockRecords=[{skillKey:'crafting',skill:'Crafting',sourceRevision:'456',sourceTimestamp:'2026-09-03T00:00:00Z',sourceUrl:'https://example.test/Crafting',rawInventoryComplete:true,parameters:[{availability:'members',level:1,entries:[statements[0]]},{availability:'members',level:2,entries:[statements[1]]}]}],identities=[{targetKey:'wiki-title:example item',requestedTitle:'Example item',resolvedTitle:'Example item',resolutionState:'revision_pinned_wiki_page',sourceRevision:'123',sourceTimestamp:'2026-09-03T00:00:00Z',sourceUrl:'https://example.test/Example_item',entityType:null,canonicalEntityIdentity:false},{targetKey:'wiki-title:unclear unlock',requestedTitle:'Unclear unlock',resolvedTitle:'Unclear unlock',resolutionState:'revision_pinned_wiki_page',sourceRevision:'124',sourceTimestamp:'2026-09-03T00:00:00Z',sourceUrl:'https://example.test/Unclear_unlock',entityType:null,canonicalEntityIdentity:false}],built=buildUnlockStatementSemanticCrosswalk({unlockRecords,linkedPageIdentities:identities,policy}),craft=built.records[0],unclear=built.records[1],compiled=compileUnlockStatementRolePolicy(policy);
check(compiled.duplicateForms.length===0&&compiled.formToRole.size===114,'The versioned policy must map all 114 observed source-leading forms exactly once.');
check(craft.sourceRole.role==='production_action_candidate'&&craft.activityDiscoveryCandidate,'An explicit production verb should route to a discovery-candidate role.');
check(craft.canonicalActivityIdentity===null&&craft.repeatableTrainingActivity===null&&craft.optimizerEligible===false,'Surface-form routing must never promote a canonical or repeatable activity.');
check(unclear.sourceLeadingForm==='<none>'&&unclear.sourceRole.routingState==='explicitly_unresolved'&&unclear.blockers.includes('source_statement_surface_form_unresolved'),'Statements without a leading form must remain explicitly unresolved.');
check(built.audit.inputStatementCoverage.exactStatementSetMatch&&built.audit.sourceRoleCoverage.sourceRoleRoutingComplete,'Every raw statement must be routed exactly once.');
check(built.audit.sourceRoleCoverage.explicitlyUnresolvedStatementCount===1&&built.audit.canonicalActivityIdentityCount===0&&built.audit.completeActivityUniverse===false,'Unresolved forms and zero promoted identities must remain measurable.');
const unknownRecords=[{...unlockRecords[0],parameters:[{availability:'members',level:1,entries:[{...statements[0],sourceLeadingVerb:'UnknownVerb'}]}]}],unknown=buildUnlockStatementSemanticCrosswalk({unlockRecords:unknownRecords,linkedPageIdentities:identities,policy});
check(!unknown.audit.publishable&&unknown.audit.sourceRoleCoverage.unmappedForms.includes('UnknownVerb'),'New source-leading forms must fail the routing gate instead of falling into a generic activity bucket.');
const promoted=built.records.map((row,index)=>index?row:{...row,optimizerEligible:true}),promotionAudit=auditUnlockStatementSemanticCrosswalk(promoted,{unlockRecords,linkedPageIdentities:identities,policy});
check(!promotionAudit.publishable&&promotionAudit.blockers.includes('unverified_activity_promotion_detected'),'Unverified optimizer promotion must fail closed.');
const malformed=built.records.map((row,index)=>index?row:{...row,sourceRole:null}),malformedAudit=auditUnlockStatementSemanticCrosswalk(malformed,{unlockRecords,linkedPageIdentities:identities,policy});
check(!malformedAudit.publishable&&malformedAudit.blockers.includes('one_or_more_statement_role_routes_invalid'),'Missing or policy-mismatched statement roles must fail the routing gate.');
if(failures.length){console.error(failures.join('\n'));process.exit(1)}console.log('Cross-skill unlock-statement semantic routing checks passed.');
