import fs from 'node:fs';
import {buildUnlockLinkedPageEntityTypes,auditUnlockLinkedPageEntityTypes,compileUnlockLinkedPageEntityTypePolicy} from '../transforms/unlock-linked-page-entity-type-lib.mjs';

const policy=JSON.parse(fs.readFileSync('platform/policies/unlock-linked-page-entity-type-v1.json','utf8')),failures=[],check=(condition,message)=>{if(!condition)failures.push(message)},source={sourcePageId:1234,sourceRevision:'123',sourceTimestamp:'2026-09-03T00:00:00Z',sourceUrl:'https://example.test/Item',sourceContentHash:'abc'},context={requestedFragment:null,redirected:false,referencedBy:{skillKeys:['attack'],statementKeys:['attack:members1:1']}},signatures=[{targetKey:'wiki-title:item',requestedTitle:'Item',resolvedTitle:'Item',rootTemplates:[{template:'Infobox Item',templateKey:'infobox item',line:2},{template:'Infobox Bonuses',templateKey:'infobox bonuses',line:10}],accountIndependent:true,...context,...source},{targetKey:'wiki-title:activity',requestedTitle:'Activity',resolvedTitle:'Activity',rootTemplates:[{template:'Infobox Activity',templateKey:'infobox activity',line:1}],accountIndependent:true,...context,...source},{targetKey:'wiki-title:collection',requestedTitle:'Collection',resolvedTitle:'Collection',rootTemplates:[{template:'External',templateKey:'external',line:1}],accountIndependent:true,...context,...source}],built=buildUnlockLinkedPageEntityTypes({signatures,policy}),item=built.records[0],activity=built.records[1],untyped=built.records[2],compiled=compileUnlockLinkedPageEntityTypePolicy(policy);
check(compiled.duplicateTemplateSignals.length===0&&compiled.templateToType.size===23,'The explicit entity-type policy must contain 23 unique root-template signals.');
check(item.classificationState==='multi_typed'&&item.entityTypes.join('|')==='equipment_page|item_page'&&item.entityTypeEvidence.every(row=>row.sourceRevision==='123'&&row.sourceContentHash==='abc'),'Every page type must be supported by exact revision-bound template evidence, including legitimate multi-type pages.');
check(item.source.sourcePageId===1234&&item.referencedBy.skillKeys[0]==='attack','Page ID and original statement context must survive type routing for later equivalence grouping.');
check(activity.activityPageCandidate&&activity.repeatabilityEvidence.state==='unproven'&&activity.repeatableTrainingActivity===null&&activity.optimizerEligible===false,'An explicit activity infobox may identify an activity page candidate but must not prove repeatability or optimizer eligibility.');
check(untyped.classificationState==='untyped'&&untyped.blockers.includes('no_policy_mapped_root_template_type_evidence'),'Unmatched collection pages must remain explicitly untyped.');
check(built.audit.pageTypeRoutingComplete&&!built.audit.entityTypeClassificationComplete&&built.audit.entityTypeCoverage.untypedPageCount===1&&built.audit.repeatabilityProvenCount===0,'Complete routing must remain separate from complete type and repeatability coverage.');
const unsupported=built.records.map((row,index)=>index?row:{...row,entityTypes:['monster_page']}),unsupportedAudit=auditUnlockLinkedPageEntityTypes(unsupported,{signatures,policy});
check(!unsupportedAudit.publishable&&unsupportedAudit.blockers.includes('one_or_more_entity_type_records_not_supported_by_exact_source_evidence'),'Unsupported or altered type classifications must fail publication.');
const polluted=built.records.map((row,index)=>index?row:{...row,currentBaseLevel:34}),pollutedAudit=auditUnlockLinkedPageEntityTypes(polluted,{signatures,policy});
check(!pollutedAudit.publishable&&pollutedAudit.blockers.includes('account_query_state_baked_into_entity_type_records'),'Current account state must not enter reusable page semantics.');
if(failures.length){console.error(failures.join('\n'));process.exit(1)}console.log('Cross-skill linked-page entity-type checks passed.');
