import {buildUnlockLinkedPageWikiEquivalence,auditUnlockLinkedPageWikiEquivalence} from '../transforms/unlock-linked-page-wiki-equivalence-lib.mjs';

const failures=[],check=(condition,message)=>{if(!condition)failures.push(message)},source=(pageId,revision,title)=>({sourcePageId:pageId,sourceRevision:String(revision),sourceTimestamp:'2026-09-03T00:00:00Z',sourceUrl:`https://oldschool.runescape.wiki/w/${title.replaceAll(' ','_')}`,sourceContentHash:`hash-${pageId}`}),row=({targetKey,requestedTitle,fragment=null,redirected=false,pageId=10,title='Training Ground',type='activity_page',skill='attack',statement='attack:members1:1'})=>({targetKey,requestedTitle,requestedFragment:fragment,redirected,referencedBy:{skillKeys:[skill],statementKeys:[statement]},resolvedTitle:title,entityTypes:type?[type]:[],classificationState:type?'typed':'untyped',pageTypeClassified:Boolean(type),activityPageCandidate:type==='activity_page',canonicalEntityIdentity:false,canonicalActivityIdentity:null,repeatableTrainingActivity:null,optimizerEligible:false,source:source(pageId,100+pageId,title),accountIndependent:true}),entityRecords=[row({targetKey:'wiki-title:training ground#first',requestedTitle:'Training Ground#First',fragment:'First'}),row({targetKey:'wiki-title:old training room',requestedTitle:'Old training room',redirected:true,skill:'defence',statement:'defence:members1:1'}),row({targetKey:'wiki-title:collection',requestedTitle:'Collection',pageId:11,title:'Collection',type:null,skill:'crafting',statement:'crafting:members1:1'})],built=buildUnlockLinkedPageWikiEquivalence({entityRecords}),activity=built.records.find(record=>record.sourcePageId===10),untyped=built.records.find(record=>record.sourcePageId===11);
check(built.records.length===2&&activity.targetReferenceCount===2&&activity.canonicalWikiPageKey==='osrs-wiki-pageid:10','Two aliases for the same stable Wiki page ID must form one evidence-page group.');
check(activity.targetReferences.some(reference=>reference.requestedFragment==='First')&&activity.targetReferences.some(reference=>reference.redirected)&&activity.targetReferences.flatMap(reference=>reference.referencedBy.skillKeys).includes('defence'),'Fragments, redirect state, skills, and statement contexts must survive grouping.');
check(activity.activityPageCandidate&&activity.canonicalGameEntityIdentity===null&&activity.canonicalActivityIdentity===null&&activity.repeatableTrainingActivity===null&&!activity.optimizerEligible,'A canonical Wiki page must not become a canonical game entity or repeatable optimizer activity.');
check(!untyped.pageTypeClassified&&untyped.blockers.includes('page_type_not_complete'),'Untyped pages must remain explicit after page-equivalence grouping.');
check(built.audit.wikiPageEquivalenceComplete&&built.audit.inputTargetCoverage.exactTargetSetMatch&&built.audit.pageIdentityCoverage.multiReferenceGroupCount===1&&built.audit.pageIdentityCoverage.consolidatedDuplicateReferenceCount===1,'The audit must measure exact reference preservation and safe alias consolidation.');
const conflictRows=[entityRecords[0],{...entityRecords[1],source:{...entityRecords[1].source,sourceContentHash:'different'}}],conflict=buildUnlockLinkedPageWikiEquivalence({entityRecords:conflictRows});
check(!conflict.audit.publishable&&conflict.audit.blockers.includes('same_wiki_page_id_has_conflicting_revision_or_type_evidence'),'Conflicting evidence under one page ID must fail publication.');
const contextChanged=built.records.map((record,index)=>index?record:{...record,targetReferences:record.targetReferences.map((reference,referenceIndex)=>referenceIndex?reference:{...reference,requestedFragment:'Changed'})}),contextChangedAudit=auditUnlockLinkedPageWikiEquivalence(contextChanged,{entityRecords});
check(!contextChangedAudit.publishable&&contextChangedAudit.inputTargetCoverage.contextMismatchTargetKeys.length===1&&contextChangedAudit.blockers.includes('one_or_more_target_reference_contexts_changed_during_grouping'),'Changed alias, fragment, redirect, skill, statement, or type context must fail publication even when target keys still match.');
const polluted=built.records.map((record,index)=>index?record:{...record,currentBaseLevel:34}),pollutedAudit=auditUnlockLinkedPageWikiEquivalence(polluted,{entityRecords});
check(!pollutedAudit.publishable&&pollutedAudit.blockers.includes('account_query_state_baked_into_wiki_page_equivalence'),'Current account state must not enter reusable page equivalence.');
if(failures.length){console.error(failures.join('\n'));process.exit(1)}console.log('Cross-skill linked-page Wiki-equivalence checks passed.');
