import {buildUnlockLinkedPageIdentities,collectUnlockLinkedTargetReferences} from '../ingestion/unlock-linked-page-identity-lib.mjs';

const failures=[],check=(condition,message)=>{if(!condition)failures.push(message)},unlockRecords=[{skillKey:'crafting',skill:'Crafting',rawInventoryComplete:true,parameters:[{availability:'members',level:1,entries:[{entryKey:'crafting:members1:1',linkedTargets:['Old name','Missing item']},{entryKey:'crafting:members1:2',linkedTargets:['Old name']}]}]},{skillKey:'magic',skill:'Magic',rawInventoryComplete:true,parameters:[{availability:'free_to_play',level:1,entries:[{entryKey:'magic:freeplay1:1',linkedTargets:[]}]}]}],resolutions=[{requestedTitle:'Old name',normalizedTitle:'Old name',resolvedTitle:'Canonical name',redirected:true,page:{title:'Canonical name',pageid:1,revisions:[{revid:123,timestamp:'2026-09-03T00:00:00Z'}]}},{requestedTitle:'Missing item',normalizedTitle:'Missing item',resolvedTitle:'Missing item',redirected:false,page:{title:'Missing item',missing:true}}],built=buildUnlockLinkedPageIdentities({unlockRecords,resolutions}),oldName=built.records.find(row=>row.requestedTitle==='Old name'),missing=built.records.find(row=>row.requestedTitle==='Missing item');
check(collectUnlockLinkedTargetReferences(unlockRecords).length===2,'Every distinct explicit linked target must be collected exactly once.');
check(oldName.referenceCount===2&&oldName.redirected&&oldName.resolvedTitle==='Canonical name'&&oldName.sourceRevision==='123','Redirected pages must retain request identity, references, resolved title, and revision.');
check(oldName.canonicalEntityIdentity===false&&oldName.repeatableTrainingActivity===null&&oldName.optimizerEligible===false,'A resolved Wiki page must not become a typed entity or optimizer activity.');
check(missing.resolutionState==='missing_wiki_page'&&missing.blockers.includes('linked_wiki_page_missing'),'Missing pages must remain explicit blockers.');
check(built.audit.resolutionAttemptCoverageComplete&&built.audit.publishable,'A complete set of resolution attempts remains publishable evidence even when a page is missing.');
check(!built.audit.revisionPinnedPageIdentityCoverageComplete&&built.audit.completeActivityUniverse===false&&built.audit.canonicalActivityIdentityCount===0,'Missing pages and untyped identities must block canonical and universe coverage.');
const dropped=buildUnlockLinkedPageIdentities({unlockRecords,resolutions:resolutions.slice(0,1)});
check(dropped.records.find(row=>row.requestedTitle==='Missing item').resolutionState==='missing_api_resolution_response'&&!dropped.audit.publishable,'An absent API resolution response must fail the structural publication gate.');
const polluted=built.records.map((row,index)=>index?row:{...row,currentBaseLevel:34}),pollutedAudit=(await import('../ingestion/unlock-linked-page-identity-lib.mjs')).auditUnlockLinkedPageIdentities(polluted,{unlockRecords});
check(!pollutedAudit.publishable&&pollutedAudit.blockers.includes('account_query_state_baked_into_linked_page_crosswalk'),'Account query state must be rejected from the reusable identity crosswalk.');
if(failures.length){console.error(failures.join('\n'));process.exit(1)}console.log('Cross-skill linked-page identity checks passed.');
